uicore::HalfFloat Class Reference - UICore SDK
uicore::HalfFloat Class Reference
#include <half_float.h>
Public Member Functions
HalfFloat ()
HalfFloat (const HalfFloat &other)
HalfFloat (float v)
HalfFloat & from_float (float v)
operator float () const
HalfFloat & operator= (const HalfFloat &other)
HalfFloat & operator= (const float v)
float to_float () const
Static Public Member Functions
static unsigned short float_to_half (float float_value)
static unsigned short float_to_half_simple (float float_value)
Only works for 'normal' half-float values.
static float half_to_float (unsigned short hf)
static float half_to_float_simple (unsigned short hf)
Only works for 'normal' half-float values.
Constructor & Destructor Documentation
uicore::HalfFloat::HalfFloat () inline
uicore::HalfFloat::HalfFloat (const HalfFloat & other) inline
uicore::HalfFloat::HalfFloat (float v) inline
Member Function Documentation
static unsigned short uicore::HalfFloat::float_to_half (float float_value) inline static
References uicore::f.
Referenced by from_float().
static unsigned short uicore::HalfFloat::float_to_half_simple (float float_value) inline static
Only works for 'normal' half-float values.
References uicore::f.
HalfFloat& uicore::HalfFloat::from_float (float v) inline
References float_to_half().
Referenced by operator=().
static float uicore::HalfFloat::half_to_float (unsigned short hf) inline static
Referenced by to_float().
static float uicore::HalfFloat::half_to_float_simple (unsigned short hf) inline static
Only works for 'normal' half-float values.
uicore::HalfFloat::operator float () const inline
References to_float().
HalfFloat& uicore::HalfFloat::operator= (const HalfFloat & other) inline
HalfFloat& uicore::HalfFloat::operator= (const float v) inline
References from_float().
float uicore::HalfFloat::to_float () const inline
References half_to_float().
Referenced by operator float().
The documentation for this class was generated from the following file:
half_float.h