uicore::Texture3D Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::Texture3D Class Reference abstract
3D texture object class.
#include <texture_3d.h>
Public Member Functions
virtual int depth () const =0
Get the texture depth.
virtual int height () const =0
Get the texture height.
virtual void set_image (const GraphicContextPtr &context, const PixelBufferPtr &image, int depth, int level=0)=0
Upload image to texture.
virtual void set_subimage (const GraphicContextPtr &context, int x, int y, int z, const PixelBufferPtr &image, const Rect &src_rect, int level=0)=0
Upload image to sub texture.
virtual void set_wrap_mode (TextureWrapMode wrap_s, TextureWrapMode wrap_t, TextureWrapMode wrap_r)=0
Set the texture wrapping mode.
Vec3i size () const
Get the texture size.
virtual int width () const =0
Get the texture width.
virtual TextureWrapMode wrap_mode_r () const =0
Get the texture wrap mode for the r coordinate.
virtual TextureWrapMode wrap_mode_s () const =0
Get the texture wrap mode for the s coordinate.
virtual TextureWrapMode wrap_mode_t () const =0
Get the texture wrap mode for the t coordinate.
Public Member Functions inherited from uicore::Texture
virtual int base_level () const =0
Get the texture base level.
virtual CompareFunction compare_function () const =0
Get the texture compare function.
virtual TextureCompareMode compare_mode () const =0
Get the texture compare mode.
virtual void generate_mipmap ()=0
Generate mipmap textures.
virtual float lod_bias () const =0
Get the level of detail bias constant.
virtual TextureFilter mag_filter () const =0
Get the texture magnification filter.
virtual int max_level () const =0
Get the texture max level.
virtual float max_lod () const =0
Get the maximum level of detail.
virtual TextureFilter min_filter () const =0
Get the texture minification filter.
virtual float min_lod () const =0
Get the minimum level of detail.
virtual void set_base_level (int base_level)=0
Sets the texture base level texture parameter.
virtual void set_lod_bias (float lod_bias)=0
Sets the level of detail bias constant.
virtual void set_mag_filter (TextureFilter filter)=0
Set the magnification filter.
virtual void set_max_anisotropy (float max_anisotropy)=0
Set the maximum degree of anisotropy.
virtual void set_max_level (int max_level)=0
Sets the texture max level texture parameter.
virtual void set_max_lod (float max_lod)=0
Set the maximum level of detail texture parameter.
virtual void set_min_filter (TextureFilter filter)=0
Set the minification filter.
virtual void set_min_lod (float min_lod)=0
Set the minimum level of detail texture parameter.
virtual void set_texture_compare (TextureCompareMode mode, CompareFunction func)=0
Sets the texture compare mode and compare function texture parameters.
virtual TextureObject * texture_object ()=0
Static Public Member Functions
static std::shared_ptr< Texture3D > create (const GraphicContextPtr &context, int width, int height, int depth, TextureFormat texture_format=tf_rgba8, int levels=1)
Constructs a 3D texture.
static std::shared_ptr< Texture3D > create (const GraphicContextPtr &context, const Vec3i &size, TextureFormat texture_format=tf_rgba8, int levels=1)
Static Public Member Functions inherited from uicore::Texture
static std::shared_ptr< Texture > create (const GraphicContextPtr &gc, PixelBufferSetPtr pixelbuffer_set)
Constructs a texture as described by a pixelbuffer set.
Detailed Description
3D texture object class.
Member Function Documentation
static std::shared_ptr<Texture3D> uicore::Texture3D::create (const GraphicContextPtr & context, int width, int height, int depth, TextureFormat texture_format = tf_rgba8, int levels = 1) static
Constructs a 3D texture.
Parameters
context = Graphic Context
width = value
height = value
depth = value
internal_format = Texture Format
levels = Mipmap levels for the texture. 0 = all levels
static std::shared_ptr<Texture3D> uicore::Texture3D::create (const GraphicContextPtr & context, const Vec3i & size, TextureFormat texture_format = tf_rgba8, int levels = 1) static
virtual int uicore::Texture3D::depth () const pure virtual
Get the texture depth.
Referenced by size().
virtual int uicore::Texture3D::height () const pure virtual
Get the texture height.
Referenced by size().
virtual void uicore::Texture3D::set_image (const GraphicContextPtr & context, const PixelBufferPtr & image, int depth, int level = 0) pure virtual
Upload image to texture.
Parameters
context Graphic context to use for the request
image Image to upload.
level Mipmap level-of-detail number.
virtual void uicore::Texture3D::set_subimage (const GraphicContextPtr & context, int x, int y, int z, const PixelBufferPtr & image, const Rect & src_rect, int level = 0) pure virtual
Upload image to sub texture.
Parameters
context Graphic context to use for the request
image Image to upload.
level Mipmap level-of-detail number.
virtual void uicore::Texture3D::set_wrap_mode (TextureWrapMode wrap_s, TextureWrapMode wrap_t, TextureWrapMode wrap_r) pure virtual
Set the texture wrapping mode.
Vec3i uicore::Texture3D::size () const inline
Get the texture size.
References depth(), height(), and width().
virtual int uicore::Texture3D::width () const pure virtual
Get the texture width.
Referenced by size().
virtual TextureWrapMode uicore::Texture3D::wrap_mode_r () const pure virtual
Get the texture wrap mode for the r coordinate.
virtual TextureWrapMode uicore::Texture3D::wrap_mode_s () const pure virtual
Get the texture wrap mode for the s coordinate.
virtual TextureWrapMode uicore::Texture3D::wrap_mode_t () const pure virtual
Get the texture wrap mode for the t coordinate.
The documentation for this class was generated from the following file:
texture_3d.h
© ClanLib.org