uicore::TextureCubeArray Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::TextureCubeArray Class Reference abstract
2D texture cube array object class.
#include <texture_cube_array.h>
Public Member Functions
virtual int array_size () const =0
Get the texture array size.
virtual int height () const =0
Get the texture height.
virtual void set_image (const GraphicContextPtr &context, int array_index, TextureCubeDirection cube_direction, const PixelBufferPtr &image, int level=0)=0
Upload image to texture.
virtual void set_subimage (const GraphicContextPtr &context, int array_index, TextureCubeDirection cube_direction, int x, int y, const PixelBufferPtr &image, const Rect &src_rect, int level=0)=0
Upload image to sub texture.
virtual void set_subimage (const GraphicContextPtr &context, int array_index, TextureCubeDirection cube_direction, const Point &point, const PixelBufferPtr &image, const Rect &src_rect, int level=0)
Size size () const
Get the texture size.
virtual int width () const =0
Get the texture width.
Public Member Functions inherited from uicore::Texture
virtual int base_level () const =0
Get the texture base level.
virtual CompareFunction compare_function () const =0
Get the texture compare function.
virtual TextureCompareMode compare_mode () const =0
Get the texture compare mode.
virtual void generate_mipmap ()=0
Generate mipmap textures.
virtual float lod_bias () const =0
Get the level of detail bias constant.
virtual TextureFilter mag_filter () const =0
Get the texture magnification filter.
virtual int max_level () const =0
Get the texture max level.
virtual float max_lod () const =0
Get the maximum level of detail.
virtual TextureFilter min_filter () const =0
Get the texture minification filter.
virtual float min_lod () const =0
Get the minimum level of detail.
virtual void set_base_level (int base_level)=0
Sets the texture base level texture parameter.
virtual void set_lod_bias (float lod_bias)=0
Sets the level of detail bias constant.
virtual void set_mag_filter (TextureFilter filter)=0
Set the magnification filter.
virtual void set_max_anisotropy (float max_anisotropy)=0
Set the maximum degree of anisotropy.
virtual void set_max_level (int max_level)=0
Sets the texture max level texture parameter.
virtual void set_max_lod (float max_lod)=0
Set the maximum level of detail texture parameter.
virtual void set_min_filter (TextureFilter filter)=0
Set the minification filter.
virtual void set_min_lod (float min_lod)=0
Set the minimum level of detail texture parameter.
virtual void set_texture_compare (TextureCompareMode mode, CompareFunction func)=0
Sets the texture compare mode and compare function texture parameters.
virtual TextureObject * texture_object ()=0
Static Public Member Functions
static std::shared_ptr< TextureCubeArray > create (const GraphicContextPtr &context, int width, int height, int array_size, TextureFormat texture_format=tf_rgba8, int levels=1)
Constructs a Texture.
static std::shared_ptr< TextureCubeArray > create (const GraphicContextPtr &context, const Size &size, int array_size, TextureFormat texture_format=tf_rgba8, int levels=1)
Static Public Member Functions inherited from uicore::Texture
static std::shared_ptr< Texture > create (const GraphicContextPtr &gc, PixelBufferSetPtr pixelbuffer_set)
Constructs a texture as described by a pixelbuffer set.
Detailed Description
2D texture cube array object class.
Member Function Documentation
virtual int uicore::TextureCubeArray::array_size () const pure virtual
Get the texture array size.
static std::shared_ptr<TextureCubeArray> uicore::TextureCubeArray::create (const GraphicContextPtr & context, int width, int height, int array_size, TextureFormat texture_format = tf_rgba8, int levels = 1) static
Constructs a Texture.
If levels is set to zero it will create a texture containing all mipmap levels
static std::shared_ptr<TextureCubeArray> uicore::TextureCubeArray::create (const GraphicContextPtr & context, const Size & size, int array_size, TextureFormat texture_format = tf_rgba8, int levels = 1) static
virtual int uicore::TextureCubeArray::height () const pure virtual
Get the texture height.
Referenced by size().
virtual void uicore::TextureCubeArray::set_image (const GraphicContextPtr & context, int array_index, TextureCubeDirection cube_direction, const PixelBufferPtr & image, int level = 0) pure virtual
Upload image to texture.
Parameters
context Graphic context to use for the request
array_index Index in the array
image Image to upload.
level Mipmap level-of-detail number.
virtual void uicore::TextureCubeArray::set_subimage (const GraphicContextPtr & context, int array_index, TextureCubeDirection cube_direction, int x, int y, const PixelBufferPtr & image, const Rect & src_rect, int level = 0) pure virtual
Upload image to sub texture.
Parameters
context Graphic context to use for the request
array_index Index in the array
image Image to upload.
level Mipmap level-of-detail number.
Referenced by set_subimage().
virtual void uicore::TextureCubeArray::set_subimage (const GraphicContextPtr & context, int array_index, TextureCubeDirection cube_direction, const Point & point, const PixelBufferPtr & image, const Rect & src_rect, int level = 0) inline virtual
References set_subimage(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
Size uicore::TextureCubeArray::size () const inline
Get the texture size.
References height(), and width().
virtual int uicore::TextureCubeArray::width () const pure virtual
Get the texture width.
Referenced by size().
The documentation for this class was generated from the following file:
texture_cube_array.h
© ClanLib.org