uicore::Color Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::Color Class Reference
Color description class.
#include <color.h>
Public Member Functions
Color ()
Constructs a color.
Color (const Colorf &)
Color (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha=255)
Constructs a color.
Color (const std::string &hexstr)
Constructs a color.
unsigned int get_abgr8 () const
Returns the color in ABGR8888 format.
unsigned char get_alpha () const
Returns the alpha color component, in the range 0-255.
float get_alpha_f () const
Returns the alpha color component, in the range 0-1.
unsigned int get_argb8 () const
Returns the color in ARGB8888 format.
unsigned int get_bgra8 () const
Returns the color in BGRA8888 format.
unsigned char get_blue () const
Returns the blue color component, in the range 0-255.
float get_blue_f () const
Returns the blue color component, in the range 0-1.
unsigned char get_green () const
Returns the green color component, in the range 0-255.
float get_green_f () const
Returns the green color component, in the range 0-1.
unsigned char get_red () const
Returns the red color component, in the range 0-255.
float get_red_f () const
Returns the red color component, in the range 0-1.
unsigned int get_rgba8 () const
Returns the color in RGBA8888 format.
bool operator!= (const Color &c) const
Color != Color operator (deep compare)
bool operator== (const Color &c) const
Color == Color operator (deep compare)
void set_alpha (unsigned char value)
Set alpha color component, in the range 0-255.
void set_alpha_f (float value)
Set alpha color component, in the range 0-1.
void set_argb8 (unsigned int color)
Set color based on argb color components.
void set_bgra8 (unsigned int color)
Set color based on rgba color components.
void set_blue (unsigned char value)
Set blue color component, in the range 0-255.
void set_blue_f (float value)
Set blue color component, in the range 0-1.
void set_color (unsigned char new_red, unsigned char new_green, unsigned char new_blue, unsigned char new_alpha=255)
Set color based on rgba color components in the range 0-255.
void set_colorf (float new_red, float new_green, float new_blue, float new_alpha=1.0f)
Set color based on rgba color components in the range 0-1.
void set_green (unsigned char value)
Set green color component, in the range 0-255.
void set_green_f (float value)
Set green color component, in the range 0-1.
void set_red (unsigned char value)
Set red color component, in the range 0-255.
void set_red_f (float value)
Set red color component, in the range 0-1.
void set_rgb8 (unsigned int color)
Set color based on rgb color components. Alpha is set to 255.
void set_rgba8 (unsigned int color)
Set color based on rgba color components.
Public Member Functions inherited from uicore::Vec4< Type >
Vec4 ()
Vec4 (const Type &scalar)
Vec4 (const Vec2< Type > &copy, const Type &p3, const Type &p4)
Vec4 (const Vec2< Type > &copy, const Vec2< Type > &copy34)
Vec4 (const Vec3< Type > &copy, const Type &p4)
Vec4 (const Type &p1, const Type &p2, const Type &p3, const Type &p4)
Vec4 (const Type &p1, const Type &p2, const Vec2< Type > &copy34)
Vec4 (const Type *array_xyzw)
Type angle3 (const Vec4< Type > &vector) const
Calculate the angle between this vector and an other vector (not taking into account the w ordinate).
Vec4< Type > & cross3 (const Vec4< Type > &vector)
Calculate the cross product between this vector and an other vector (not taking into account the w ordinate).
Type distance3 (const Vec4< Type > &vector) const
Calculate the distance between this vector and an other vector (not taking into account the w ordinate).
Type distance4 (const Vec4< Type > &vector) const
Calculate the distance between this vector and an other vector (taking into account the w ordinate).
Type dot3 (const Vec4< Type > &vector) const
Dot products this vector with an other vector (not taking into account the w ordinate).
Type dot4 (const Vec4< Type > &vector) const
Dot products this vector with an other vector (taking into account the w ordinate).
bool is_equal (const Vec4< Type > &other, Type epsilon) const
Returns true if equal within the bounds of an epsilon.
*Type length3 () const
Returns the length (magnitude) of this vector (not taking into account the w ordinate).
template<>
double length3 () const
template<>
float length3 () const
*Type length4 () const
Returns the length (magnitude) of this vector (taking into account the w ordinate).
template<>
double length4 () const
template<>
float length4 () const
Vec4< Type > & normalize3 ()
Normalizes this vector (not taking into account the w ordinate)
Vec4< Type > & normalize4 ()
Normalizes this vector (taking into account the w ordinate)
bool operator!= (const Vec4< Type > &vector) const
!= operator.
void operator*= (const Vec4< Type > &vector)
*= operator.
void operator*= (Type value)
*= operator.
void operator+= (const Vec4< Type > &vector)
+= operator.
void operator+= (Type value)
+= operator.
Vec4< Type > operator- () const
operator.
void operator-= (const Vec4< Type > &vector)
-= operator.
void operator-= (Type value)
-= operator.
void operator/= (const Vec4< Type > &vector)
/= operator.
void operator/= (Type value)
/= operator.
bool operator< (const Vec4< Type > &vector) const
< operator.
Vec4< Type > & operator= (const Vec4< Type > &vector)
= operator.
bool operator== (const Vec4< Type > &vector) const
== operator.
Vec4< Type > & rotate3 (Type angle, const Vec4< Type > &axis)
Rotate this vector around an axis. Same as glRotate[f|d](angle, a);.
Vec4< Type > & round ()
Rounds all components on this vector.
void set_xy (const Vec2< Type > &new_v)
void set_zw (const Vec2< Type > &new_v)
Static Public Attributes
static Color aliceblue
static Color antiquewhite
static Color aqua
static Color aquamarine
static Color azure
static Color beige
static Color bisque
static Color black
static Color blanchedalmond
static Color blue
static Color blueviolet
static Color brown
static Color burlywood
static Color cadetblue
static Color chartreuse
static Color chocolate
static Color coral
static Color cornflowerblue
static Color cornsilk
static Color crimson
static Color cyan
static Color darkblue
static Color darkcyan
static Color darkgoldenrod
static Color darkgray
static Color darkgreen
static Color darkgrey
static Color darkkhaki
static Color darkmagenta
static Color darkolivegreen
static Color darkorange
static Color darkorchid
static Color darkred
static Color darksalmon
static Color darkseagreen
static Color darkslateblue
static Color darkslategray
static Color darkslategrey
static Color darkturquoise
static Color darkviolet
static Color deeppink
static Color deepskyblue
static Color dimgray
static Color dimgrey
static Color dodgerblue
static Color firebrick
static Color floralwhite
static Color forestgreen
static Color fuchsia
static Color gainsboro
static Color ghostwhite
static Color gold
static Color goldenrod
static Color gray
static Color gray10
static Color gray20
static Color gray30
static Color gray40
static Color gray50
static Color gray60
static Color gray70
static Color gray80
static Color gray90
static Color green
static Color greenyellow
static Color grey
static Color honeydew
static Color hotpink
static Color indianred
static Color indigo
static Color ivory
static Color khaki
static Color lavender
static Color lavenderblush
static Color lawngreen
static Color lemonchiffon
static Color lightblue
static Color lightcoral
static Color lightcyan
static Color lightgoldenrodyellow
static Color lightgray
static Color lightgreen
static Color lightgrey
static Color lightpink
static Color lightsalmon
static Color lightseagreen
static Color lightskyblue
static Color lightslategray
static Color lightslategrey
static Color lightsteelblue
static Color lightyellow
static Color lime
static Color limegreen
static Color linen
static Color magenta
static Color maroon
static Color mediumaquamarine
static Color mediumblue
static Color mediumorchid
static Color mediumpurple
static Color mediumseagreen
static Color mediumslateblue
static Color mediumspringgreen
static Color mediumturquoise
static Color mediumvioletred
static Color midnightblue
static Color mintcream
static Color mistyrose
static Color moccasin
static Color navajowhite
static Color navy
static Color oldlace
static Color olive
static Color olivedrab
static Color orange
static Color orangered
static Color orchid
static Color palegoldenrod
static Color palegreen
static Color paleturquoise
static Color palevioletred
static Color papayawhip
static Color peachpuff
static Color peru
static Color pink
static Color plum
static Color powderblue
static Color purple
static Color red
static Color rosybrown
static Color royalblue
static Color saddlebrown
static Color salmon
static Color sandybrown
static Color seagreen
static Color seashell
static Color sienna
static Color silver
static Color skyblue
static Color slateblue
static Color slategray
static Color slategrey
static Color snow
static Color springgreen
static Color steelblue
static Color tan
static Color teal
static Color thistle
static Color tomato
static Color transparent
rgba(0, 0, 0, 0).
static Color turquoise
static Color violet
static Color wheat
static Color white
static Color whitesmoke
static Color yellow
static Color yellowgreen
Additional Inherited Members
Public Types inherited from uicore::Vec4< Type >
typedef Type datatype
Static Public Member Functions inherited from uicore::Vec4< Type >
static Vec4< Type > cross3 (const Vec4< Type > &vector1, const Vec4< Type > &vector2)
Calculate the cross product between two vectors (not taking into account the w ordinate).
static Type dot3 (const Vec4< Type > &vector1, const Vec4< Type > &vector2)
Dot products between two vectors (not taking into account the w ordinate).
static Type dot4 (const Vec4< Type > &vector1, const Vec4< Type > &vector2)
Dot products between two vectors (taking into account the w ordinate).
static bool is_equal (const Vec4< Type > &first, const Vec4< Type > &second, Type epsilon)
Returns true if equal within the bounds of an epsilon.
static Vec4< Type > normalize3 (const Vec4< Type > &vector)
Normalizes a vector (not taking into account the w ordinate)
static Vec4< Type > normalize4 (const Vec4< Type > &vector)
Normalizes a vector (taking into account the w ordinate)
static Vec4< Type > rotate3 (const Vec4< Type > &vector, Type angle, const Vec4< Type > &axis)
Rotate a vector around an axis. Same as glRotate[f|d](angle, a);.
static Vec4< Type > round (const Vec4< Type > &vector)
Rounds all components on a vector.
Public Attributes inherited from uicore::Vec4< Type >
Type w
Type x
Type y
Type z
Detailed Description
Color description class.
Constructor & Destructor Documentation
uicore::Color::Color () inline
Constructs a color.
uicore::Color::Color (const Colorf &) explicit
uicore::Color::Color (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha = 255) inline
Constructs a color.
Color components are specified in the range 0 to 255.
An alpha value of 0 means complete transparency, while 255 means completely opaque (solid).
Parameters
red Red color component.
green Green color component.
blue Blue color component.
alpha Alpha (transparency) color component.
uicore::Color::Color (const std::string & hexstr)
Constructs a color.
Color components are specified in the range 0 to 255.
An alpha value of 0 means complete transparency, while 255 means completely opaque (solid).
Parameters
hexstr The colors rgba components as a hexadecimal string of the format "#rrggbbaa", where the '#' and "aa" parts are optional.
Member Function Documentation
unsigned int uicore::Color::get_abgr8 () const inline
Returns the color in ABGR8888 format.
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
unsigned char uicore::Color::get_alpha () const inline
Returns the alpha color component, in the range 0-255.
References uicore::Vec4< Type >::w.
Referenced by uicore::Image::set_color().
float uicore::Color::get_alpha_f () const inline
Returns the alpha color component, in the range 0-1.
References uicore::Vec4< Type >::w.
unsigned int uicore::Color::get_argb8 () const inline
Returns the color in ARGB8888 format.
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
unsigned int uicore::Color::get_bgra8 () const inline
Returns the color in BGRA8888 format.
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
unsigned char uicore::Color::get_blue () const inline
Returns the blue color component, in the range 0-255.
References uicore::Vec4< Type >::z.
Referenced by uicore::Image::set_color().
float uicore::Color::get_blue_f () const inline
Returns the blue color component, in the range 0-1.
References uicore::Vec4< Type >::z.
unsigned char uicore::Color::get_green () const inline
Returns the green color component, in the range 0-255.
References uicore::Vec4< Type >::y.
Referenced by uicore::Image::set_color().
float uicore::Color::get_green_f () const inline
Returns the green color component, in the range 0-1.
References uicore::Vec4< Type >::y.
unsigned char uicore::Color::get_red () const inline
Returns the red color component, in the range 0-255.
References uicore::Vec4< Type >::x.
Referenced by uicore::Image::set_color().
float uicore::Color::get_red_f () const inline
Returns the red color component, in the range 0-1.
References uicore::Vec4< Type >::x.
unsigned int uicore::Color::get_rgba8 () const inline
Returns the color in RGBA8888 format.
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
bool uicore::Color::operator!= (const Color & c) const inline
Color != Color operator (deep compare)
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
bool uicore::Color::operator== (const Color & c) const inline
Color == Color operator (deep compare)
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
void uicore::Color::set_alpha (unsigned char value) inline
Set alpha color component, in the range 0-255.
References uicore::Vec4< Type >::w.
void uicore::Color::set_alpha_f (float value) inline
Set alpha color component, in the range 0-1.
References uicore::f, and uicore::Vec4< Type >::w.
void uicore::Color::set_argb8 (unsigned int color)
Set color based on argb color components.
void uicore::Color::set_bgra8 (unsigned int color)
Set color based on rgba color components.
void uicore::Color::set_blue (unsigned char value) inline
Set blue color component, in the range 0-255.
References uicore::Vec4< Type >::z.
void uicore::Color::set_blue_f (float value) inline
Set blue color component, in the range 0-1.
References uicore::f, and uicore::Vec4< Type >::z.
void uicore::Color::set_color (unsigned char new_red, unsigned char new_green, unsigned char new_blue, unsigned char new_alpha = 255) inline
Set color based on rgba color components in the range 0-255.
References uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
void uicore::Color::set_colorf (float new_red, float new_green, float new_blue, float new_alpha = 1.0f) inline
Set color based on rgba color components in the range 0-1.
References uicore::f, uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
void uicore::Color::set_green (unsigned char value) inline
Set green color component, in the range 0-255.
References uicore::Vec4< Type >::y.
void uicore::Color::set_green_f (float value) inline
Set green color component, in the range 0-1.
References uicore::f, and uicore::Vec4< Type >::y.
void uicore::Color::set_red (unsigned char value) inline
Set red color component, in the range 0-255.
References uicore::Vec4< Type >::x.
void uicore::Color::set_red_f (float value) inline
Set red color component, in the range 0-1.
References uicore::f, and uicore::Vec4< Type >::x.
void uicore::Color::set_rgb8 (unsigned int color)
Set color based on rgb color components. Alpha is set to 255.
void uicore::Color::set_rgba8 (unsigned int color)
Set color based on rgba color components.
Member Data Documentation
Color uicore::Color::aliceblue static
rgb(240, 248, 255).
Color uicore::Color::antiquewhite static
rgb(250, 235, 215).
Color uicore::Color::aqua static
rgb(0, 255, 255).
Color uicore::Color::aquamarine static
rgb(127, 255, 212).
Color uicore::Color::azure static
rgb(240, 255, 255).
Color uicore::Color::beige static
rgb(245, 245, 220).
Color uicore::Color::bisque static
rgb(255, 228, 196).
Color uicore::Color::black static
rgb(0, 0, 0).
Color uicore::Color::blanchedalmond static
rgb(255, 235, 205).
Color uicore::Color::blue static
rgb(0, 0, 255).
Color uicore::Color::blueviolet static
rgb(138, 43, 226).
Color uicore::Color::brown static
rgb(165, 42, 42).
Color uicore::Color::burlywood static
rgb(222, 184, 135).
Color uicore::Color::cadetblue static
rgb(95, 158, 160).
Color uicore::Color::chartreuse static
rgb(127, 255, 0).
Color uicore::Color::chocolate static
rgb(210, 105, 30).
Color uicore::Color::coral static
rgb(255, 127, 80).
Color uicore::Color::cornflowerblue static
rgb(100, 149, 237).
Color uicore::Color::cornsilk static
rgb(255, 248, 220).
Color uicore::Color::crimson static
rgb(220, 20, 60).
Color uicore::Color::cyan static
rgb(0, 255, 255).
Color uicore::Color::darkblue static
rgb(0, 0, 139).
Color uicore::Color::darkcyan static
rgb(0, 139, 139).
Color uicore::Color::darkgoldenrod static
rgb(184, 134, 11).
Color uicore::Color::darkgray static
rgb(169, 169, 169).
Color uicore::Color::darkgreen static
rgb(0, 100, 0).
Color uicore::Color::darkgrey static
rgb(169, 169, 169).
Color uicore::Color::darkkhaki static
rgb(189, 183, 107).
Color uicore::Color::darkmagenta static
rgb(139, 0, 139).
Color uicore::Color::darkolivegreen static
rgb(85, 107, 47).
Color uicore::Color::darkorange static
rgb(255, 140, 0).
Color uicore::Color::darkorchid static
rgb(153, 50, 204).
Color uicore::Color::darkred static
rgb(139, 0, 0).
Color uicore::Color::darksalmon static
rgb(233, 150, 122).
Color uicore::Color::darkseagreen static
rgb(143, 188, 143).
Color uicore::Color::darkslateblue static
rgb(72, 61, 139).
Color uicore::Color::darkslategray static
rgb(47, 79, 79).
Color uicore::Color::darkslategrey static
rgb(47, 79, 79).
Color uicore::Color::darkturquoise static
rgb(0, 206, 209).
Color uicore::Color::darkviolet static
rgb(148, 0, 211).
Color uicore::Color::deeppink static
rgb(255, 20, 147).
Color uicore::Color::deepskyblue static
rgb(0, 191, 255).
Color uicore::Color::dimgray static
rgb(105, 105, 105).
Color uicore::Color::dimgrey static
rgb(105, 105, 105).
Color uicore::Color::dodgerblue static
rgb(30, 144, 255).
Color uicore::Color::firebrick static
rgb(178, 34, 34).
Color uicore::Color::floralwhite static
rgb(255, 250, 240).
Color uicore::Color::forestgreen static
rgb(34, 139, 34).
Color uicore::Color::fuchsia static
rgb(255, 0, 255).
Color uicore::Color::gainsboro static
rgb(220, 220, 220).
Color uicore::Color::ghostwhite static
rgb(248, 248, 255).
Color uicore::Color::gold static
rgb(255, 215, 0).
Color uicore::Color::goldenrod static
rgb(218, 165, 32).
Color uicore::Color::gray static
rgb(128, 128, 128).
Color uicore::Color::gray10 static
Color uicore::Color::gray20 static
Color uicore::Color::gray30 static
Color uicore::Color::gray40 static
Color uicore::Color::gray50 static
Color uicore::Color::gray60 static
Color uicore::Color::gray70 static
Color uicore::Color::gray80 static
Color uicore::Color::gray90 static
Color uicore::Color::green static
rgb(0, 128, 0).
Color uicore::Color::greenyellow static
rgb(173, 255, 47).
Color uicore::Color::grey static
rgb(128, 128, 128).
Color uicore::Color::honeydew static
rgb(240, 255, 240).
Color uicore::Color::hotpink static
rgb(255, 105, 180).
Color uicore::Color::indianred static
rgb(205, 92, 92).
Color uicore::Color::indigo static
rgb(75, 0, 130).
Color uicore::Color::ivory static
rgb(255, 255, 240).
Color uicore::Color::khaki static
rgb(240, 230, 140).
Color uicore::Color::lavender static
rgb(230, 230, 250).
Color uicore::Color::lavenderblush static
rgb(255, 240, 245).
Color uicore::Color::lawngreen static
rgb(124, 252, 0).
Color uicore::Color::lemonchiffon static
rgb(255, 250, 205).
Color uicore::Color::lightblue static
rgb(173, 216, 230).
Color uicore::Color::lightcoral static
rgb(240, 128, 128).
Color uicore::Color::lightcyan static
rgb(224, 255, 255).
Color uicore::Color::lightgoldenrodyellow static
rgb(250, 250, 210).
Color uicore::Color::lightgray static
rgb(211, 211, 211).
Color uicore::Color::lightgreen static
rgb(144, 238, 144).
Color uicore::Color::lightgrey static
rgb(211, 211, 211).
Color uicore::Color::lightpink static
rgb(255, 182, 193).
Color uicore::Color::lightsalmon static
rgb(255, 160, 122).
Color uicore::Color::lightseagreen static
rgb(32, 178, 170).
Color uicore::Color::lightskyblue static
rgb(135, 206, 250).
Color uicore::Color::lightslategray static
rgb(119, 136, 153).
Color uicore::Color::lightslategrey static
rgb(119, 136, 153).
Color uicore::Color::lightsteelblue static
rgb(176, 196, 222).
Color uicore::Color::lightyellow static
rgb(255, 255, 224).
Color uicore::Color::lime static
rgb(0, 255, 0).
Color uicore::Color::limegreen static
rgb(50, 205, 50).
Color uicore::Color::linen static
rgb(250, 240, 230).
Color uicore::Color::magenta static
rgb(255, 0, 255).
Color uicore::Color::maroon static
rgb(128, 0, 0).
Color uicore::Color::mediumaquamarine static
rgb(102, 205, 170).
Color uicore::Color::mediumblue static
rgb(0, 0, 205).
Color uicore::Color::mediumorchid static
rgb(186, 85, 211).
Color uicore::Color::mediumpurple static
rgb(147, 112, 219).
Color uicore::Color::mediumseagreen static
rgb(60, 179, 113).
Color uicore::Color::mediumslateblue static
rgb(123, 104, 238).
Color uicore::Color::mediumspringgreen static
rgb(0, 250, 154).
Color uicore::Color::mediumturquoise static
rgb(72, 209, 204).
Color uicore::Color::mediumvioletred static
rgb(199, 21, 133).
Color uicore::Color::midnightblue static
rgb(25, 25, 112).
Color uicore::Color::mintcream static
rgb(245, 255, 250).
Color uicore::Color::mistyrose static
rgb(255, 228, 225).
Color uicore::Color::moccasin static
rgb(255, 228, 181).
Color uicore::Color::navajowhite static
rgb(255, 222, 173).
Color uicore::Color::navy static
rgb(0, 0, 128).
Color uicore::Color::oldlace static
rgb(253, 245, 230).
Color uicore::Color::olive static
rgb(128, 128, 0).
Color uicore::Color::olivedrab static
rgb(107, 142, 35).
Color uicore::Color::orange static
rgb(255, 165, 0).
Color uicore::Color::orangered static
rgb(255, 69, 0).
Color uicore::Color::orchid static
rgb(218, 112, 214).
Color uicore::Color::palegoldenrod static
rgb(238, 232, 170).
Color uicore::Color::palegreen static
rgb(152, 251, 152).
Color uicore::Color::paleturquoise static
rgb(175, 238, 238).
Color uicore::Color::palevioletred static
rgb(219, 112, 147).
Color uicore::Color::papayawhip static
rgb(255, 239, 213).
Color uicore::Color::peachpuff static
rgb(255, 218, 185).
Color uicore::Color::peru static
rgb(205, 133, 63).
Color uicore::Color::pink static
rgb(255, 192, 203).
Color uicore::Color::plum static
rgb(221, 160, 221).
Color uicore::Color::powderblue static
rgb(176, 224, 230).
Color uicore::Color::purple static
rgb(128, 0, 128).
Color uicore::Color::red static
rgb(255, 0, 0).
Color uicore::Color::rosybrown static
rgb(188, 143, 143).
Color uicore::Color::royalblue static
rgb(65, 105, 225).
Color uicore::Color::saddlebrown static
rgb(139, 69, 19).
Color uicore::Color::salmon static
rgb(250, 128, 114).
Color uicore::Color::sandybrown static
rgb(244, 164, 96).
Color uicore::Color::seagreen static
rgb(46, 139, 87).
Color uicore::Color::seashell static
rgb(255, 245, 238).
Color uicore::Color::sienna static
rgb(160, 82, 45).
Color uicore::Color::silver static
rgb(192, 192, 192).
Color uicore::Color::skyblue static
rgb(135, 206, 235).
Color uicore::Color::slateblue static
rgb(106, 90, 205).
Color uicore::Color::slategray static
rgb(112, 128, 144).
Color uicore::Color::slategrey static
rgb(112, 128, 144).
Color uicore::Color::snow static
rgb(255, 250, 250).
Color uicore::Color::springgreen static
rgb(0, 255, 127).
Color uicore::Color::steelblue static
rgb(70, 130, 180).
Color uicore::Color::tan static
rgb(210, 180, 140).
Color uicore::Color::teal static
rgb(0, 128, 128).
Color uicore::Color::thistle static
rgb(216, 191, 216).
Color uicore::Color::tomato static
rgb(255, 99, 71).
Color uicore::Color::transparent static
rgba(0, 0, 0, 0).
Color uicore::Color::turquoise static
rgb(64, 224, 208).
Color uicore::Color::violet static
rgb(238, 130, 238).
Color uicore::Color::wheat static
rgb(245, 222, 179).
Color uicore::Color::white static
rgb(255, 255, 255).
Color uicore::Color::whitesmoke static
rgb(245, 245, 245).
Color uicore::Color::yellow static
rgb(255, 255, 0).
Color uicore::Color::yellowgreen static
rgb(154, 205, 50).
The documentation for this class was generated from the following file:
color.h
© ClanLib.org