uicore::IODevice Class Reference - UICore SDK
uicore::IODevice Class Reference abstract
#include <iodevice.h>
Public Member Functions
virtual ~IODevice ()
virtual void close ()
bool is_big_endian_mode () const
long long position () const
void read (void *data, int size)
double read_double ()
float read_float ()
int16_t read_int16 ()
int32_t read_int32 ()
int8_t read_int8 ()
template<typename T >
T read_type ()
uint16_t read_uint16 ()
uint32_t read_uint32 ()
uint8_t read_uint8 ()
virtual long long seek (long long position)=0
virtual long long seek_from_current (long long offset)=0
virtual long long seek_from_end (long long offset)=0
void set_big_endian_mode (bool value=true)
virtual long long size () const =0
virtual int try_read (void *data, int size)=0
virtual void write (const void *data, int size)=0
void write_double (double v)
void write_float (float v)
void write_int16 (int16_t v)
void write_int32 (int32_t v)
void write_int64 (int64_t v)
void write_int8 (int8_t v)
template<typename T >
void write_type (T v)
void write_uint16 (uint16_t v)
void write_uint32 (uint32_t v)
void write_uint64 (uint64_t v)
void write_uint8 (uint8_t v)
Constructor & Destructor Documentation
virtual uicore::IODevice::~IODevice () inline virtual
Member Function Documentation
virtual void uicore::IODevice::close () inline virtual
bool uicore::IODevice::is_big_endian_mode () const inline
long long uicore::IODevice::position () const inline
References seek_from_current().
void uicore::IODevice::read (void * data, int size) inline
References try_read().
Referenced by read_type().
double uicore::IODevice::read_double () inline
float uicore::IODevice::read_float () inline
int16_t uicore::IODevice::read_int16 () inline
int32_t uicore::IODevice::read_int32 () inline
int8_t uicore::IODevice::read_int8 () inline
template<typename T > T uicore::IODevice::read_type () inline
References read(), uicore::Endian::swap(), and uicore::v.
uint16_t uicore::IODevice::read_uint16 () inline
uint32_t uicore::IODevice::read_uint32 () inline
uint8_t uicore::IODevice::read_uint8 () inline
virtual long long uicore::IODevice::seek (long long position) pure virtual
virtual long long uicore::IODevice::seek_from_current (long long offset) pure virtual
Referenced by position().
virtual long long uicore::IODevice::seek_from_end (long long offset) pure virtual
void uicore::IODevice::set_big_endian_mode (bool value = true) inline
virtual long long uicore::IODevice::size () const pure virtual
virtual int uicore::IODevice::try_read (void * data, int size) pure virtual
Referenced by read().
virtual void uicore::IODevice::write (const void * data, int size) pure virtual
Referenced by write_type().
void uicore::IODevice::write_double (double v) inline
References write_type().
void uicore::IODevice::write_float (float v) inline
References write_type().
void uicore::IODevice::write_int16 (int16_t v) inline
References write_type().
void uicore::IODevice::write_int32 (int32_t v) inline
References write_type().
void uicore::IODevice::write_int64 (int64_t v) inline
References write_type().
void uicore::IODevice::write_int8 (int8_t v) inline
References write_type().
template<typename T > void uicore::IODevice::write_type (T v) inline
References uicore::Endian::swap(), and write().
Referenced by write_double(), write_float(), write_int16(), write_int32(), write_int64(), write_int8(), write_uint16(), write_uint32(), write_uint64(), and write_uint8().
void uicore::IODevice::write_uint16 (uint16_t v) inline
References write_type().
void uicore::IODevice::write_uint32 (uint32_t v) inline
References write_type().
void uicore::IODevice::write_uint64 (uint64_t v) inline
References write_type().
void uicore::IODevice::write_uint8 (uint8_t v) inline
References write_type().
The documentation for this class was generated from the following file:
iodevice.h