uicore::StyleGetValue Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::StyleGetValue Class Reference
Style value returned by style classes.
#include <style_get_value.h>
Public Member Functions
Colorf color () const
Value color.
StyleDimension dimension () const
Dimension used by value.
bool is_angle () const
Check if value is an angle.
bool is_color () const
Check if value is a color.
bool is_frequency () const
Check if value is a frequency.
bool is_keyword () const
Check if value is a keyword.
bool is_keyword (const char *keyword) const
bool is_keyword (const std::string &keyword) const
bool is_length () const
Check if value is a length.
bool is_number () const
Check if value is a number.
bool is_percentage () const
Check if value is a percentage.
bool is_resolution () const
Check if value is a resolution.
bool is_string () const
Check if value is a string.
bool is_time () const
Check if value is a time.
bool is_undefined () const
Check if value is undefined.
bool is_url () const
Check if value is an url.
float number () const
Value number.
const char * text () const
Text when the type is a text string.
StyleValueType type () const
Variant type.
Static Public Member Functions
static StyleGetValue from_angle (float angle, StyleDimension dimension=StyleDimension::rad)
Create style value from an angle.
static StyleGetValue from_color (const Colorf &color)
Create style value from a color.
static StyleGetValue from_frequency (float freq, StyleDimension dimension=StyleDimension::hz)
Create style value from a frequency.
static StyleGetValue from_keyword (const char *keyword)
Create style value from a keyword.
static StyleGetValue from_length (float length, StyleDimension dimension=StyleDimension::px)
Create style value from a length.
static StyleGetValue from_number (float number)
Create style value from a number.
static StyleGetValue from_percentage (float percentage)
Create style value from a percentage.
static StyleGetValue from_resolution (float resolution, StyleDimension dimension=StyleDimension::dppx)
Create style value from a resolution.
static StyleGetValue from_string (const char *text)
Create style value from a string.
static StyleGetValue from_time (float t, StyleDimension dimension=StyleDimension::s)
Create style value from a time.
static StyleGetValue from_url (const char *url)
Create style value from an url.
Detailed Description
Style value returned by style classes.
Member Function Documentation
Colorf uicore::StyleGetValue::color () const inline
Value color.
References uicore::color.
StyleDimension uicore::StyleGetValue::dimension () const inline
Dimension used by value.
References uicore::angle, uicore::frequency, uicore::length, uicore::px, uicore::resolution, and uicore::time.
Referenced by from_angle(), from_frequency(), from_length(), from_resolution(), and from_time().
static StyleGetValue uicore::StyleGetValue::from_angle (float angle, StyleDimension dimension = StyleDimension::rad) inline static
Create style value from an angle.
References uicore::angle, dimension(), float_value, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_color (const Colorf & color) inline static
Create style value from a color.
References uicore::color, color, uicore::v, uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
static StyleGetValue uicore::StyleGetValue::from_frequency (float freq, StyleDimension dimension = StyleDimension::hz) inline static
Create style value from a frequency.
References dimension(), float_value, uicore::frequency, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_keyword (const char * keyword) inline static
Create style value from a keyword.
References uicore::keyword, text, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_length (float length, StyleDimension dimension = StyleDimension::px) inline static
Create style value from a length.
References dimension(), float_value, uicore::length, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_number (float number) inline static
Create style value from a number.
References float_value, uicore::number, number(), and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_percentage (float percentage) inline static
Create style value from a percentage.
References float_value, uicore::percentage, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_resolution (float resolution, StyleDimension dimension = StyleDimension::dppx) inline static
Create style value from a resolution.
References dimension(), float_value, uicore::resolution, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_string (const char * text) inline static
Create style value from a string.
References uicore::string, text, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_time (float t, StyleDimension dimension = StyleDimension::s) inline static
Create style value from a time.
References dimension(), float_value, uicore::t, uicore::time, and uicore::v.
static StyleGetValue uicore::StyleGetValue::from_url (const char * url) inline static
Create style value from an url.
References text, uicore::url, and uicore::v.
bool uicore::StyleGetValue::is_angle () const inline
Check if value is an angle.
References uicore::angle.
bool uicore::StyleGetValue::is_color () const inline
Check if value is a color.
References uicore::color.
bool uicore::StyleGetValue::is_frequency () const inline
Check if value is a frequency.
References uicore::frequency.
bool uicore::StyleGetValue::is_keyword () const inline
Check if value is a keyword.
References uicore::keyword.
bool uicore::StyleGetValue::is_keyword (const char * keyword) const inline
References is_keyword().
Referenced by is_keyword().
bool uicore::StyleGetValue::is_keyword (const std::string & keyword) const inline
References is_keyword(), and uicore::keyword.
Referenced by is_keyword().
bool uicore::StyleGetValue::is_length () const inline
Check if value is a length.
References uicore::length.
bool uicore::StyleGetValue::is_number () const inline
Check if value is a number.
References uicore::number.
bool uicore::StyleGetValue::is_percentage () const inline
Check if value is a percentage.
References uicore::percentage.
bool uicore::StyleGetValue::is_resolution () const inline
Check if value is a resolution.
References uicore::resolution.
bool uicore::StyleGetValue::is_string () const inline
Check if value is a string.
References uicore::string.
bool uicore::StyleGetValue::is_time () const inline
Check if value is a time.
References uicore::time.
bool uicore::StyleGetValue::is_undefined () const inline
Check if value is undefined.
References uicore::undefined.
bool uicore::StyleGetValue::is_url () const inline
Check if value is an url.
References uicore::url.
float uicore::StyleGetValue::number () const inline
Value number.
References uicore::angle, uicore::frequency, uicore::length, uicore::number, uicore::percentage, uicore::resolution, and uicore::time.
Referenced by from_number().
const char* uicore::StyleGetValue::text () const inline
Text when the type is a text string.
References uicore::keyword, uicore::string, and uicore::url.
Referenced by from_string().
StyleValueType uicore::StyleGetValue::type () const inline
Variant type.
Member Data Documentation
float uicore::StyleGetValue::color[4]
Referenced by from_color().
StyleDimension uicore::StyleGetValue::dimension
struct { ... } uicore::StyleGetValue::float_value
Referenced by from_angle(), from_frequency(), from_length(), from_number(), from_percentage(), from_resolution(), and from_time().
float uicore::StyleGetValue::number
const char* uicore::StyleGetValue::text
Referenced by from_keyword(), from_string(), and from_url().
The documentation for this class was generated from the following file:
style_get_value.h
© ClanLib.org