uicore::JsonValue Class Reference - UICore SDK
uicore::JsonValue Class Reference
#include <json_value.h>
Public Member Functions
JsonValue & at (size_t index)
const JsonValue & at (size_t index) const
void clear ()
void erase (size_t offset, size_t length)
bool is_array () const
bool is_boolean () const
bool is_null () const
bool is_number () const
bool is_object () const
bool is_undefined () const
std::vector< JsonValue > & items ()
const std::vector< JsonValue > & items () const
JsonValue & operator[] (const std::string &name)
JsonValue & operator[] (const char *name)
const JsonValue & operator[] (const std::string &name) const
const JsonValue & operator[] (const char *name) const
JsonValue & operator[] (size_t index)
const JsonValue & operator[] (size_t index) const
const JsonValue & prop (const std::string &name) const
const JsonValue & prop (const char *name) const
JsonValue & prop (const std::string &name)
JsonValue & prop (const char *name)
std::map< std::string, JsonValue > & properties ()
const std::map< std::string, JsonValue > & properties () const
void remove (const std::string &name)
void remove (const char *name)
void set_array ()
void set_boolean (bool v)
void set_null ()
void set_number (double v)
void set_number (float v)
void set_number (int v)
void set_number (unsigned int v)
void set_number (short v)
void set_number (unsigned short v)
void set_number (char v)
void set_number (unsigned char v)
void set_object ()
void set_string (const std::string &v)
void set_string (const char *v)
void set_undefined ()
size_t size () const
bool to_boolean () const
char to_char () const
double to_double () const
float to_float () const
int to_int () const
std::string to_json () const
double to_number () const
short to_short () const
const std::string & to_string () const
unsigned char to_uchar () const
unsigned int to_uint () const
unsigned short to_ushort () const
JsonType type () const
Static Public Member Functions
static JsonValue array ()
static JsonValue boolean (bool value)
static JsonValue null ()
static JsonValue number (double value)
static JsonValue number (float value)
static JsonValue number (int value)
static JsonValue number (unsigned int value)
static JsonValue number (short value)
static JsonValue number (unsigned short value)
static JsonValue number (char value)
static JsonValue number (unsigned char value)
static JsonValue object ()
static JsonValue parse (const std::string &json)
static JsonValue string (const std::string &value)
static JsonValue undefined ()
Member Function Documentation
static JsonValue uicore::JsonValue::array () inline static
References uicore::array, and uicore::v.
Referenced by set_array().
JsonValue& uicore::JsonValue::at (size_t index) inline
Referenced by operator[]().
const JsonValue& uicore::JsonValue::at (size_t index) const inline
static JsonValue uicore::JsonValue::boolean (bool value) inline static
References uicore::boolean, and uicore::v.
Referenced by set_boolean().
void uicore::JsonValue::clear () inline
void uicore::JsonValue::erase (size_t offset, size_t length) inline
References uicore::length.
bool uicore::JsonValue::is_array () const inline
References uicore::array, and type().
bool uicore::JsonValue::is_boolean () const inline
References uicore::boolean, and type().
bool uicore::JsonValue::is_null () const inline
References uicore::null, and type().
bool uicore::JsonValue::is_number () const inline
References uicore::number, and type().
bool uicore::JsonValue::is_object () const inline
References uicore::object, and type().
bool uicore::JsonValue::is_undefined () const inline
References type(), and uicore::undefined.
std::vector<JsonValue>& uicore::JsonValue::items () inline
const std::vector<JsonValue>& uicore::JsonValue::items () const inline
static JsonValue uicore::JsonValue::null () inline static
References uicore::null, and uicore::v.
Referenced by set_null().
static JsonValue uicore::JsonValue::number (double value) inline static
References uicore::number, and uicore::v.
Referenced by number(), and set_number().
static JsonValue uicore::JsonValue::number (float value) inline static
References number().
static JsonValue uicore::JsonValue::number (int value) inline static
References number().
static JsonValue uicore::JsonValue::number (unsigned int value) inline static
References number().
static JsonValue uicore::JsonValue::number (short value) inline static
References number().
static JsonValue uicore::JsonValue::number (unsigned short value) inline static
References number().
static JsonValue uicore::JsonValue::number (char value) inline static
References number().
static JsonValue uicore::JsonValue::number (unsigned char value) inline static
References number().
static JsonValue uicore::JsonValue::object () inline static
References uicore::object, and uicore::v.
Referenced by set_object().
JsonValue& uicore::JsonValue::operator[] (const std::string & name) inline
References prop().
JsonValue& uicore::JsonValue::operator[] (const char * name) inline
References prop().
const JsonValue& uicore::JsonValue::operator[] (const std::string & name) const inline
References prop().
const JsonValue& uicore::JsonValue::operator[] (const char * name) const inline
References prop().
JsonValue& uicore::JsonValue::operator[] (size_t index) inline
References at().
const JsonValue& uicore::JsonValue::operator[] (size_t index) const inline
References at().
static JsonValue uicore::JsonValue::parse (const std::string & json) static
const JsonValue& uicore::JsonValue::prop (const std::string & name) const inline
Referenced by operator[]().
const JsonValue& uicore::JsonValue::prop (const char * name) const inline
JsonValue& uicore::JsonValue::prop (const std::string & name) inline
JsonValue& uicore::JsonValue::prop (const char * name) inline
std::map<std::string, JsonValue>& uicore::JsonValue::properties () inline
const std::map<std::string, JsonValue>& uicore::JsonValue::properties () const inline
void uicore::JsonValue::remove (const std::string & name) inline
void uicore::JsonValue::remove (const char * name) inline
void uicore::JsonValue::set_array () inline
References array().
void uicore::JsonValue::set_boolean (bool v) inline
References boolean().
void uicore::JsonValue::set_null () inline
References null().
void uicore::JsonValue::set_number (double v) inline
References number().
void uicore::JsonValue::set_number (float v) inline
References number().
void uicore::JsonValue::set_number (int v) inline
References number().
void uicore::JsonValue::set_number (unsigned int v) inline
References number().
void uicore::JsonValue::set_number (short v) inline
References number().
void uicore::JsonValue::set_number (unsigned short v) inline
References number().
void uicore::JsonValue::set_number (char v) inline
References number().
void uicore::JsonValue::set_number (unsigned char v) inline
References number().
void uicore::JsonValue::set_object () inline
References object().
void uicore::JsonValue::set_string (const std::string & v) inline
References string().
void uicore::JsonValue::set_string (const char * v) inline
References string().
void uicore::JsonValue::set_undefined () inline
References undefined().
size_t uicore::JsonValue::size () const inline
static JsonValue uicore::JsonValue::string (const std::string & value) inline static
References uicore::string, and uicore::v.
Referenced by set_string().
bool uicore::JsonValue::to_boolean () const inline
char uicore::JsonValue::to_char () const inline
References to_number().
double uicore::JsonValue::to_double () const inline
References to_number().
float uicore::JsonValue::to_float () const inline
References to_number().
int uicore::JsonValue::to_int () const inline
References to_number().
std::string uicore::JsonValue::to_json () const
double uicore::JsonValue::to_number () const inline
Referenced by to_char(), to_double(), to_float(), to_int(), to_short(), to_uchar(), to_uint(), and to_ushort().
short uicore::JsonValue::to_short () const inline
References to_number().
const std::string& uicore::JsonValue::to_string () const inline
unsigned char uicore::JsonValue::to_uchar () const inline
References to_number().
unsigned int uicore::JsonValue::to_uint () const inline
References to_number().
unsigned short uicore::JsonValue::to_ushort () const inline
References to_number().
JsonType uicore::JsonValue::type () const inline
Referenced by is_array(), is_boolean(), is_null(), is_number(), is_object(), and is_undefined().
static JsonValue uicore::JsonValue::undefined () inline static
References uicore::undefined, and uicore::v.
Referenced by set_undefined().
The documentation for this class was generated from the following file:
json_value.h