uicore::XmlNode Class Reference - UICore SDK
uicore::XmlNode Class Reference abstract
Tree node in a XML document.
#include <xml_node.h>
Public Member Functions
virtual XmlNodePtr add_attribute (const XmlNodePtr &new_attribute)=0
virtual XmlNodePtr append_child (const XmlNodePtr &new_child)=0
virtual XmlString attribute (const XmlString &name, const XmlString &default_value=XmlString()) const =0
virtual XmlNodePtr attribute_node (const XmlString &name) const =0
virtual XmlNodePtr attribute_node (const XmlString &namespace_uri, const XmlString &local_name) const =0
virtual XmlString attribute_ns (const XmlString &namespace_uri, const XmlString &local_name, const XmlString &default_value=XmlString()) const =0
virtual XmlNodePtr clone (bool deep) const =0
Returns a duplicate of this node, i.e., serves as a generic copy constructor for nodes. The duplicate node has no parent.
virtual XmlString find_namespace_uri (const XmlString &qualified_name) const =0
Searches the node tree upwards for the namespace URI of the given qualified name.
virtual XmlString find_prefix (const XmlString &namespace_uri) const =0
Searches the node tree upwards for the prefix name for the namespace URI.
virtual XmlNodePtr first_attribute () const =0
virtual XmlNodePtr first_child () const =0
virtual bool has_attribute (const XmlString &name) const =0
virtual bool has_attribute (const XmlString &namespace_uri, const XmlString &local_name) const =0
virtual bool has_attributes () const =0
bool has_child_nodes () const
virtual XmlNodePtr insert_before (const XmlNodePtr &new_child, const XmlNodePtr &ref_child)=0
bool is_attr () const
bool is_cdata_section () const
bool is_comment () const
bool is_document () const
bool is_document_fragment () const
bool is_element () const
bool is_text () const
virtual XmlNodePtr last_child () const =0
virtual XmlString local_name () const =0
virtual XmlString name () const =0
virtual XmlNodePtr named_item (const XmlString &name) const =0
Returns the first child node with the specified node name. Returns null if no child is found.
virtual XmlNodePtr named_item (const XmlString &namespace_uri, const XmlString &local_name) const =0
virtual XmlString namespace_uri () const =0
virtual XmlNodePtr next_sibling () const =0
virtual XmlDocumentPtr owner_document () const =0
virtual XmlNodePtr parent () const =0
virtual XmlString prefix () const =0
virtual XmlNodePtr previous_sibling () const =0
virtual void remove_attribute (const XmlString &name)=0
virtual void remove_attribute (const XmlString &namespace_uri, const XmlString &local_name)=0
virtual XmlNodePtr remove_attribute (const XmlNodePtr &old_attribute)=0
virtual XmlNodePtr remove_child (const XmlNodePtr &old_child)=0
virtual XmlNodePtr replace_child (const XmlNodePtr &new_child, const XmlNodePtr &old_child)=0
virtual void set_attribute (const XmlString &name, const XmlString &value)=0
virtual void set_attribute (const XmlString &namespace_uri, const XmlString &qualified_name, const XmlString &value)=0
virtual void set_prefix (const XmlString &prefix)=0
virtual void set_text (const XmlString &value)=0
virtual XmlString text () const =0
virtual XmlNodeType type () const =0
Detailed Description
Tree node in a XML document.
Member Function Documentation
virtual XmlNodePtr uicore::XmlNode::add_attribute (const XmlNodePtr & new_attribute) pure virtual
virtual XmlNodePtr uicore::XmlNode::append_child (const XmlNodePtr & new_child) pure virtual
virtual XmlString uicore::XmlNode::attribute (const XmlString & name, const XmlString & default_value = XmlString()) const pure virtual
virtual XmlNodePtr uicore::XmlNode::attribute_node (const XmlString & name) const pure virtual
virtual XmlNodePtr uicore::XmlNode::attribute_node (const XmlString & namespace_uri, const XmlString & local_name) const pure virtual
virtual XmlString uicore::XmlNode::attribute_ns (const XmlString & namespace_uri, const XmlString & local_name, const XmlString & default_value = XmlString()) const pure virtual
virtual XmlNodePtr uicore::XmlNode::clone (bool deep) const pure virtual
Returns a duplicate of this node, i.e., serves as a generic copy constructor for nodes. The duplicate node has no parent.
Parameters
deep If true, recursively clone the subtree under the specified node; if false, clone only the node itself (and its attributes, if it is an Element).
virtual XmlString uicore::XmlNode::find_namespace_uri (const XmlString & qualified_name) const pure virtual
Searches the node tree upwards for the namespace URI of the given qualified name.
virtual XmlString uicore::XmlNode::find_prefix (const XmlString & namespace_uri) const pure virtual
Searches the node tree upwards for the prefix name for the namespace URI.
virtual XmlNodePtr uicore::XmlNode::first_attribute () const pure virtual
virtual XmlNodePtr uicore::XmlNode::first_child () const pure virtual
Referenced by has_child_nodes().
virtual bool uicore::XmlNode::has_attribute (const XmlString & name) const pure virtual
virtual bool uicore::XmlNode::has_attribute (const XmlString & namespace_uri, const XmlString & local_name) const pure virtual
virtual bool uicore::XmlNode::has_attributes () const pure virtual
bool uicore::XmlNode::has_child_nodes () const inline
References first_child().
virtual XmlNodePtr uicore::XmlNode::insert_before (const XmlNodePtr & new_child, const XmlNodePtr & ref_child) pure virtual
bool uicore::XmlNode::is_attr () const inline
References uicore::attribute, and type().
bool uicore::XmlNode::is_cdata_section () const inline
References uicore::cdata, and type().
bool uicore::XmlNode::is_comment () const inline
References uicore::comment, and type().
bool uicore::XmlNode::is_document () const inline
References uicore::document, and type().
bool uicore::XmlNode::is_document_fragment () const inline
References uicore::document_fragment, and type().
bool uicore::XmlNode::is_element () const inline
References uicore::element, and type().
bool uicore::XmlNode::is_text () const inline
References uicore::text, and type().
virtual XmlNodePtr uicore::XmlNode::last_child () const pure virtual
virtual XmlString uicore::XmlNode::local_name () const pure virtual
virtual XmlString uicore::XmlNode::name () const pure virtual
virtual XmlNodePtr uicore::XmlNode::named_item (const XmlString & name) const pure virtual
Returns the first child node with the specified node name. Returns null if no child is found.
virtual XmlNodePtr uicore::XmlNode::named_item (const XmlString & namespace_uri, const XmlString & local_name) const pure virtual
virtual XmlString uicore::XmlNode::namespace_uri () const pure virtual
virtual XmlNodePtr uicore::XmlNode::next_sibling () const pure virtual
virtual XmlDocumentPtr uicore::XmlNode::owner_document () const pure virtual
virtual XmlNodePtr uicore::XmlNode::parent () const pure virtual
virtual XmlString uicore::XmlNode::prefix () const pure virtual
virtual XmlNodePtr uicore::XmlNode::previous_sibling () const pure virtual
virtual void uicore::XmlNode::remove_attribute (const XmlString & name) pure virtual
virtual void uicore::XmlNode::remove_attribute (const XmlString & namespace_uri, const XmlString & local_name) pure virtual
virtual XmlNodePtr uicore::XmlNode::remove_attribute (const XmlNodePtr & old_attribute) pure virtual
virtual XmlNodePtr uicore::XmlNode::remove_child (const XmlNodePtr & old_child) pure virtual
virtual XmlNodePtr uicore::XmlNode::replace_child (const XmlNodePtr & new_child, const XmlNodePtr & old_child) pure virtual
virtual void uicore::XmlNode::set_attribute (const XmlString & name, const XmlString & value) pure virtual
virtual void uicore::XmlNode::set_attribute (const XmlString & namespace_uri, const XmlString & qualified_name, const XmlString & value) pure virtual
virtual void uicore::XmlNode::set_prefix (const XmlString & prefix) pure virtual
virtual void uicore::XmlNode::set_text (const XmlString & value) pure virtual
virtual XmlString uicore::XmlNode::text () const pure virtual
virtual XmlNodeType uicore::XmlNode::type () const pure virtual
Referenced by is_attr(), is_cdata_section(), is_comment(), is_document(), is_document_fragment(), is_element(), and is_text().
The documentation for this class was generated from the following file:
xml_node.h