uicore::PrimitivesArray Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::PrimitivesArray Class Reference abstract
Primitives array description.
#include <primitives_array.h>
Public Member Functions
virtual void set_attributes (int index, const VertexArrayBufferPtr &buffer, int size, VertexAttributeDataType type, size_t offset=0, int stride=0, bool normalize=false)=0
Set attributes.
void set_attributes (int index, const VertexArrayVector< unsigned char > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< char > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< unsigned short > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< short > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< unsigned int > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< int > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< float > &buffer, int size, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< unsigned char > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< signed char > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< unsigned short > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< signed short > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< unsigned int > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< signed int > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< float > &buffer)
void set_attributes (int index, const VertexArrayVector< Vec2ub > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec2b > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec2us > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec2s > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec2ui > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec2i > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec2f > &buffer)
void set_attributes (int index, const VertexArrayVector< Vec3ub > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec3b > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec3us > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec3s > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec3ui > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec3i > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec3f > &buffer)
void set_attributes (int index, const VertexArrayVector< Vec4ub > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec4b > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec4us > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec4s > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec4ui > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec4i > &buffer, bool normalize=false)
void set_attributes (int index, const VertexArrayVector< Vec4f > &buffer)
void set_attributes (int index, const VertexArrayVector< Colorf > &buffer)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, unsigned char *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, signed char *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, unsigned short *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, signed short *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, unsigned int *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, signed int *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, float *member_offset)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2ub *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2b *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2us *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2s *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2ui *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2i *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec2f *member_offset)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3ub *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3b *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3us *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3s *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3ui *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3i *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec3f *member_offset)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4ub *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4b *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4us *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4s *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4ui *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4i *member_offset, bool normalize=false)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Vec4f *member_offset)
template<typename Type >
void set_attributes (int index, const VertexArrayVector< Type > &buffer, Colorf *member_offset)
Static Public Member Functions
static std::shared_ptr< PrimitivesArray > create (const GraphicContextPtr &gc)
Constructs a PrimitivesArray.
Detailed Description
Primitives array description.
Member Function Documentation
static std::shared_ptr<PrimitivesArray> uicore::PrimitivesArray::create (const GraphicContextPtr & gc) static
Constructs a PrimitivesArray.
virtual void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayBufferPtr & buffer, int size, VertexAttributeDataType type, size_t offset = 0, int stride = 0, bool normalize = false) pure virtual
Set attributes.
Referenced by set_attributes().
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< unsigned char > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< char > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< unsigned short > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< short > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< unsigned int > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< int > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< float > & buffer, int size, bool normalize = false) inline
References set_attributes(), and uicore::type_float.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< unsigned char > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< signed char > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< unsigned short > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< signed short > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< unsigned int > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< signed int > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< float > & buffer) inline
References set_attributes(), and uicore::type_float.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2ub > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2b > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2us > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2s > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2ui > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2i > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec2f > & buffer) inline
References set_attributes(), and uicore::type_float.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3ub > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3b > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3us > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3s > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3ui > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3i > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec3f > & buffer) inline
References set_attributes(), and uicore::type_float.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4ub > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4b > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4us > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4s > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4ui > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4i > & buffer, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Vec4f > & buffer) inline
References set_attributes(), and uicore::type_float.
void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Colorf > & buffer) inline
References set_attributes(), and uicore::type_float.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, unsigned char * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, signed char * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, unsigned short * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, signed short * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, unsigned int * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, signed int * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, float * member_offset) inline
References set_attributes(), and uicore::type_float.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2ub * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2b * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2us * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2s * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2ui * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2i * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec2f * member_offset) inline
References set_attributes(), and uicore::type_float.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3ub * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3b * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3us * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3s * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3ui * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3i * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec3f * member_offset) inline
References set_attributes(), and uicore::type_float.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4ub * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4b * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_byte.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4us * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4s * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_short.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4ui * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_unsigned_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4i * member_offset, bool normalize = false) inline
References set_attributes(), and uicore::type_int.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Vec4f * member_offset) inline
References set_attributes(), and uicore::type_float.
template<typename Type > void uicore::PrimitivesArray::set_attributes (int index, const VertexArrayVector< Type > & buffer, Colorf * member_offset) inline
References set_attributes(), and uicore::type_float.
The documentation for this class was generated from the following file:
primitives_array.h
© ClanLib.org