uicore::View Class Reference - UICore SDK
uicore::View Class Reference
View for an area of the user interface.
#include <view.h>
Public Member Functions
View ()
virtual ~View ()
const std::vector< std::shared_ptr< ViewAction > > & actions () const
List of all action recognizers.
void activated (ActivationChangeEvent *e) override
Handler for when the application is activated.
void add_action (const std::shared_ptr< ViewAction > &action)
Add an action recognizer.
template<typename T , typename... Types>
std::shared_ptr< T > add_action (Types &&...args)
void add_child (const std::shared_ptr< View > &view)
Add a child view.
template<typename T , typename... Types>
std::shared_ptr< T > add_child (Types &&...args)
std::shared_ptr< View > add_child ()
void animate (float from, float to, const std::function< void(float)> &setter, int duration_ms=400, const std::function< float(float)> &easing=Easing::linear, std::function< void()> animation_end=std::function< void()>())
Continously call an animation function for the specified duration.
CanvasPtr canvas () const
const std::vector< std::shared_ptr< View > > & children () const
List of all immediate child views.
void clear_exception_encountered ()
void close (CloseEvent *e) override
Handler for close events.
bool content_clipped () const
Content clipping flag.
void deactivated (ActivationChangeEvent *e) override
Handler for when the application is deactivated.
void dispatch_event (EventUI *e, bool no_propagation=false)
void dispatch_event (EventUI *e, const View *until_parent_view)
std::shared_ptr< View > find_view_at (const Pointf &pos) const
Find descendant view at the specified content relative position.
float first_baseline_offset (const CanvasPtr &canvas, float width)
Calculates the offset to the first baseline.
void focus_gained (FocusChangeEvent *e) override
Handler for focus gained events.
void focus_lost (FocusChangeEvent *e) override
Handler for focus lost events.
FocusPolicy focus_policy () const
Focus policy active for this view.
View * focus_view () const
The view receiving keyboard events or nullptr if no view has the focus.
Pointf from_root_pos (const Pointf &pos)
Map from root content to local content coordinates.
Pointf from_screen_pos (const Pointf &pos)
Map from screen to local content coordinates.
const ViewGeometry & geometry () const
Actual view position and size after layout.
bool has_focus () const
Test if this view is receiving keyboard input.
bool hidden () const
Test if view is set to hidden.
bool is_static_position_and_visible () const
Test if view should participate in static layout calculations (layout_children)
void key_press (KeyEvent *e) override
Handler for key press events.
void key_release (KeyEvent *e) override
Handler for key release events.
float last_baseline_offset (const CanvasPtr &canvas, float width)
Calculates the offset to the last baseline.
virtual void layout_children (const CanvasPtr &canvas)
Sets the view geometry for all children of this view.
bool needs_layout () const
Test if view geometry needs to be recalculated.
void next_focus ()
Give focus to the next view in the keyboard tab index order.
View * parent () const
Parent view node or nullptr if the view is the current root node.
void pointer_double_click (PointerEvent *e) override
Handler for pointer double click events.
void pointer_enter (PointerEvent *e) override
Handler for pointer enter events.
void pointer_leave (PointerEvent *e) override
Handler for pointer leave events.
void pointer_move (PointerEvent *e) override
Handler for pointer movement events.
void pointer_press (PointerEvent *e) override
Handler for pointer press events.
void pointer_proximity_change (PointerEvent *e) override
Handler for pointer proximity change events.
void pointer_release (PointerEvent *e) override
Handler for pointer release events.
float preferred_height (const CanvasPtr &canvas, float width)
Calculates the preferred height of this view.
float preferred_width (const CanvasPtr &canvas)
Calculates the preferred width of this view.
void prev_focus ()
Give focus to the previous view in the keyboard tab index order.
void remove_focus ()
Remove focus from this view.
void remove_from_parent ()
Remove view from parent.
bool render_exception_encountered () const
Test if this view generated an exception during rendering.
void set_content_clipped (bool clipped)
Specifies if content should be clipped during rendering.
void set_cursor (const CursorDescription &cursor)
Set the cursor icon used when cursor is above this view.
void set_cursor (StandardCursor type)
void set_focus ()
Set this view as the focused view.
void set_focus_policy (FocusPolicy policy)
Set if this view automatically can gain focus.
void set_geometry (const ViewGeometry &geometry)
void set_hidden (bool value=true)
Hides a view from layout and rendering.
void set_inherit_cursor ()
Specify that the cursor icon is inherited from the parent view.
void set_needs_layout ()
Forces recalculation of view geometry before next rendering.
void set_needs_render ()
Signals this view needs to be rendered again.
void set_state (const std::string &name, bool value)
Set or clear style state.
void set_state_cascade (const std::string &name, bool value)
Sets the state for this view and all siblings recursively, until a manually set state of the same name is found.
void set_tab_index (unsigned int index)
Sets the tab index used for keyboard focus changes.
void set_view_transform (const Mat4f &transform)
Specifies the view transform to be applied before its contents and children are rendered.
Signal< void(ActivationChangeEvent *)> & sig_activated ()
Signal< void(CloseEvent *)> & sig_close ()
Signal< void(ActivationChangeEvent *)> & sig_deactivated ()
Signal< void(FocusChangeEvent *)> & sig_focus_gained ()
Signal< void(FocusChangeEvent *)> & sig_focus_lost ()
Signal< void(KeyEvent *)> & sig_key_press ()
Signal< void(KeyEvent *)> & sig_key_release ()
Signal< void(PointerEvent *)> & sig_pointer_double_click ()
Signal< void(PointerEvent *)> & sig_pointer_enter ()
Signal< void(PointerEvent *)> & sig_pointer_leave ()
Signal< void(PointerEvent *)> & sig_pointer_move ()
Signal< void(PointerEvent *)> & sig_pointer_press ()
Signal< void(PointerEvent *)> & sig_pointer_proximity_change ()
Signal< void(PointerEvent *)> & sig_pointer_release ()
bool state (const std::string &name) const
Test if a style state is currently set.
void stop_animations ()
Stop all activate animation functions.
const std::shared_ptr< Style > & style (const std::string &state=std::string()) const
Style properties for the specified state.
const StyleCascade & style_cascade () const
Style cascade currently active for this view.
unsigned int tab_index () const
Tab index for keyboard focus changes.
Pointf to_root_pos (const Pointf &pos)
Map from local content to root content coordinates.
Pointf to_screen_pos (const Pointf &pos)
Map from local content to screen coordinates.
void update_cursor (const DisplayWindowPtr &window)
Update window cursor to the cursor used by this view.
const Mat4f & view_transform () const
Current view transform.
const ViewTree * view_tree () const
Tree in view hierachy.
ViewTree * view_tree ()
Static Public Member Functions
static View * common_parent (View *view1, View *view2)
Find the common parent view for the specified views.
Public Attributes
SlotContainer slots
Slot container helping with automatic disconnection of connected slots when the view is destroyed.
Protected Member Functions
virtual float calculate_first_baseline_offset (const CanvasPtr &canvas, float width)
Calculates the offset to the first baseline.
virtual float calculate_last_baseline_offset (const CanvasPtr &canvas, float width)
Calculates the offset to the last baseline.
virtual float calculate_preferred_height (const CanvasPtr &canvas, float width)
Calculates the preferred height of this view.
virtual float calculate_preferred_width (const CanvasPtr &canvas)
Calculates the preferred width of this view.
virtual void child_added (const std::shared_ptr< View > &view)
Child view was added to this view.
virtual void child_removed (const std::shared_ptr< View > &view)
Child view was removed from this view.
virtual void render_content (const CanvasPtr &canvas)
Renders the content of a view.
Friends
class ViewAction
class ViewImpl
class ViewTree
Detailed Description
View for an area of the user interface.
Constructor & Destructor Documentation
uicore::View::View ()
virtual uicore::View::~View () virtual
Member Function Documentation
const std::vector<std::shared_ptr<ViewAction> >& uicore::View::actions () const
List of all action recognizers.
void uicore::View::activated (ActivationChangeEvent * e) inline override virtual
Handler for when the application is activated.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_activated().
void uicore::View::add_action (const std::shared_ptr< ViewAction > & action)
Add an action recognizer.
Referenced by add_action().
template<typename T , typename... Types> std::shared_ptr<T> uicore::View::add_action (Types &&... args) inline
References add_action().
void uicore::View::add_child (const std::shared_ptr< View > & view)
Add a child view.
template<typename T , typename... Types> std::shared_ptr<T> uicore::View::add_child (Types &&... args) inline
References add_child().
std::shared_ptr<View> uicore::View::add_child () inline
Referenced by add_child().
void uicore::View::animate (float from, float to, const std::function< void(float)> & setter, int duration_ms = 400, const std::function< float(float)> & easing = Easing::linear, std::function< void()> animation_end = std::function< void()>())
Continously call an animation function for the specified duration.
virtual float uicore::View::calculate_first_baseline_offset (const CanvasPtr & canvas, float width) protected virtual
Calculates the offset to the first baseline.
Reimplemented in uicore::TextFieldBaseView, uicore::TextAreaBaseView, uicore::LabelBaseView, uicore::ScrollBaseView, and uicore::TextBlockBaseView.
virtual float uicore::View::calculate_last_baseline_offset (const CanvasPtr & canvas, float width) protected virtual
Calculates the offset to the last baseline.
Reimplemented in uicore::TextFieldBaseView, uicore::TextAreaBaseView, uicore::LabelBaseView, uicore::ScrollBaseView, and uicore::TextBlockBaseView.
virtual float uicore::View::calculate_preferred_height (const CanvasPtr & canvas, float width) protected virtual
Calculates the preferred height of this view.
Reimplemented in uicore::TextFieldBaseView, uicore::TextAreaBaseView, uicore::LabelBaseView, uicore::ImageBaseView, uicore::ScrollBaseView, and uicore::TextBlockBaseView.
virtual float uicore::View::calculate_preferred_width (const CanvasPtr & canvas) protected virtual
Calculates the preferred width of this view.
Reimplemented in uicore::TextFieldBaseView, uicore::TextAreaBaseView, uicore::LabelBaseView, uicore::ImageBaseView, uicore::ScrollBaseView, and uicore::TextBlockBaseView.
CanvasPtr uicore::View::canvas () const
Gets the current canvas used to render this view
This function may return a null canvas if the view does not have a canvas attached to it yet.
virtual void uicore::View::child_added (const std::shared_ptr< View > & view) inline protected virtual
Child view was added to this view.
Reimplemented in uicore::TextBlockBaseView.
virtual void uicore::View::child_removed (const std::shared_ptr< View > & view) inline protected virtual
Child view was removed from this view.
Reimplemented in uicore::TextBlockBaseView.
const std::vector<std::shared_ptr<View> >& uicore::View::children () const
List of all immediate child views.
void uicore::View::clear_exception_encountered ()
Clears exception encountered flag
If a view generates an exception during rendering the view's render_content function will not be called again until this function is called.
void uicore::View::close (CloseEvent * e) inline override virtual
Handler for close events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_close().
static View* uicore::View::common_parent (View * view1, View * view2) static
Find the common parent view for the specified views.
bool uicore::View::content_clipped () const
Content clipping flag.
void uicore::View::deactivated (ActivationChangeEvent * e) inline override virtual
Handler for when the application is deactivated.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_deactivated().
void uicore::View::dispatch_event (EventUI * e, bool no_propagation = false)
Dispatch view event
Parameters
until_parent_view = Dispatch until current target is this view, then propagation stops
void uicore::View::dispatch_event (EventUI * e, const View * until_parent_view)
std::shared_ptr<View> uicore::View::find_view_at (const Pointf & pos) const
Find descendant view at the specified content relative position.
float uicore::View::first_baseline_offset (const CanvasPtr & canvas, float width)
Calculates the offset to the first baseline.
void uicore::View::focus_gained (FocusChangeEvent * e) inline override virtual
Handler for focus gained events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_focus_gained().
void uicore::View::focus_lost (FocusChangeEvent * e) inline override virtual
Handler for focus lost events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_focus_lost().
FocusPolicy uicore::View::focus_policy () const
Focus policy active for this view.
View* uicore::View::focus_view () const
The view receiving keyboard events or nullptr if no view has the focus.
Referenced by has_focus().
Pointf uicore::View::from_root_pos (const Pointf & pos)
Map from root content to local content coordinates.
Pointf uicore::View::from_screen_pos (const Pointf & pos)
Map from screen to local content coordinates.
const ViewGeometry& uicore::View::geometry () const
Actual view position and size after layout.
bool uicore::View::has_focus () const inline
Test if this view is receiving keyboard input.
References focus_view().
bool uicore::View::hidden () const
Test if view is set to hidden.
bool uicore::View::is_static_position_and_visible () const
Test if view should participate in static layout calculations (layout_children)
void uicore::View::key_press (KeyEvent * e) inline override virtual
Handler for key press events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_key_press().
void uicore::View::key_release (KeyEvent * e) inline override virtual
Handler for key release events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_key_release().
float uicore::View::last_baseline_offset (const CanvasPtr & canvas, float width)
Calculates the offset to the last baseline.
virtual void uicore::View::layout_children (const CanvasPtr & canvas) virtual
Sets the view geometry for all children of this view.
Reimplemented in uicore::ScrollBarBaseView, uicore::LabelBaseView, uicore::SliderBaseView, uicore::ScrollBaseView, and uicore::TextBlockBaseView.
bool uicore::View::needs_layout () const
Test if view geometry needs to be recalculated.
void uicore::View::next_focus ()
Give focus to the next view in the keyboard tab index order.
View* uicore::View::parent () const
Parent view node or nullptr if the view is the current root node.
void uicore::View::pointer_double_click (PointerEvent * e) inline override virtual
Handler for pointer double click events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_double_click().
void uicore::View::pointer_enter (PointerEvent * e) inline override virtual
Handler for pointer enter events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_enter().
void uicore::View::pointer_leave (PointerEvent * e) inline override virtual
Handler for pointer leave events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_leave().
void uicore::View::pointer_move (PointerEvent * e) inline override virtual
Handler for pointer movement events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_move().
void uicore::View::pointer_press (PointerEvent * e) inline override virtual
Handler for pointer press events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_press().
void uicore::View::pointer_proximity_change (PointerEvent * e) inline override virtual
Handler for pointer proximity change events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_proximity_change().
void uicore::View::pointer_release (PointerEvent * e) inline override virtual
Handler for pointer release events.
Reimplemented from uicore::ViewEventHandler.
References uicore::e, and sig_pointer_release().
float uicore::View::preferred_height (const CanvasPtr & canvas, float width)
Calculates the preferred height of this view.
float uicore::View::preferred_width (const CanvasPtr & canvas)
Calculates the preferred width of this view.
void uicore::View::prev_focus ()
Give focus to the previous view in the keyboard tab index order.
void uicore::View::remove_focus ()
Remove focus from this view.
void uicore::View::remove_from_parent ()
Remove view from parent.
virtual void uicore::View::render_content (const CanvasPtr & canvas) inline protected virtual
Renders the content of a view.
Reimplemented in uicore::TextFieldBaseView, uicore::TextAreaBaseView, uicore::LabelBaseView, uicore::ImageBaseView, and uicore::TextBlockBaseView.
bool uicore::View::render_exception_encountered () const
Test if this view generated an exception during rendering.
void uicore::View::set_content_clipped (bool clipped)
Specifies if content should be clipped during rendering.
void uicore::View::set_cursor (const CursorDescription & cursor)
Set the cursor icon used when cursor is above this view.
void uicore::View::set_cursor (StandardCursor type)
void uicore::View::set_focus ()
Set this view as the focused view.
void uicore::View::set_focus_policy (FocusPolicy policy)
Set if this view automatically can gain focus.
void uicore::View::set_geometry (const ViewGeometry & geometry)
Sets the view position and size
This function should only be called by layout_children.
void uicore::View::set_hidden (bool value = true)
Hides a view from layout and rendering.
void uicore::View::set_inherit_cursor ()
Specify that the cursor icon is inherited from the parent view.
void uicore::View::set_needs_layout ()
Forces recalculation of view geometry before next rendering.
void uicore::View::set_needs_render ()
Signals this view needs to be rendered again.
void uicore::View::set_state (const std::string & name, bool value)
Set or clear style state.
void uicore::View::set_state_cascade (const std::string & name, bool value)
Sets the state for this view and all siblings recursively, until a manually set state of the same name is found.
void uicore::View::set_tab_index (unsigned int index)
Sets the tab index used for keyboard focus changes.
void uicore::View::set_view_transform (const Mat4f & transform)
Specifies the view transform to be applied before its contents and children are rendered.
Signal<void(ActivationChangeEvent *)>& uicore::View::sig_activated ()
Referenced by activated().
Signal<void(CloseEvent *)>& uicore::View::sig_close ()
Referenced by close().
Signal<void(ActivationChangeEvent *)>& uicore::View::sig_deactivated ()
Referenced by deactivated().
Signal<void(FocusChangeEvent *)>& uicore::View::sig_focus_gained ()
Referenced by focus_gained().
Signal<void(FocusChangeEvent *)>& uicore::View::sig_focus_lost ()
Referenced by focus_lost().
Signal<void(KeyEvent *)>& uicore::View::sig_key_press ()
Referenced by key_press().
Signal<void(KeyEvent *)>& uicore::View::sig_key_release ()
Referenced by key_release().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_double_click ()
Referenced by pointer_double_click().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_enter ()
Referenced by pointer_enter().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_leave ()
Referenced by pointer_leave().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_move ()
Referenced by pointer_move().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_press ()
Referenced by pointer_press().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_proximity_change ()
Referenced by pointer_proximity_change().
Signal<void(PointerEvent *)>& uicore::View::sig_pointer_release ()
Referenced by pointer_release().
bool uicore::View::state (const std::string & name) const
Test if a style state is currently set.
void uicore::View::stop_animations ()
Stop all activate animation functions.
const std::shared_ptr<Style>& uicore::View::style (const std::string & state = std::string()) const
Style properties for the specified state.
Referenced by uicore::ColumnView::ColumnView(), uicore::RowView::RowView(), and uicore::SpacerView::SpacerView().
const StyleCascade& uicore::View::style_cascade () const
Style cascade currently active for this view.
unsigned int uicore::View::tab_index () const
Tab index for keyboard focus changes.
Pointf uicore::View::to_root_pos (const Pointf & pos)
Map from local content to root content coordinates.
Pointf uicore::View::to_screen_pos (const Pointf & pos)
Map from local content to screen coordinates.
void uicore::View::update_cursor (const DisplayWindowPtr & window)
Update window cursor to the cursor used by this view.
const Mat4f& uicore::View::view_transform () const
Current view transform.
const ViewTree* uicore::View::view_tree () const
Tree in view hierachy.
ViewTree* uicore::View::view_tree ()
Friends And Related Function Documentation
friend class ViewAction friend
friend class ViewImpl friend
friend class ViewTree friend
Member Data Documentation
SlotContainer uicore::View::slots
Slot container helping with automatic disconnection of connected slots when the view is destroyed.
The documentation for this class was generated from the following file:
view.h