uicore::SocketName Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::SocketName Class Reference
Socket name; container class for an IP address and port.
#include <socket_name.h>
Public Member Functions
SocketName ()
Constructs a new socket name.
SocketName (const std::string &port)
SocketName (const std::string &address, const std::string &port)
const std::string & address () const
Returns the address part of the socket name.
void from_sockaddr (int domain, sockaddr *addr, int len)
Get the socket name from a C sockets sockaddr structure.
std::string lookup_hostname () const
Perform a DNS lookup, if needed, for the hostname.
std::string lookup_ipv4 () const
Perform a DNS lookup, if needed, for the IP v4 address.
bool operator< (const SocketName &other_instance) const
bool operator== (const SocketName &other_instance) const
const std::string & port () const
Returns the port part of the socket name.
void set_address (const std::string &address)
Set the IP address.
void set_name (const std::string &hostname, const std::string &port)
Set the socket name using a hostname and port.
void set_port (const std::string &port)
Set the IP port.
SocketName to_hostname ()
Create socket name that uses the hostname as its address.
SocketName to_ipv4 ()
Create socket name that uses the IP v4 address as its address.
void to_sockaddr (int domain, sockaddr *addr, int len) const
Fill the socket name into a C sockets sockaddr structure.
Detailed Description
Socket name; container class for an IP address and port.
Constructor & Destructor Documentation
uicore::SocketName::SocketName () inline
Constructs a new socket name.
If no address is specified, the socket address will default to INADDR_ANY. If no port is specified, it will default to port 0.
uicore::SocketName::SocketName (const std::string & port) inline
uicore::SocketName::SocketName (const std::string & address, const std::string & port) inline
Member Function Documentation
const std::string& uicore::SocketName::address () const inline
Returns the address part of the socket name.
Referenced by set_address().
void uicore::SocketName::from_sockaddr (int domain, sockaddr * addr, int len)
Get the socket name from a C sockets sockaddr structure.
std::string uicore::SocketName::lookup_hostname () const
Perform a DNS lookup, if needed, for the hostname.
std::string uicore::SocketName::lookup_ipv4 () const
Perform a DNS lookup, if needed, for the IP v4 address.
bool uicore::SocketName::operator< (const SocketName & other_instance) const
bool uicore::SocketName::operator== (const SocketName & other_instance) const
const std::string& uicore::SocketName::port () const inline
Returns the port part of the socket name.
Referenced by set_name(), and set_port().
void uicore::SocketName::set_address (const std::string & address) inline
Set the IP address.
Parameters
address Can be an IPv4 dotted-quad, hostname or a valid IPv6 address.
References address().
void uicore::SocketName::set_name (const std::string & hostname, const std::string & port) inline
Set the socket name using a hostname and port.
Parameters
hostname Can be an IPv4 dotted-quad, hostname or a valid IPv6 address.
port Port number.
References port().
void uicore::SocketName::set_port (const std::string & port) inline
Set the IP port.
References port().
SocketName uicore::SocketName::to_hostname ()
Create socket name that uses the hostname as its address.
SocketName uicore::SocketName::to_ipv4 ()
Create socket name that uses the IP v4 address as its address.
void uicore::SocketName::to_sockaddr (int domain, sockaddr * addr, int len) const
Fill the socket name into a C sockets sockaddr structure.
The documentation for this class was generated from the following file:
socket_name.h
© ClanLib.org