uicore::Endian Class Reference - UICore SDK
uicore::Endian Class Reference
#include <endian.h>
Static Public Member Functions
static uint8_t swap (uint8_t val)
static int8_t swap (int8_t val)
static uint16_t swap (uint16_t val)
static int16_t swap (int16_t val)
static uint32_t swap (uint32_t val)
static int32_t swap (int32_t val)
static uint64_t swap (uint64_t val)
static int64_t swap (int64_t val)
static float swap (float val)
static double swap (double val)
Member Function Documentation
static uint8_t uicore::Endian::swap (uint8_t val) inline static
Referenced by uicore::IODevice::read_type(), swap(), and uicore::IODevice::write_type().
static int8_t uicore::Endian::swap (int8_t val) inline static
static uint16_t uicore::Endian::swap (uint16_t val) inline static
static int16_t uicore::Endian::swap (int16_t val) inline static
References swap().
static uint32_t uicore::Endian::swap (uint32_t val) inline static
static int32_t uicore::Endian::swap (int32_t val) inline static
References swap().
static uint64_t uicore::Endian::swap (uint64_t val) inline static
static int64_t uicore::Endian::swap (int64_t val) inline static
References swap().
static float uicore::Endian::swap (float val) inline static
static double uicore::Endian::swap (double val) inline static
The documentation for this class was generated from the following file:
endian.h