uicore::WindowManager Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::WindowManager Class Reference
Manages one or more windows.
#include <window_manager.h>
Static Public Member Functions
static void present_main (const std::shared_ptr< WindowController > &controller)
Shows a main window.
template<typename T , typename... Types>
static std::shared_ptr< T > present_main (Types &&...args)
static void present_modal (View *owner, const std::shared_ptr< WindowController > &controller)
Shows a modal dialog.
template<typename T , typename... Types>
static std::shared_ptr< T > present_modal (View *owner, Types &&...args)
static void present_popup (View *owner, const Pointf &pos, const std::shared_ptr< WindowController > &controller)
Shows a popup window.
template<typename T , typename... Types>
static std::shared_ptr< T > present_popup (View *owner, const Pointf &pos, Types &&...args)
static void set_exit_on_last_close (bool enable=true)
Notifices RunLoop to exit when last presented window is dismissed.
Friends
class WindowController
Detailed Description
Manages one or more windows.
Member Function Documentation
static void uicore::WindowManager::present_main (const std::shared_ptr< WindowController > & controller) static
Shows a main window.
Referenced by present_main().
template<typename T , typename... Types> static std::shared_ptr<T> uicore::WindowManager::present_main (Types &&... args) inline static
References present_main().
static void uicore::WindowManager::present_modal (View * owner, const std::shared_ptr< WindowController > & controller) static
Shows a modal dialog.
Referenced by present_modal().
template<typename T , typename... Types> static std::shared_ptr<T> uicore::WindowManager::present_modal (View * owner, Types &&... args) inline static
References present_modal().
static void uicore::WindowManager::present_popup (View * owner, const Pointf & pos, const std::shared_ptr< WindowController > & controller) static
Shows a popup window.
Referenced by present_popup().
template<typename T , typename... Types> static std::shared_ptr<T> uicore::WindowManager::present_popup (View * owner, const Pointf & pos, Types &&... args) inline static
References present_popup().
static void uicore::WindowManager::set_exit_on_last_close (bool enable = true) static
Notifices RunLoop to exit when last presented window is dismissed.
Friends And Related Function Documentation
friend class WindowController friend
The documentation for this class was generated from the following file:
window_manager.h
© ClanLib.org