uicore::Texture2DArray Class Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::Texture2DArray Class Reference abstract
2D texture array object class.
#include <texture_2d_array.h>
Public Member Functions
virtual int array_size () const =0
Returns the number of textures in the array.
virtual std::shared_ptr< Texture2D > create_2d_view (int array_index, TextureFormat texture_format, int min_level, int num_levels)=0
Creates a 2D texture view.
virtual int height () const =0
Retrieves the actual height of the texture in the display.
virtual void set_image (const GraphicContextPtr &context, int array_index, const PixelBufferPtr &image, int level=0)=0
virtual void set_subimage (const GraphicContextPtr &context, int array_index, int x, int y, const PixelBufferPtr &image, const Rect &src_rect, int level=0)=0
void set_subimage (const GraphicContextPtr &context, int array_index, const Point &point, const PixelBufferPtr &image, const Rect &src_rect, int level=0)
virtual void set_wrap_mode (TextureWrapMode wrap_s, TextureWrapMode wrap_t)=0
Size size () const
Retrieves the actual size of the texture.
virtual int width () const =0
Retrieves the actual width of the texture in the display.
virtual TextureWrapMode wrap_mode_s () const =0
Get the texture wrap mode for the s coordinate.
virtual TextureWrapMode wrap_mode_t () const =0
Get the texture wrap mode for the t coordinate.
Public Member Functions inherited from uicore::Texture
virtual int base_level () const =0
Get the texture base level.
virtual CompareFunction compare_function () const =0
Get the texture compare function.
virtual TextureCompareMode compare_mode () const =0
Get the texture compare mode.
virtual void generate_mipmap ()=0
Generate mipmap textures.
virtual float lod_bias () const =0
Get the level of detail bias constant.
virtual TextureFilter mag_filter () const =0
Get the texture magnification filter.
virtual int max_level () const =0
Get the texture max level.
virtual float max_lod () const =0
Get the maximum level of detail.
virtual TextureFilter min_filter () const =0
Get the texture minification filter.
virtual float min_lod () const =0
Get the minimum level of detail.
virtual void set_base_level (int base_level)=0
Sets the texture base level texture parameter.
virtual void set_lod_bias (float lod_bias)=0
Sets the level of detail bias constant.
virtual void set_mag_filter (TextureFilter filter)=0
Set the magnification filter.
virtual void set_max_anisotropy (float max_anisotropy)=0
Set the maximum degree of anisotropy.
virtual void set_max_level (int max_level)=0
Sets the texture max level texture parameter.
virtual void set_max_lod (float max_lod)=0
Set the maximum level of detail texture parameter.
virtual void set_min_filter (TextureFilter filter)=0
Set the minification filter.
virtual void set_min_lod (float min_lod)=0
Set the minimum level of detail texture parameter.
virtual void set_texture_compare (TextureCompareMode mode, CompareFunction func)=0
Sets the texture compare mode and compare function texture parameters.
virtual TextureObject * texture_object ()=0
Static Public Member Functions
static std::shared_ptr< Texture2DArray > create (const GraphicContextPtr &context, int width, int height, int array_size, TextureFormat texture_format=tf_rgba8, int levels=1)
static std::shared_ptr< Texture2DArray > create (const GraphicContextPtr &context, const Size &size, int array_size, TextureFormat texture_format=tf_rgba8, int levels=1)
Static Public Member Functions inherited from uicore::Texture
static std::shared_ptr< Texture > create (const GraphicContextPtr &gc, PixelBufferSetPtr pixelbuffer_set)
Constructs a texture as described by a pixelbuffer set.
Detailed Description
2D texture array object class.
Member Function Documentation
virtual int uicore::Texture2DArray::array_size () const pure virtual
Returns the number of textures in the array.
static std::shared_ptr<Texture2DArray> uicore::Texture2DArray::create (const GraphicContextPtr & context, int width, int height, int array_size, TextureFormat texture_format = tf_rgba8, int levels = 1) static
Constructs a new 2D array texture.
Parameters
context Graphic context to construct the texture on.
width Width of the new texture.
height Height of the new texture.
array_size Number of textures to allocate in this array.
format Data format of the new texture.
levels Number of mipmap levels for the new texture. Setting this to 0 enables all levels.
static std::shared_ptr<Texture2DArray> uicore::Texture2DArray::create (const GraphicContextPtr & context, const Size & size, int array_size, TextureFormat texture_format = tf_rgba8, int levels = 1) static
virtual std::shared_ptr<Texture2D> uicore::Texture2DArray::create_2d_view (int array_index, TextureFormat texture_format, int min_level, int num_levels) pure virtual
Creates a 2D texture view.
virtual int uicore::Texture2DArray::height () const pure virtual
Retrieves the actual height of the texture in the display.
Referenced by size().
virtual void uicore::Texture2DArray::set_image (const GraphicContextPtr & context, int array_index, const PixelBufferPtr & image, int level = 0) pure virtual
Upload image to this texture array.
Parameters
context Graphic context to use for the request.
array_index Index in the array to upload the image into.
image Image to upload.
level Mipmap level-of-detail number.
virtual void uicore::Texture2DArray::set_subimage (const GraphicContextPtr & context, int array_index, int x, int y, const PixelBufferPtr & image, const Rect & src_rect, int level = 0) pure virtual
Upload image to sub-texture.
Parameters
context Graphic context to use for the request.
array_index Index in the array to upload the image into.
x The horizontal point in the selected texture to write the new sub-texture image onto.
y The vertical point in the selected texture to write the sub-texture image onto.
point Point in the selected texture to write the new sub-texture image onto.
image Image to upload.
level Mipmap level-of-detail number.
Referenced by set_subimage().
void uicore::Texture2DArray::set_subimage (const GraphicContextPtr & context, int array_index, const Point & point, const PixelBufferPtr & image, const Rect & src_rect, int level = 0) inline
References set_subimage(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
virtual void uicore::Texture2DArray::set_wrap_mode (TextureWrapMode wrap_s, TextureWrapMode wrap_t) pure virtual
Size uicore::Texture2DArray::size () const inline
Retrieves the actual size of the texture.
References height(), and width().
virtual int uicore::Texture2DArray::width () const pure virtual
Retrieves the actual width of the texture in the display.
Referenced by size().
virtual TextureWrapMode uicore::Texture2DArray::wrap_mode_s () const pure virtual
Get the texture wrap mode for the s coordinate.
virtual TextureWrapMode uicore::Texture2DArray::wrap_mode_t () const pure virtual
Get the texture wrap mode for the t coordinate.
The documentation for this class was generated from the following file:
texture_2d_array.h
© ClanLib.org