uicore::Signal< FuncType > Class Template Reference - ClanLib SDK
Overview Download Documentation Contact
uicore::Signal< FuncType > Class Template Reference
#include <signal.h>
Public Member Functions
Signal ()
Slot connect (const std::function< FuncType > &func)
template<typename InstanceType , typename MemberFuncType >
Slot connect (InstanceType instance, MemberFuncType func)
template<typename... Args>
void operator() (Args &&...args)
Constructor & Destructor Documentation
template<typename FuncType> uicore::Signal< FuncType >::Signal () inline
Member Function Documentation
template<typename FuncType> Slot uicore::Signal< FuncType >::connect (const std::function< FuncType > & func) inline
Referenced by uicore::Signal< FuncType >::connect(), and uicore::SlotContainer::connect().
template<typename FuncType> template<typename InstanceType , typename MemberFuncType > Slot uicore::Signal< FuncType >::connect (InstanceType instance, MemberFuncType func) inline
References uicore::bind_member(), and uicore::Signal< FuncType >::connect().
template<typename FuncType> template<typename... Args> void uicore::Signal< FuncType >::operator() (Args &&... args) inline
The documentation for this class was generated from the following file:
signal.h
© ClanLib.org