uicore Namespace Reference - ClanLib SDK
Overview Download Documentation Contact
uicore Namespace Reference
Classes
class ActivationChangeEvent
Window was activated or deactivated event.
class AES128_Decrypt
AES-128 decryption class (running in Cipher Block Chaining mode)
class AES128_Encrypt
AES-128 encryption class (running in Cipher Block Chaining mode)
class AES192_Decrypt
AES-192 decryption class (running in Cipher Block Chaining mode)
class AES192_Encrypt
AES-192 encryption class (running in Cipher Block Chaining mode)
class AES256_Decrypt
AES-256 decryption class (running in Cipher Block Chaining mode)
class AES256_Encrypt
AES-256 encryption class (running in Cipher Block Chaining mode)
class Application
Base class for the application object.
class ApplicationInstance
Helper class to create cross platform applications.
class ApplicationInstancePrivate
class AxisAlignedBoundingBox
class Base64Decoder
Base64 decoder class.
class Base64Encoder
Base64 encoder class.
class BigInt
Big Integer class.
class BlendState
class BlendStateDescription
Blend state description.
class BrowseFolderDialog
Displays the system folder browsing dialog.
class Brush
class BrushGradientStop
class ButtonBaseView
class Canvas
2D Graphics Canvas
class CheckBoxBaseView
class Circle
Circle - Integer.
class Circled
Circle - Double.
class Circlef
Circle - Float.
class Circlex
Circle.
class CloseEvent
Window close button was clicked event.
class Color
Color description class.
class Colorf
Floating point color description class (for float).
class ColorHSLx
Color HSL description class.
class ColorHSVx
Color HSV description class.
class ColumnView
class ComPtr
ComPtr.
class CrashReporter
Generates crash reports (aka. minidumps or core dumps) when the application crashes, or when requested.
class Cursor
Mouse cursor class.
class CursorDescription
This class contains everything to construct a cursor - its data, default settings etc.
class CursorDescriptionFrame
This class describes a single frame in a cursor description.
class D3DTarget
Display target for uicoreDisplay.
class DataBuffer
General purpose data buffer.
class DateTime
Date/Time class.
class DDSFormat
Image format that can load Direct3D texture (.dds) files.
class DepthStencilState
class DepthStencilStateDescription
DepthStencil state description.
class DetectHang
Calls CrashReporter::invoke if the constructing thread does not call RunLoop::process for more than 30 seconds.
class Directory
Directory utility class.
class DirectoryScanner
Directory scanning class.
class DisplayTarget
Display target for uicoreDisplay.
class DisplayWindow
Top-level window class.
class DisplayWindowDescription
Display window description class.
struct DisplayWindowHandle
class DisposableObject
DisposableObject.
class EarClipTriangle
Triangle returned by triangulator.
class EarClipTriangulator
Ear-clipping triangulator.
class Easing
class ElementArrayBuffer
Element Array Buffer.
class ElementArrayVector
Typed access to a element array buffer.
class Endian
class EventUI
Base class for events being dispatched through the view hiarchy.
class Exception
Top-level exception class.
class ExceptionDialog
Displays a modal dialog with exception details.
class File
class FilePath
Path helper functions.
class FocusChangeEvent
View focus changed event.
class Font
Font class.
class FontDescription
Font description class.
class FontFamily
FontFamily class.
class FontHandle
class FontMetrics
Font metrics class.
class FrameBuffer
Frame-buffer object class.
class FrustumPlanes
class GLFunctions
GLFunctions.
class GlyphMetrics
Glyph metrics class.
class GraphicContext
Interface to drawing graphics.
class HalfFloat
class HashFunctions
A Collection of checksum functions.
class IconSet
Icon set class.
class Image
Image class.
class ImageBaseView
class ImageFile
Load or save an image.
class ImageFileType
Provider type.
class ImageFileType_Register
Class template to register a provider type.
class ImageImportDescription
Image Import Description Class.
class ImageSource
class InputDevice
InputDevice.
class InputEvent
Input event class.
class IntersectionTest
class IODevice
class JPEGFormat
Image provider that can load JPEG (.jpg) files.
class JsonValue
class KeyEvent
Keyboard key event.
class LabelBaseView
class Line2
2D line - Integer
class Line2d
2D line - Double
class Line2f
2D line - Float
class Line2x
2D line
class Line3
3D line - Integer
class Line3d
3D line - Double
class Line3f
3D line - Float
class Line3x
3D line
class LineMath
Math operations on 2D lines.
class LineRay2
2D line ray - Integer
class LineRay2d
2D line ray - Double
class LineRay2f
2D line ray - Float
class LineRay2x
2D line ray
class LineRay3
3D line ray - Integer
class LineRay3d
3D line ray - Double
class LineRay3f
3D line ray - Float
class LineRay3x
3D line ray
class LineSegment2
2D line segment - Integer
class LineSegment2d
2D line segment - Double
class LineSegment2f
2D line segment - Float
class LineSegment2x
2D line segment
class LineSegment3
3D line segment - Integer
class LineSegment3d
3D line segment - Double
class LineSegment3f
3D line segment - Float
class LineSegment3x
3D line segment
class ListBoxBaseView
class Mat2
2D matrix
class Mat3
3D matrix
class Mat4
4D matrix
class MD5
MD5 hash function class.
class MemoryDevice
struct MessageLog_GL
class NetworkConditionVariable
Condition variable that also awaken on network events.
class NetworkEvent
Base class for all classes that generate network events.
class OcclusionQuery
Graphics occlusion query class.
class OpenFileDialog
Displays the system open file dialog.
class OpenGL
OpenGL utility class.
class OpenGLContextDescription
OpenGL context specific settings.
class OpenGLTarget
Display target for uicoreDisplay.
class OrientedBoundingBox
class Path
class Pen
class PerlinNoise
Perlin Noise Generator class.
class PixelBuffer
Pixel data container.
class PixelBufferSet
Set of images that combined form a complete texture.
class PixelConverter
Pixel format converter class.
class PNGFormat
Surface provider that can load PNG (.png) files.
class PNGOutputDescription
Set PNG output options. Used with PNGFormat::save().
class PNGOutputDescriptionPalette
class Point
2D (x,y) point structure - Integer
class Pointd
2D (x,y) point structure - Double
class PointerEvent
Pointer event.
class Pointf
2D (x,y) point structure - Float
class PointSetMath
Math operations related to point sets.
class Pointx
2D (x,y) point structure.
class PrimitivesArray
Primitives array description.
class ProgramObject
Program Object.
class ProgressBaseView
class Quad
2D quad structure - Integer
class Quadd
2D quad structure - Double
class Quadf
2D quad structure - Float
class Quadx
2D quad structure.
class Quaternionx
Quaternion.
class RadioButtonBaseView
Radio button component.
class Random
Random class.
class RasterizerState
class RasterizerStateDescription
Rasterizer state description.
class Rect
2D (left,top,right,bottom) rectangle structure - Integer
class Rectd
2D (left,top,right,bottom) rectangle structure - Double
class Rectf
2D (left,top,right,bottom) rectangle structure - Float
class RectPacker
Generic rect packer class. Implements an algorithm to pack rects into groups efficiently.
class Rectx
2D (left,top,right,bottom) rectangle structure.
class RegistryKey
Registry key class.
class RenderBuffer
Render target buffer object class.
class ResizeEvent
Window resize event.
class RowView
class RSA
RSA class.
class RunLoop
Main thread message pump processing.
class SaveFileDialog
Displays the system save file dialog.
class ScreenInfo
Screen Information class.
class ScrollBarBaseView
class ScrollBaseView
class Secret
Key class.
class Service
Service/daemon class.
class SHA1
SHA-1 hash function class.
class SHA224
SHA-224 hash function class.
class SHA256
SHA-256 hash function class.
class SHA384
SHA-384 hash function class.
class SHA512
SHA-512 hash function class.
class SHA512_224
SHA-512_224 hash function class.
class SHA512_256
SHA-512_256 hash function class.
class ShaderObject
Shader Object.
class Signal
class SignalImpl
class Singleton
Workaround for broken destruction of static member variables in MSVC.
class SingletonBugfix
Workaround for broken destruction of static member variables in MSVC.
class Size
2D (width,height) size structure - Integer
class Sized
2D (width,height) size structure - Double
class Sizef
2D (width,height) size structure - Float
class Sizex
2D (width,height) size structure.
class SliderBaseView
class Slot
class SlotContainer
class SlotImpl
class SlotImplT
class SocketName
Socket name; container class for an IP address and port.
class SpacerView
class SpanComponent
Component placed in the layout.
class SpinBaseView
SpinBaseView component.
class StagingBuffer
Transfer Buffer.
class StagingTexture
Texture Transfer class.
class StagingVector
Typed access to a transfer buffer.
class StorageBuffer
Storage Buffer.
class StorageVector
Typed access to a storage buffer.
class StringFormat
String formatting class.
class Style
Style property set.
class StyleCascade
Style value resolver.
class StyleGetValue
Style value returned by style classes.
class StyleGradient
Linear or radial gradient.
class StyleGradientStop
Gradient stop in a style gradient.
class StyleImage
Style image values.
class StyleParser
Parser interface used during property parsing.
class StyleProperty
Style property interface used to parse or query properties by name.
class StylePropertyDefault
Sets the default value for a property.
class StylePropertyParser
Style property parser.
class StylePropertySetter
Interface used by style parsers to store values in a style property set.
class StyleSetValue
Style value variable.
class StyleToken
Style token.
class StyleTokenizer
Tokenizer class that breaks text into tokens.
class System
General system helper functions.
class TargaFormat
Surface provider that can load targa (.tga) files.
class TCPConnection
TCP/IP socket connection.
class TCPListen
Listens for incoming TCP/IP socket connections.
class Text
Text string functions.
class TextAreaBaseView
class TextBlock
Span layout class.
class TextBlockBaseView
class TextFieldBaseView
class Texture
Texture object class.
class Texture1D
1D texture object class.
class Texture1DArray
1D texture array object class.
class Texture2D
2D texture object class.
class Texture2DArray
2D texture array object class.
class Texture3D
3D texture object class.
class TextureCube
2D texture cube object class.
class TextureCubeArray
2D texture cube array object class.
struct TextureFormat_GL
class TextureGroup
Dynamic atlas texture class.
class TextureGroupImage
Image position in a TextureGroup.
class TextureWindow
class Timer
Timer class that invokes a callback on a specified interval.
class TLSClient
Transport Layer Security (TLS) client class.
class TopLevelWindow
class Triangle
Triangles - Integer.
class Triangled
Triangles - Double.
class Trianglef
Triangles - Float.
class Trianglex
Triangles.
class UDPSocket
UDP/IP socket class.
class UIThread
class UniformBuffer
Uniform Buffer.
class UniformVector
Typed access to an uniform buffer.
class UTF8_Reader
UTF8 reader helper functions.
class Vec2
2D vector
class Vec2hf
2D half-float vector
class Vec3
3D vector
class Vec3hf
3D half-float vector
class Vec4
4D vector
class Vec4hf
4D half-float vector
class VertexArrayBuffer
Vertex Array Buffer.
class VertexArrayVector
Typed access to a vertex array buffer.
class View
View for an area of the user interface.
class ViewAction
Recognizes actions in a view and captures input for the duration of the action.
class ViewEventHandler
Event sink interface for view events.
class ViewGeometry
class ViewTree
Base class for managing a tree of views.
class WindowController
Base class for controllers managing windows.
class WindowManager
Manages one or more windows.
class XmlDocument
XML document tree.
class XmlNode
Tree node in a XML document.
class XmlToken
XML token in a XML file.
class XmlTokenizer
The XML Tokenizer breaks a XML file into XML tokens.
class XmlWriter
The XML Writer writes a XML file based on XML tokens.
class ZLibCompression
Deflate compressor.
Typedefs
typedef std::shared_ptr< AES128_Decrypt > AES128_DecryptPtr
typedef std::shared_ptr< AES128_Encrypt > AES128_EncryptPtr
typedef std::shared_ptr< AES192_Decrypt > AES192_DecryptPtr
typedef std::shared_ptr< AES192_Encrypt > AES192_EncryptPtr
typedef std::shared_ptr< AES256_Decrypt > AES256_DecryptPtr
typedef std::shared_ptr< AES256_Encrypt > AES256_EncryptPtr
typedef std::shared_ptr< BlendState > BlendStatePtr
typedef std::shared_ptr< Canvas > CanvasPtr
typedef void * CLDEBUGPROC
typedef void * CLDEBUGPROCARB
typedef int64_t CLint64
typedef struct __CLsync * CLsync
typedef uint64_t CLuint64
typedef ColorHSLx< double, Colorf > ColorHSLd
typedef ColorHSLx< float, Colorf > ColorHSLf
typedef ColorHSLx< int, Color > ColorHSLi
typedef ColorHSVx< double, Colorf > ColorHSVd
typedef ColorHSVx< float, Colorf > ColorHSVf
typedef ColorHSVx< int, Color > ColorHSVi
typedef std::shared_ptr< Cursor > CursorPtr
typedef std::shared_ptr< DataBuffer > DataBufferPtr
typedef std::shared_ptr< DepthStencilState > DepthStencilStatePtr
typedef std::shared_ptr< DetectHang > DetectHangPtr
typedef std::shared_ptr< DisplayWindow > DisplayWindowPtr
typedef std::shared_ptr< ElementArrayBuffer > ElementArrayBufferPtr
typedef std::shared_ptr< File > FilePtr
typedef std::shared_ptr< FontFamily > FontFamilyPtr
typedef std::shared_ptr< Font > FontPtr
typedef std::shared_ptr< FrameBuffer > FrameBufferPtr
typedef unsigned int GLbitfield
typedef unsigned char GLboolean
typedef signed char GLbyte
typedef char GLchar
typedef double GLclampd
typedef float GLclampf
typedef double GLdouble
typedef unsigned int GLenum
typedef float GLfloat
typedef int GLint
typedef ptrdiff_t GLintptr
typedef short GLshort
typedef int GLsizei
typedef ptrdiff_t GLsizeiptr
typedef unsigned char GLubyte
typedef unsigned int GLuint
typedef unsigned short GLushort
typedef void GLvoid
typedef std::shared_ptr< GraphicContext > GraphicContextPtr
typedef std::shared_ptr< IconSet > IconSetPtr
typedef std::shared_ptr< Image > ImagePtr
typedef std::shared_ptr< InputDevice > InputDevicePtr
typedef std::shared_ptr< IODevice > IODevicePtr
typedef Mat2< double > Mat2d
typedef Mat2< float > Mat2f
typedef Mat2< int > Mat2i
typedef Mat3< double > Mat3d
typedef Mat3< float > Mat3f
typedef Mat3< int > Mat3i
typedef Mat4< double > Mat4d
typedef Mat4< float > Mat4f
typedef Mat4< int > Mat4i
typedef std::shared_ptr< MD5 > MD5Ptr
typedef std::shared_ptr< MemoryDevice > MemoryDevicePtr
typedef std::shared_ptr< OcclusionQuery > OcclusionQueryPtr
typedef std::shared_ptr< Path > PathPtr
typedef std::shared_ptr< PerlinNoise > PerlinNoisePtr
typedef std::shared_ptr< PixelBuffer > PixelBufferPtr
typedef std::shared_ptr< PixelBufferSet > PixelBufferSetPtr
typedef std::shared_ptr< PixelConverter > PixelConverterPtr
typedef std::shared_ptr< PrimitivesArray > PrimitivesArrayPtr
typedef void(ProcAddress) ()
Extension procedure address typedef for OpenGL.
typedef std::shared_ptr< ProgramObject > ProgramObjectPtr
typedef Quaternionx< double > Quaterniond
typedef Quaternionx< float > Quaternionf
typedef std::shared_ptr< Random > RandomPtr
typedef std::shared_ptr< RasterizerState > RasterizerStatePtr
typedef std::shared_ptr< RegistryKey > RegistryKeyPtr
typedef std::shared_ptr< RenderBuffer > RenderBufferPtr
typedef std::shared_ptr< Secret > SecretPtr
typedef std::shared_ptr< SHA1 > SHA1Ptr
typedef std::shared_ptr< SHA224 > SHA224Ptr
typedef std::shared_ptr< SHA256 > SHA256Ptr
typedef std::shared_ptr< SHA384 > SHA384Ptr
typedef std::shared_ptr< SHA512_224 > SHA512_224Ptr
typedef std::shared_ptr< SHA512_256 > SHA512_256Ptr
typedef std::shared_ptr< SHA512 > SHA512Ptr
typedef std::shared_ptr< ShaderObject > ShaderObjectPtr
typedef std::shared_ptr< StagingBuffer > StagingBufferPtr
typedef std::shared_ptr< StagingTexture > StagingTexturePtr
typedef std::shared_ptr< StorageBuffer > StorageBufferPtr
typedef std::shared_ptr< TCPConnection > TCPConnectionPtr
typedef std::shared_ptr< TCPListen > TCPListenPtr
typedef std::shared_ptr< TextBlock > TextBlockPtr
typedef std::shared_ptr< Texture1DArray > Texture1DArrayPtr
typedef std::shared_ptr< Texture1D > Texture1DPtr
typedef std::shared_ptr< Texture2DArray > Texture2DArrayPtr
typedef std::shared_ptr< Texture2D > Texture2DPtr
typedef std::shared_ptr< Texture3D > Texture3DPtr
typedef std::shared_ptr< TextureCube > TextureCubePtr
typedef std::shared_ptr< TextureGroup > TextureGroupPtr
typedef std::shared_ptr< Texture > TexturePtr
typedef std::shared_ptr< Timer > TimerPtr
typedef std::shared_ptr< TLSClient > TLSClientPtr
typedef std::shared_ptr< UDPSocket > UDPSocketPtr
typedef std::shared_ptr< UniformBuffer > UniformBufferPtr
typedef Vec2< char > Vec2b
typedef Vec2< double > Vec2d
typedef Vec2< float > Vec2f
typedef Vec2< int > Vec2i
typedef Vec2< short > Vec2s
typedef Vec2< unsigned char > Vec2ub
typedef Vec2< unsigned int > Vec2ui
typedef Vec2< unsigned short > Vec2us
typedef Vec3< char > Vec3b
typedef Vec3< double > Vec3d
typedef Vec3< float > Vec3f
typedef Vec3< int > Vec3i
typedef Vec3< short > Vec3s
typedef Vec3< unsigned char > Vec3ub
typedef Vec3< unsigned int > Vec3ui
typedef Vec3< unsigned short > Vec3us
typedef Vec4< char > Vec4b
typedef Vec4< double > Vec4d
typedef Vec4< float > Vec4f
typedef Vec4< int > Vec4i
typedef Vec4< short > Vec4s
typedef Vec4< unsigned char > Vec4ub
typedef Vec4< unsigned int > Vec4ui
typedef Vec4< unsigned short > Vec4us
typedef std::shared_ptr< VertexArrayBuffer > VertexArrayBufferPtr
typedef std::shared_ptr< XmlDocument > XmlDocumentPtr
typedef std::shared_ptr< XmlNode > XmlNodePtr
typedef std::string XmlString
typedef std::shared_ptr< XmlTokenizer > XmlTokenizerPtr
typedef std::shared_ptr< XmlWriter > XmlWriterPtr
Enumerations
enum ActivationChangeType { ActivationChangeType::activated, ActivationChangeType::deactivated }
Window activation change.
enum BlendEquation {
equation_add, equation_subtract, equation_reverse_subtract, equation_min,
equation_max
}
Blending equations.
enum BlendFunc {
blend_zero, blend_one, blend_dest_color, blend_src_color,
blend_one_minus_dest_color, blend_one_minus_src_color, blend_src_alpha, blend_one_minus_src_alpha,
blend_dest_alpha, blend_one_minus_dest_alpha, blend_src_alpha_saturate, blend_constant_color,
blend_one_minus_constant_color, blend_constant_alpha, blend_one_minus_constant_alpha
}
Blending functions.
enum BrushInterpolateMode { BrushInterpolateMode::nearest, BrushInterpolateMode::linear }
enum BrushType { BrushType::solid, BrushType::linear, BrushType::radial, BrushType::image }
enum BrushWrapMode { BrushWrapMode::clamp, BrushWrapMode::wrap, BrushWrapMode::mirror }
enum BufferAccess { access_read_only, access_write_only, access_read_write, access_write_discard }
Array Buffer access enum.
enum BufferUsage {
usage_stream_draw, usage_stream_read, usage_stream_copy, usage_static_draw,
usage_static_read, usage_static_copy, usage_dynamic_draw, usage_dynamic_read,
usage_dynamic_copy
}
Array Buffer usage enum.
enum ByteOrderMark {
ByteOrderMark::none, ByteOrderMark::utf32_be, ByteOrderMark::utf32_le, ByteOrderMark::utf16_be,
ByteOrderMark::utf16_le, ByteOrderMark::utf8
}
Unicode byte order mark (BOM) types.
enum ClipZRange { clip_negative_positive_w, clip_zero_positive_w }
enum CompareFunction {
compare_lequal, compare_gequal, compare_less, compare_greater,
compare_equal, compare_notequal, compare_always, compare_never
}
Compare functions.
enum ContentOverflow { ContentOverflow::hidden, ContentOverflow::scroll, ContentOverflow::automatic }
enum CullMode { cull_front, cull_back, cull_front_and_back }
Polygon culling modes.
enum DisplayDefines {
GL_DEPTH_BUFFER_BIT = 0x00000100, GL_STENCIL_BUFFER_BIT = 0x00000400, GL_COLOR_BUFFER_BIT = 0x00004000, GL_FALSE = 0,
GL_TRUE = 1, GL_POINTS = 0x0000, GL_LINES = 0x0001, GL_LINE_LOOP = 0x0002,
GL_LINE_STRIP = 0x0003, GL_TRIANGLES = 0x0004, GL_TRIANGLE_STRIP = 0x0005, GL_TRIANGLE_FAN = 0x0006,
GL_NEVER = 0x0200, GL_LESS = 0x0201, GL_EQUAL = 0x0202, GL_LEQUAL = 0x0203,
GL_GREATER = 0x0204, GL_NOTEQUAL = 0x0205, GL_GEQUAL = 0x0206, GL_ALWAYS = 0x0207,
GL_ZERO = 0, GL_ONE = 1, GL_SRC_COLOR = 0x0300, GL_ONE_MINUS_SRC_COLOR = 0x0301,
GL_SRC_ALPHA = 0x0302, GL_ONE_MINUS_SRC_ALPHA = 0x0303, GL_DST_ALPHA = 0x0304, GL_ONE_MINUS_DST_ALPHA = 0x0305,
GL_DST_COLOR = 0x0306, GL_ONE_MINUS_DST_COLOR = 0x0307, GL_SRC_ALPHA_SATURATE = 0x0308, GL_NONE = 0,
GL_FRONT_LEFT = 0x0400, GL_FRONT_RIGHT = 0x0401, GL_BACK_LEFT = 0x0402, GL_BACK_RIGHT = 0x0403,
GL_FRONT = 0x0404, GL_BACK = 0x0405, GL_LEFT = 0x0406, GL_RIGHT = 0x0407,
GL_FRONT_AND_BACK = 0x0408, GL_NO_ERROR = 0, GL_INVALID_ENUM = 0x0500, GL_INVALID_VALUE = 0x0501,
GL_INVALID_OPERATION = 0x0502, GL_OUT_OF_MEMORY = 0x0505, GL_CW = 0x0900, GL_CCW = 0x0901,
GL_POINT_SIZE = 0x0B11, GL_POINT_SIZE_RANGE = 0x0B12, GL_POINT_SIZE_GRANULARITY = 0x0B13, GL_LINE_SMOOTH = 0x0B20,
GL_LINE_WIDTH = 0x0B21, GL_LINE_WIDTH_RANGE = 0x0B22, GL_LINE_WIDTH_GRANULARITY = 0x0B23, GL_POLYGON_SMOOTH = 0x0B41,
GL_CULL_FACE = 0x0B44, GL_CULL_FACE_MODE = 0x0B45, GL_FRONT_FACE = 0x0B46, GL_DEPTH_RANGE = 0x0B70,
GL_DEPTH_TEST = 0x0B71, GL_DEPTH_WRITEMASK = 0x0B72, GL_DEPTH_CLEAR_VALUE = 0x0B73, GL_DEPTH_FUNC = 0x0B74,
GL_STENCIL_TEST = 0x0B90, GL_STENCIL_CLEAR_VALUE = 0x0B91, GL_STENCIL_FUNC = 0x0B92, GL_STENCIL_VALUE_MASK = 0x0B93,
GL_STENCIL_FAIL = 0x0B94, GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95, GL_STENCIL_PASS_DEPTH_PASS = 0x0B96, GL_STENCIL_REF = 0x0B97,
GL_STENCIL_WRITEMASK = 0x0B98, GL_VIEWPORT = 0x0BA2, GL_DITHER = 0x0BD0, GL_BLEND_DST = 0x0BE0,
GL_BLEND_SRC = 0x0BE1, GL_BLEND = 0x0BE2, GL_LOGIC_OP_MODE = 0x0BF0, GL_COLOR_LOGIC_OP = 0x0BF2,
GL_DRAW_BUFFER = 0x0C01, GL_READ_BUFFER = 0x0C02, GL_SCISSOR_BOX = 0x0C10, GL_SCISSOR_TEST = 0x0C11,
GL_COLOR_CLEAR_VALUE = 0x0C22, GL_COLOR_WRITEMASK = 0x0C23, GL_DOUBLEBUFFER = 0x0C32, GL_STEREO = 0x0C33,
GL_LINE_SMOOTH_HINT = 0x0C52, GL_POLYGON_SMOOTH_HINT = 0x0C53, GL_UNPACK_SWAP_BYTES = 0x0CF0, GL_UNPACK_LSB_FIRST = 0x0CF1,
GL_UNPACK_ROW_LENGTH = 0x0CF2, GL_UNPACK_SKIP_ROWS = 0x0CF3, GL_UNPACK_SKIP_PIXELS = 0x0CF4, GL_UNPACK_ALIGNMENT = 0x0CF5,
GL_PACK_SWAP_BYTES = 0x0D00, GL_PACK_LSB_FIRST = 0x0D01, GL_PACK_ROW_LENGTH = 0x0D02, GL_PACK_SKIP_ROWS = 0x0D03,
GL_PACK_SKIP_PIXELS = 0x0D04, GL_PACK_ALIGNMENT = 0x0D05, GL_MAX_TEXTURE_SIZE = 0x0D33, GL_MAX_VIEWPORT_DIMS = 0x0D3A,
GL_SUBCL_PIXEL_BITS = 0x0D50, GL_TEXTURE_1D = 0x0DE0, GL_TEXTURE_2D = 0x0DE1, GL_POLYGON_OFFSET_UNITS = 0x2A00,
GL_POLYGON_OFFSET_POINT = 0x2A01, GL_POLYGON_OFFSET_LINE = 0x2A02, GL_POLYGON_OFFSET_FILL = 0x8037, GL_POLYGON_OFFSET_FACTOR = 0x8038,
GL_TEXTURE_BINDING_1D = 0x8068, GL_TEXTURE_BINDING_2D = 0x8069, GL_TEXTURE_WIDTH = 0x1000, GL_TEXTURE_HEIGHT = 0x1001,
GL_TEXTURE_INTERNAL_FORMAT = 0x1003, GL_TEXTURE_BORDER_COLOR = 0x1004, GL_TEXTURE_RED_SIZE = 0x805C, GL_TEXTURE_GREEN_SIZE = 0x805D,
GL_TEXTURE_BLUE_SIZE = 0x805E, GL_TEXTURE_ALPHA_SIZE = 0x805F, GL_DONT_CARE = 0x1100, GL_FASTEST = 0x1101,
GL_NICEST = 0x1102, GL_BYTE = 0x1400, GL_UNSIGNED_BYTE = 0x1401, GL_SHORT = 0x1402,
GL_UNSIGNED_SHORT = 0x1403, GL_INT = 0x1404, GL_UNSIGNED_INT = 0x1405, GL_FLOAT = 0x1406,
GL_DOUBLE = 0x140A, GL_STACK_OVERFLOW = 0x0503, GL_STACK_UNDERFLOW = 0x0504, GL_CLEAR = 0x1500,
GL_AND = 0x1501, GL_AND_REVERSE = 0x1502, GL_COPY = 0x1503, GL_AND_INVERTED = 0x1504,
GL_NOOP = 0x1505, GL_XOR = 0x1506, GL_OR = 0x1507, GL_NOR = 0x1508,
GL_EQUIV = 0x1509, GL_INVERT = 0x150A, GL_OR_REVERSE = 0x150B, GL_COPY_INVERTED = 0x150C,
GL_OR_INVERTED = 0x150D, GL_NAND = 0x150E, GL_SET = 0x150F, GL_TEXTURE = 0x1702,
GL_COLOR = 0x1800, GL_DEPTH = 0x1801, GL_STENCIL = 0x1802, GL_STENCIL_INDEX = 0x1901,
GL_DEPTH_COMPONENT = 0x1902, GL_RED = 0x1903, GL_GREEN = 0x1904, GL_BLUE = 0x1905,
GL_ALPHA = 0x1906, GL_RGB = 0x1907, GL_RGBA = 0x1908, GL_POINT = 0x1B00,
GL_LINE = 0x1B01, GL_FILL = 0x1B02, GL_KEEP = 0x1E00, GL_REPLACE = 0x1E01,
GL_INCR = 0x1E02, GL_DECR = 0x1E03, GL_VENDOR = 0x1F00, GL_RENDERER = 0x1F01,
GL_VERSION = 0x1F02, GL_EXTENSIONS = 0x1F03, GL_NEAREST = 0x2600, GL_LINEAR = 0x2601,
GL_NEAREST_MIPMAP_NEAREST = 0x2700, GL_LINEAR_MIPMAP_NEAREST = 0x2701, GL_NEAREST_MIPMAP_LINEAR = 0x2702, GL_LINEAR_MIPMAP_LINEAR = 0x2703,
GL_TEXTURE_MAG_FILTER = 0x2800, GL_TEXTURE_MIN_FILTER = 0x2801, GL_TEXTURE_WRAP_S = 0x2802, GL_TEXTURE_WRAP_T = 0x2803,
GL_PROXY_TEXTURE_1D = 0x8063, GL_PROXY_TEXTURE_2D = 0x8064, GL_REPEAT = 0x2901, GL_R3_G3_B2 = 0x2A10,
GL_RGB4 = 0x804F, GL_RGB5 = 0x8050, GL_RGB8 = 0x8051, GL_RGB10 = 0x8052,
GL_RGB12 = 0x8053, GL_RGB16 = 0x8054, GL_RGBA2 = 0x8055, GL_RGBA4 = 0x8056,
GL_RGB5_A1 = 0x8057, GL_RGBA8 = 0x8058, GL_RGB10_A2 = 0x8059, GL_RGBA12 = 0x805A,
GL_RGBA16 = 0x805B, GL_UNSIGNED_BYTE_3_3_2 = 0x8032, GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033, GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034,
GL_UNSIGNED_INT_8_8_8_8 = 0x8035, GL_UNSIGNED_INT_10_10_10_2 = 0x8036, GL_TEXTURE_BINDING_3D = 0x806A, GL_PACK_SKIP_IMAGES = 0x806B,
GL_PACK_IMAGE_HEIGHT = 0x806C, GL_UNPACK_SKIP_IMAGES = 0x806D, GL_UNPACK_IMAGE_HEIGHT = 0x806E, GL_TEXTURE_3D = 0x806F,
GL_PROXY_TEXTURE_3D = 0x8070, GL_TEXTURE_DEPTH = 0x8071, GL_TEXTURE_WRAP_R = 0x8072, GL_MAX_3D_TEXTURE_SIZE = 0x8073,
GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362, GL_UNSIGNED_SHORT_5_6_5 = 0x8363, GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364, GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365,
GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366, GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367, GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368, GL_BGR = 0x80E0,
GL_BGRA = 0x80E1, GL_MAX_ELEMENTS_VERTICES = 0x80E8, GL_MAX_ELEMENTS_INDICES = 0x80E9, GL_CLAMP_TO_EDGE = 0x812F,
GL_TEXTURE_MIN_LOD = 0x813A, GL_TEXTURE_MAX_LOD = 0x813B, GL_TEXTURE_BASE_LEVEL = 0x813C, GL_TEXTURE_MAX_LEVEL = 0x813D,
GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12, GL_SMOOTH_POINT_SIZE_GRANULARITY = 0x0B13, GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22, GL_SMOOTH_LINE_WIDTH_GRANULARITY = 0x0B23,
GL_ALIASED_LINE_WIDTH_RANGE = 0x846E, GL_CONSTANT_COLOR = 0x8001, GL_ONE_MINUS_CONSTANT_COLOR = 0x8002, GL_CONSTANT_ALPHA = 0x8003,
GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004, GL_BLEND_COLOR = 0x8005, GL_FUNC_ADD = 0x8006, GL_MIN = 0x8007,
GL_MAX = 0x8008, GL_BLEND_EQUATION = 0x8009, GL_FUNC_SUBTRACT = 0x800A, GL_FUNC_REVERSE_SUBTRACT = 0x800B,
GL_TEXTURE0 = 0x84C0, GL_TEXTURE1 = 0x84C1, GL_TEXTURE2 = 0x84C2, GL_TEXTURE3 = 0x84C3,
GL_TEXTURE4 = 0x84C4, GL_TEXTURE5 = 0x84C5, GL_TEXTURE6 = 0x84C6, GL_TEXTURE7 = 0x84C7,
GL_TEXTURE8 = 0x84C8, GL_TEXTURE9 = 0x84C9, GL_TEXTURE10 = 0x84CA, GL_TEXTURE11 = 0x84CB,
GL_TEXTURE12 = 0x84CC, GL_TEXTURE13 = 0x84CD, GL_TEXTURE14 = 0x84CE, GL_TEXTURE15 = 0x84CF,
GL_TEXTURE16 = 0x84D0, GL_TEXTURE17 = 0x84D1, GL_TEXTURE18 = 0x84D2, GL_TEXTURE19 = 0x84D3,
GL_TEXTURE20 = 0x84D4, GL_TEXTURE21 = 0x84D5, GL_TEXTURE22 = 0x84D6, GL_TEXTURE23 = 0x84D7,
GL_TEXTURE24 = 0x84D8, GL_TEXTURE25 = 0x84D9, GL_TEXTURE26 = 0x84DA, GL_TEXTURE27 = 0x84DB,
GL_TEXTURE28 = 0x84DC, GL_TEXTURE29 = 0x84DD, GL_TEXTURE30 = 0x84DE, GL_TEXTURE31 = 0x84DF,
GL_ACTIVE_TEXTURE = 0x84E0, GL_MULTISAMPLE = 0x809D, GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E, GL_SAMPLE_ALPHA_TO_ONE = 0x809F,
GL_SAMPLE_COVERAGE = 0x80A0, GL_SAMPLE_BUFFERS = 0x80A8, GL_SAMPLES = 0x80A9, GL_SAMPLE_COVERAGE_VALUE = 0x80AA,
GL_SAMPLE_COVERAGE_INVERT = 0x80AB, GL_TEXTURE_CUBE_MAP = 0x8513, GL_TEXTURE_BINDING_CUBE_MAP = 0x8514, GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515,
GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516, GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517, GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518, GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519,
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A, GL_PROXY_TEXTURE_CUBE_MAP = 0x851B, GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C, GL_COMPRESSED_RGB = 0x84ED,
GL_COMPRESSED_RGBA = 0x84EE, GL_TEXTURE_COMPRESSION_HINT = 0x84EF, GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0, GL_TEXTURE_COMPRESSED = 0x86A1,
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2, GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3, GL_CLAMP_TO_BORDER = 0x812D, GL_BLEND_DST_RGB = 0x80C8,
GL_BLEND_SRC_RGB = 0x80C9, GL_BLEND_DST_ALPHA = 0x80CA, GL_BLEND_SRC_ALPHA = 0x80CB, GL_POINT_FADE_THRESHOLD_SIZE = 0x8128,
GL_DEPTH_COMPONENT16 = 0x81A5, GL_DEPTH_COMPONENT24 = 0x81A6, GL_DEPTH_COMPONENT32 = 0x81A7, GL_MIRRORED_REPEAT = 0x8370,
GL_MAX_TEXTURE_LOD_BIAS = 0x84FD, GL_TEXTURE_LOD_BIAS = 0x8501, GL_INCR_WRAP = 0x8507, GL_DECR_WRAP = 0x8508,
GL_TEXTURE_DEPTH_SIZE = 0x884A, GL_TEXTURE_COMPARE_MODE = 0x884C, GL_TEXTURE_COMPARE_FUNC = 0x884D, GL_BUFFER_SIZE = 0x8764,
GL_BUFFER_USAGE = 0x8765, GL_QUERY_COUNTER_BITS = 0x8864, GL_CURRENT_QUERY = 0x8865, GL_QUERY_RESULT = 0x8866,
GL_QUERY_RESULT_AVAILABLE = 0x8867, GL_ARRAY_BUFFER = 0x8892, GL_ELEMENT_ARRAY_BUFFER = 0x8893, GL_ARRAY_BUFFER_BINDING = 0x8894,
GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895, GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F, GL_READ_ONLY = 0x88B8, GL_WRITE_ONLY = 0x88B9,
GL_READ_WRITE = 0x88BA, GL_BUFFER_ACCESS = 0x88BB, GL_BUFFER_MAPPED = 0x88BC, GL_BUFFER_MAP_POINTER = 0x88BD,
GL_STREAM_DRAW = 0x88E0, GL_STREAM_READ = 0x88E1, GL_STREAM_COPY = 0x88E2, GL_STATIC_DRAW = 0x88E4,
GL_STATIC_READ = 0x88E5, GL_STATIC_COPY = 0x88E6, GL_DYNAMIC_DRAW = 0x88E8, GL_DYNAMIC_READ = 0x88E9,
GL_DYNAMIC_COPY = 0x88EA, GL_SAMPLES_PASSED = 0x8914, GL_BLEND_EQUATION_RGB = 0x8009, GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622,
GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623, GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624, GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625, GL_CURRENT_VERTEX_ATTRIB = 0x8626,
GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642, GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645, GL_STENCIL_BACK_FUNC = 0x8800, GL_STENCIL_BACK_FAIL = 0x8801,
GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802, GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803, GL_MAX_DRAW_BUFFERS = 0x8824, GL_DRAW_BUFFER0 = 0x8825,
GL_DRAW_BUFFER1 = 0x8826, GL_DRAW_BUFFER2 = 0x8827, GL_DRAW_BUFFER3 = 0x8828, GL_DRAW_BUFFER4 = 0x8829,
GL_DRAW_BUFFER5 = 0x882A, GL_DRAW_BUFFER6 = 0x882B, GL_DRAW_BUFFER7 = 0x882C, GL_DRAW_BUFFER8 = 0x882D,
GL_DRAW_BUFFER9 = 0x882E, GL_DRAW_BUFFER10 = 0x882F, GL_DRAW_BUFFER11 = 0x8830, GL_DRAW_BUFFER12 = 0x8831,
GL_DRAW_BUFFER13 = 0x8832, GL_DRAW_BUFFER14 = 0x8833, GL_DRAW_BUFFER15 = 0x8834, GL_BLEND_EQUATION_ALPHA = 0x883D,
GL_MAX_VERTEX_ATTRIBS = 0x8869, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A, GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872, GL_FRAGMENT_SHADER = 0x8B30,
GL_VERTEX_SHADER = 0x8B31, GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49, GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A, GL_MAX_VARYING_FLOATS = 0x8B4B,
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C, GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D, GL_SHADER_TYPE = 0x8B4F, GL_FLOAT_VEC2 = 0x8B50,
GL_FLOAT_VEC3 = 0x8B51, GL_FLOAT_VEC4 = 0x8B52, GL_INT_VEC2 = 0x8B53, GL_INT_VEC3 = 0x8B54,
GL_INT_VEC4 = 0x8B55, GL_BOOL = 0x8B56, GL_BOOL_VEC2 = 0x8B57, GL_BOOL_VEC3 = 0x8B58,
GL_BOOL_VEC4 = 0x8B59, GL_FLOAT_MAT2 = 0x8B5A, GL_FLOAT_MAT3 = 0x8B5B, GL_FLOAT_MAT4 = 0x8B5C,
GL_SAMPLER_1D = 0x8B5D, GL_SAMPLER_2D = 0x8B5E, GL_SAMPLER_3D = 0x8B5F, GL_SAMPLER_CUBE = 0x8B60,
GL_SAMPLER_1D_SHADOW = 0x8B61, GL_SAMPLER_2D_SHADOW = 0x8B62, GL_DELETE_STATUS = 0x8B80, GL_COMPILE_STATUS = 0x8B81,
GL_LINK_STATUS = 0x8B82, GL_VALIDATE_STATUS = 0x8B83, GL_INFO_LOG_LENGTH = 0x8B84, GL_ATTACHED_SHADERS = 0x8B85,
GL_ACTIVE_UNIFORMS = 0x8B86, GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87, GL_SHADER_SOURCE_LENGTH = 0x8B88, GL_ACTIVE_ATTRIBUTES = 0x8B89,
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A, GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B, GL_SHADING_LANGUAGE_VERSION = 0x8B8C, GL_CURRENT_PROGRAM = 0x8B8D,
GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0, GL_LOWER_LEFT = 0x8CA1, GL_UPPER_LEFT = 0x8CA2, GL_STENCIL_BACK_REF = 0x8CA3,
GL_STENCIL_BACK_VALUE_MASK = 0x8CA4, GL_STENCIL_BACK_WRITEMASK = 0x8CA5, GL_PIXEL_PACK_BUFFER = 0x88EB, GL_PIXEL_UNPACK_BUFFER = 0x88EC,
GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED, GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF, GL_FLOAT_MAT2x3 = 0x8B65, GL_FLOAT_MAT2x4 = 0x8B66,
GL_FLOAT_MAT3x2 = 0x8B67, GL_FLOAT_MAT3x4 = 0x8B68, GL_FLOAT_MAT4x2 = 0x8B69, GL_FLOAT_MAT4x3 = 0x8B6A,
GL_SRGB = 0x8C40, GL_SRGB8 = 0x8C41, GL_SRGB_ALPHA = 0x8C42, GL_SRGB8_ALPHA8 = 0x8C43,
GL_COMPRESSED_SRGB = 0x8C48, GL_COMPRESSED_SRGB_ALPHA = 0x8C49, GL_COMPARE_REF_TO_TEXTURE = 0x884E, GL_CLIP_DISTANCE0 = 0x3000,
GL_CLIP_DISTANCE1 = 0x3001, GL_CLIP_DISTANCE2 = 0x3002, GL_CLIP_DISTANCE3 = 0x3003, GL_CLIP_DISTANCE4 = 0x3004,
GL_CLIP_DISTANCE5 = 0x3005, GL_CLIP_DISTANCE6 = 0x3006, GL_CLIP_DISTANCE7 = 0x3007, GL_MAX_CLIP_DISTANCES = 0x0D32,
GL_MAJOR_VERSION = 0x821B, GL_MINOR_VERSION = 0x821C, GL_NUM_EXTENSIONS = 0x821D, GL_CONTEXT_FLAGS = 0x821E,
GL_COMPRESSED_RED = 0x8225, GL_COMPRESSED_RG = 0x8226, GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x0001, GL_RGBA32F = 0x8814,
GL_RGB32F = 0x8815, GL_RGBA16F = 0x881A, GL_RGB16F = 0x881B, GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD,
GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF, GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904, GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905, GL_CLAMP_READ_COLOR = 0x891C,
GL_FIXED_ONLY = 0x891D, GL_MAX_VARYING_COMPONENTS = 0x8B4B, GL_TEXTURE_1D_ARRAY = 0x8C18, GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19,
GL_TEXTURE_2D_ARRAY = 0x8C1A, GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B, GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C, GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D,
GL_R11F_G11F_B10F = 0x8C3A, GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B, GL_RGB9_E5 = 0x8C3D, GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E,
GL_TEXTURE_SHARED_SIZE = 0x8C3F, GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76, GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F, GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80,
GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83, GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84, GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85, GL_PRIMITIVES_GENERATED = 0x8C87,
GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88, GL_RASTERIZER_DISCARD = 0x8C89, GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A, GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B,
GL_INTERLEAVED_ATTRIBS = 0x8C8C, GL_SEPARATE_ATTRIBS = 0x8C8D, GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E, GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F,
GL_RGBA32UI = 0x8D70, GL_RGB32UI = 0x8D71, GL_RGBA16UI = 0x8D76, GL_RGB16UI = 0x8D77,
GL_RGBA8UI = 0x8D7C, GL_RGB8UI = 0x8D7D, GL_RGBA32I = 0x8D82, GL_RGB32I = 0x8D83,
GL_RGBA16I = 0x8D88, GL_RGB16I = 0x8D89, GL_RGBA8I = 0x8D8E, GL_RGB8I = 0x8D8F,
GL_RED_INTEGER = 0x8D94, GL_GREEN_INTEGER = 0x8D95, GL_BLUE_INTEGER = 0x8D96, GL_RGB_INTEGER = 0x8D98,
GL_RGBA_INTEGER = 0x8D99, GL_BGR_INTEGER = 0x8D9A, GL_BGRA_INTEGER = 0x8D9B, GL_SAMPLER_1D_ARRAY = 0x8DC0,
GL_SAMPLER_2D_ARRAY = 0x8DC1, GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3, GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4, GL_SAMPLER_CUBE_SHADOW = 0x8DC5,
GL_UNSIGNED_INT_VEC2 = 0x8DC6, GL_UNSIGNED_INT_VEC3 = 0x8DC7, GL_UNSIGNED_INT_VEC4 = 0x8DC8, GL_INT_SAMPLER_1D = 0x8DC9,
GL_INT_SAMPLER_2D = 0x8DCA, GL_INT_SAMPLER_3D = 0x8DCB, GL_INT_SAMPLER_CUBE = 0x8DCC, GL_INT_SAMPLER_1D_ARRAY = 0x8DCE,
GL_INT_SAMPLER_2D_ARRAY = 0x8DCF, GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1, GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2, GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3,
GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4, GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6, GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7, GL_QUERY_WAIT = 0x8E13,
GL_QUERY_NO_WAIT = 0x8E14, GL_QUERY_BY_REGION_WAIT = 0x8E15, GL_QUERY_BY_REGION_NO_WAIT = 0x8E16, GL_BUFFER_ACCESS_FLAGS = 0x911F,
GL_BUFFER_MAP_LENGTH = 0x9120, GL_BUFFER_MAP_OFFSET = 0x9121, GL_SAMPLER_2D_RECT = 0x8B63, GL_SAMPLER_2D_RECT_SHADOW = 0x8B64,
GL_SAMPLER_BUFFER = 0x8DC2, GL_INT_SAMPLER_2D_RECT = 0x8DCD, GL_INT_SAMPLER_BUFFER = 0x8DD0, GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5,
GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8, GL_TEXTURE_BUFFER = 0x8C2A, GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B, GL_TEXTURE_BINDING_BUFFER = 0x8C2C,
GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D, GL_TEXTURE_BUFFER_FORMAT = 0x8C2E, GL_TEXTURE_RECTANGLE = 0x84F5, GL_TEXTURE_BINDING_RECTANGLE = 0x84F6,
GL_PROXY_TEXTURE_RECTANGLE = 0x84F7, GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8, GL_RED_SNORM = 0x8F90, GL_RG_SNORM = 0x8F91,
GL_RGB_SNORM = 0x8F92, GL_RGBA_SNORM = 0x8F93, GL_R8_SNORM = 0x8F94, GL_RG8_SNORM = 0x8F95,
GL_RGB8_SNORM = 0x8F96, GL_RGBA8_SNORM = 0x8F97, GL_R16_SNORM = 0x8F98, GL_RG16_SNORM = 0x8F99,
GL_RGB16_SNORM = 0x8F9A, GL_RGBA16_SNORM = 0x8F9B, GL_SIGNED_NORMALIZED = 0x8F9C, GL_PRIMITIVE_RESTART = 0x8F9D,
GL_PRIMITIVE_RESTART_INDEX = 0x8F9E, GL_CONTEXT_CORE_PROFILE_BIT = 0x00000001, GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 0x00000002, GL_LINES_ADJACENCY = 0x000A,
GL_LINE_STRIP_ADJACENCY = 0x000B, GL_TRIANGLES_ADJACENCY = 0x000C, GL_TRIANGLE_STRIP_ADJACENCY = 0x000D, GL_PROGRAM_POINT_SIZE = 0x8642,
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29, GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7, GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8, GL_GEOMETRY_SHADER = 0x8DD9,
GL_GEOMETRY_VERTICES_OUT = 0x8916, GL_GEOMETRY_INPUT_TYPE = 0x8917, GL_GEOMETRY_OUTPUT_TYPE = 0x8918, GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDF,
GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0, GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1, GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122, GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123,
GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124, GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125, GL_CONTEXT_PROFILE_MASK = 0x9126, GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE,
GL_SAMPLE_SHADING = 0x8C36, GL_MIN_SAMPLE_SHADING_VALUE = 0x8C37, GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E, GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F,
GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009, GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x900A, GL_PROXY_TEXTURE_CUBE_MAP_ARRAY = 0x900B, GL_SAMPLER_CUBE_MAP_ARRAY = 0x900C,
GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW = 0x900D, GL_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900E, GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900F, GL_NUM_SHADING_LANGUAGE_VERSIONS = 0x82E9,
GL_VERTEX_ATTRIB_ARRAY_LONG = 0x874E, GL_DEPTH_COMPONENT32F = 0x8CAC, GL_DEPTH32F_STENCIL8 = 0x8CAD, GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD,
GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506, GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210, GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211, GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212,
GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213, GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214, GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215, GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216,
GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217, GL_FRAMEBUFFER_DEFAULT = 0x8218, GL_FRAMEBUFFER_UNDEFINED = 0x8219, GL_DEPTH_STENCIL_ATTACHMENT = 0x821A,
GL_MAX_RENDERBUFFER_SIZE = 0x84E8, GL_DEPTH_STENCIL = 0x84F9, GL_UNSIGNED_INT_24_8 = 0x84FA, GL_DEPTH24_STENCIL8 = 0x88F0,
GL_TEXTURE_STENCIL_SIZE = 0x88F1, GL_TEXTURE_RED_TYPE = 0x8C10, GL_TEXTURE_GREEN_TYPE = 0x8C11, GL_TEXTURE_BLUE_TYPE = 0x8C12,
GL_TEXTURE_ALPHA_TYPE = 0x8C13, GL_TEXTURE_DEPTH_TYPE = 0x8C16, GL_UNSIGNED_NORMALIZED = 0x8C17, GL_FRAMEBUFFER_BINDING = 0x8CA6,
GL_DRAW_FRAMEBUFFER_BINDING = GL_FRAMEBUFFER_BINDING, GL_RENDERBUFFER_BINDING = 0x8CA7, GL_READ_FRAMEBUFFER = 0x8CA8, GL_DRAW_FRAMEBUFFER = 0x8CA9,
GL_READ_FRAMEBUFFER_BINDING = 0x8CAA, GL_RENDERBUFFER_SAMPLES = 0x8CAB, GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0, GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1,
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2, GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3, GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4, GL_FRAMEBUFFER_COMPLETE = 0x8CD5,
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6, GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7, GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB, GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC,
GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD, GL_MAX_COLOR_ATTACHMENTS = 0x8CDF, GL_COLOR_ATTACHMENT0 = 0x8CE0, GL_COLOR_ATTACHMENT1 = 0x8CE1,
GL_COLOR_ATTACHMENT2 = 0x8CE2, GL_COLOR_ATTACHMENT3 = 0x8CE3, GL_COLOR_ATTACHMENT4 = 0x8CE4, GL_COLOR_ATTACHMENT5 = 0x8CE5,
GL_COLOR_ATTACHMENT6 = 0x8CE6, GL_COLOR_ATTACHMENT7 = 0x8CE7, GL_COLOR_ATTACHMENT8 = 0x8CE8, GL_COLOR_ATTACHMENT9 = 0x8CE9,
GL_COLOR_ATTACHMENT10 = 0x8CEA, GL_COLOR_ATTACHMENT11 = 0x8CEB, GL_COLOR_ATTACHMENT12 = 0x8CEC, GL_COLOR_ATTACHMENT13 = 0x8CED,
GL_COLOR_ATTACHMENT14 = 0x8CEE, GL_COLOR_ATTACHMENT15 = 0x8CEF, GL_DEPTH_ATTACHMENT = 0x8D00, GL_STENCIL_ATTACHMENT = 0x8D20,
GL_FRAMEBUFFER = 0x8D40, GL_RENDERBUFFER = 0x8D41, GL_RENDERBUFFER_WIDTH = 0x8D42, GL_RENDERBUFFER_HEIGHT = 0x8D43,
GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44, GL_STENCIL_INDEX1 = 0x8D46, GL_STENCIL_INDEX4 = 0x8D47, GL_STENCIL_INDEX8 = 0x8D48,
GL_STENCIL_INDEX16 = 0x8D49, GL_RENDERBUFFER_RED_SIZE = 0x8D50, GL_RENDERBUFFER_GREEN_SIZE = 0x8D51, GL_RENDERBUFFER_BLUE_SIZE = 0x8D52,
GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53, GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54, GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55, GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56,
GL_MAX_SAMPLES = 0x8D57, GL_FRAMEBUFFER_SRGB = 0x8DB9, GL_HALF_FLOAT = 0x140B, GL_MAP_READ_BIT = 0x0001,
GL_MAP_WRITE_BIT = 0x0002, GL_MAP_INVALIDATE_RANGE_BIT = 0x0004, GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008, GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010,
GL_MAP_UNSYNCHRONIZED_BIT = 0x0020, GL_COMPRESSED_RED_RGTC1 = 0x8DBB, GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC, GL_COMPRESSED_RG_RGTC2 = 0x8DBD,
GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE, GL_RG = 0x8227, GL_RG_INTEGER = 0x8228, GL_R8 = 0x8229,
GL_R16 = 0x822A, GL_RG8 = 0x822B, GL_RG16 = 0x822C, GL_R16F = 0x822D,
GL_R32F = 0x822E, GL_RG16F = 0x822F, GL_RG32F = 0x8230, GL_R8I = 0x8231,
GL_R8UI = 0x8232, GL_R16I = 0x8233, GL_R16UI = 0x8234, GL_R32I = 0x8235,
GL_R32UI = 0x8236, GL_RG8I = 0x8237, GL_RG8UI = 0x8238, GL_RG16I = 0x8239,
GL_RG16UI = 0x823A, GL_RG32I = 0x823B, GL_RG32UI = 0x823C, GL_VERTEX_ARRAY_BINDING = 0x85B5,
GL_UNIFORM_BUFFER = 0x8A11, GL_UNIFORM_BUFFER_BINDING = 0x8A28, GL_UNIFORM_BUFFER_START = 0x8A29, GL_UNIFORM_BUFFER_SIZE = 0x8A2A,
GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B, GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C, GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D, GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E,
GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F, GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30, GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31, GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32,
GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33, GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34, GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35, GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36,
GL_UNIFORM_TYPE = 0x8A37, GL_UNIFORM_SIZE = 0x8A38, GL_UNIFORM_NAME_LENGTH = 0x8A39, GL_UNIFORM_BLOCK_INDEX = 0x8A3A,
GL_UNIFORM_OFFSET = 0x8A3B, GL_UNIFORM_ARRAY_STRIDE = 0x8A3C, GL_UNIFORM_MATRIX_STRIDE = 0x8A3D, GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E,
GL_UNIFORM_BLOCK_BINDING = 0x8A3F, GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40, GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41, GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42,
GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43, GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44, GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45, GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46,
GL_INVALID_INDEX = 0xFFFFFFFFu, GL_COPY_READ_BUFFER_BINDING = 0x8F36, GL_COPY_READ_BUFFER = GL_COPY_READ_BUFFER_BINDING, GL_COPY_WRITE_BUFFER_BINDING = 0x8F37,
GL_COPY_WRITE_BUFFER = GL_COPY_WRITE_BUFFER_BINDING, GL_DEPTH_CLAMP = 0x864F, GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = 0x8E4C, GL_FIRST_VERTEX_CONVENTION = 0x8E4D,
GL_LAST_VERTEX_CONVENTION = 0x8E4E, GL_PROVOKING_VERTEX = 0x8E4F, GL_TEXTURE_CUBE_MAP_SEAMLESS = 0x884F, GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111,
GL_OBJECT_TYPE = 0x9112, GL_SYNC_CONDITION = 0x9113, GL_SYNC_STATUS = 0x9114, GL_SYNC_FLAGS = 0x9115,
GL_SYNC_FENCE = 0x9116, GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117, GL_UNSIGNALED = 0x9118, GL_SIGNALED = 0x9119,
GL_ALREADY_SIGNALED = 0x911A, GL_TIMEOUT_EXCL_PIRED = 0x911B, GL_CONDITION_SATISFIED = 0x911C, GL_WAIT_FAILED = 0x911D,
GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001, GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFFull, GL_SAMPLE_POSITION = 0x8E50, GL_SAMPLE_MASK = 0x8E51,
GL_SAMPLE_MASK_VALUE = 0x8E52, GL_MAX_SAMPLE_MASK_WORDS = 0x8E59, GL_TEXTURE_2D_MULTISAMPLE = 0x9100, GL_PROXY_TEXTURE_2D_MULTISAMPLE = 0x9101,
GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102, GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9103, GL_TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104, GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 0x9105,
GL_TEXTURE_SAMPLES = 0x9106, GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107, GL_SAMPLER_2D_MULTISAMPLE = 0x9108, GL_INT_SAMPLER_2D_MULTISAMPLE = 0x9109,
GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 0x910A, GL_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910B, GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910C, GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910D,
GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910E, GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910F, GL_MAX_INTEGER_SAMPLES = 0x9110, GL_SAMPLE_SHADING_ARB = 0x8C36,
GL_MIN_SAMPLE_SHADING_VALUE_ARB = 0x8C37, GL_TEXTURE_CUBE_MAP_ARRAY_ARB = 0x9009, GL_TEXTURE_BINDING_CUBE_MAP_ARRAY_ARB = 0x900A, GL_PROXY_TEXTURE_CUBE_MAP_ARRAY_ARB = 0x900B,
GL_SAMPLER_CUBE_MAP_ARRAY_ARB = 0x900C, GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW_ARB = 0x900D, GL_INT_SAMPLER_CUBE_MAP_ARRAY_ARB = 0x900E, GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_ARB = 0x900F,
GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB = 0x8E5E, GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB = 0x8E5F, GL_SHADER_INCLUDE_ARB = 0x8DAE, GL_NAMED_STRING_LENGTH_ARB = 0x8DE9,
GL_NAMED_STRING_TYPE_ARB = 0x8DEA, GL_COMPRESSED_RGBA_BPTC_UNORM_ARB = 0x8E8C, GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB = 0x8E8D, GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB = 0x8E8E,
GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_ARB = 0x8E8F, GL_SRC1_COLOR = 0x88F9, GL_ONE_MINUS_SRC1_COLOR = 0x88FA, GL_ONE_MINUS_SRC1_ALPHA = 0x88FB,
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = 0x88FC, GL_ANY_SAMPLES_PASSED = 0x8C2F, GL_SAMPLER_BINDING = 0x8919, GL_RGB10_A2UI = 0x906F,
GL_TEXTURE_SWIZZLE_R = 0x8E42, GL_TEXTURE_SWIZZLE_G = 0x8E43, GL_TEXTURE_SWIZZLE_B = 0x8E44, GL_TEXTURE_SWIZZLE_A = 0x8E45,
GL_TEXTURE_SWIZZLE_RGBA = 0x8E46, GL_TIME_ELAPSED = 0x88BF, GL_TIMESTAMP = 0x8E28, GL_INT_2_10_10_10_REV = 0x8D9F,
GL_DRAW_INDIRECT_BUFFER = 0x8F3F, GL_DRAW_INDIRECT_BUFFER_BINDING = 0x8F43, GL_GEOMETRY_SHADER_INVOCATIONS = 0x887F, GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x8E5A,
GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5B, GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5C, GL_FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D, GL_DOUBLE_VEC2 = 0x8FFC,
GL_DOUBLE_VEC3 = 0x8FFD, GL_DOUBLE_VEC4 = 0x8FFE, GL_DOUBLE_MAT2 = 0x8F46, GL_DOUBLE_MAT3 = 0x8F47,
GL_DOUBLE_MAT4 = 0x8F48, GL_DOUBLE_MAT2x3 = 0x8F49, GL_DOUBLE_MAT2x4 = 0x8F4A, GL_DOUBLE_MAT3x2 = 0x8F4B,
GL_DOUBLE_MAT3x4 = 0x8F4C, GL_DOUBLE_MAT4x2 = 0x8F4D, GL_DOUBLE_MAT4x3 = 0x8F4E, GL_ACTIVE_SUBROUTINES = 0x8DE5,
GL_ACTIVE_SUBROUTINE_UNIFORMS = 0x8DE6, GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS = 0x8E47, GL_ACTIVE_SUBROUTINE_MAX_LENGTH = 0x8E48, GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH = 0x8E49,
GL_MAX_SUBROUTINES = 0x8DE7, GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS = 0x8DE8, GL_NUM_COMPATIBLE_SUBROUTINES = 0x8E4A, GL_COMPATIBLE_SUBROUTINES = 0x8E4B,
GL_PATCHES = 0x000E, GL_PATCH_VERTICES = 0x8E72, GL_PATCH_DEFAULT_INNER_LEVEL = 0x8E73, GL_PATCH_DEFAULT_OUTER_LEVEL = 0x8E74,
GL_TESS_CONTROL_OUTPUT_VERTICES = 0x8E75, GL_TESS_GEN_MODE = 0x8E76, GL_TESS_GEN_SPACING = 0x8E77, GL_TESS_GEN_VERTEX_ORDER = 0x8E78,
GL_TESS_GEN_POINT_MODE = 0x8E79, GL_ISOLINES = 0x8E7A, GL_FRACTIONAL_ODD = 0x8E7B, GL_FRACTIONAL_EVEN = 0x8E7C,
GL_MAX_PATCH_VERTICES = 0x8E7D, GL_MAX_TESS_GEN_LEVEL = 0x8E7E, GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F, GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80,
GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81, GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82, GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83, GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84,
GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85, GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86, GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89, GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A,
GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C, GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D, GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E, GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F,
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = 0x84F0, GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x84F1, GL_TESS_EVALUATION_SHADER = 0x8E87, GL_TESS_CONTROL_SHADER = 0x8E88,
GL_TRANSFORM_FEEDBACK = 0x8E22, GL_TRANSFORM_FEEDBACK_PAUSED = 0x8E23, GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED = GL_TRANSFORM_FEEDBACK_PAUSED, GL_TRANSFORM_FEEDBACK_ACTIVE = 0x8E24,
GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE = GL_TRANSFORM_FEEDBACK_ACTIVE, GL_TRANSFORM_FEEDBACK_BINDING = 0x8E25, GL_MAX_TRANSFORM_FEEDBACK_BUFFERS = 0x8E70, GL_MAX_VERTEX_STREAMS = 0x8E71,
GL_FIXED = 0x140C, GL_IMPLEMENTATION_COLOR_READ_TYPE = 0x8B9A, GL_IMPLEMENTATION_COLOR_READ_FORMAT = 0x8B9B, GL_LOW_FLOAT = 0x8DF0,
GL_MEDIUM_FLOAT = 0x8DF1, GL_HIGH_FLOAT = 0x8DF2, GL_LOW_INT = 0x8DF3, GL_MEDIUM_INT = 0x8DF4,
GL_HIGH_INT = 0x8DF5, GL_SHADER_COMPILER = 0x8DFA, GL_NUM_SHADER_BINARY_FORMATS = 0x8DF9, GL_MAX_VERTEX_UNIFORM_VECTORS = 0x8DFB,
GL_MAX_VARYING_VECTORS = 0x8DFC, GL_MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD, GL_RGB565 = 0x8D62, GL_PROGRAM_BINARY_RETRIEVABLE_HINT = 0x8257,
GL_PROGRAM_BINARY_LENGTH = 0x8741, GL_NUM_PROGRAM_BINARY_FORMATS = 0x87FE, GL_PROGRAM_BINARY_FORMATS = 0x87FF, GL_VERTEX_SHADER_BIT = 0x00000001,
GL_FRAGMENT_SHADER_BIT = 0x00000002, GL_GEOMETRY_SHADER_BIT = 0x00000004, GL_TESS_CONTROL_SHADER_BIT = 0x00000008, GL_TESS_EVALUATION_SHADER_BIT = 0x00000010,
GL_ALL_SHADER_BITS = 0xFFFFFFFF, GL_PROGRAM_SEPARABLE = 0x8258, GL_ACTIVE_PROGRAM = 0x8259, GL_PROGRAM_PIPELINE_BINDING = 0x825A,
GL_MAX_VIEWPORTS = 0x825B, GL_VIEWPORT_SUBCL_PIXEL_BITS = 0x825C, GL_VIEWPORT_BOUNDS_RANGE = 0x825D, GL_LAYER_PROVOKING_VERTEX = 0x825E,
GL_VIEWPORT_INDEX_PROVOKING_VERTEX = 0x825F, GL_UNDEFINED_VERTEX = 0x8260, GL_SYNC_EVENT_ARB = 0x8240, GL_SYNC_EVENT_COMPLETE_ARB = 0x8241,
GL_DEBUG_OUTPUT_SYNCHRONOUS_ARB = 0x8242, GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH_ARB = 0x8243, GL_DEBUG_CALLBACK_FUNCTION_ARB = 0x8244, GL_DEBUG_CALLBACK_USER_PARAM_ARB = 0x8245,
GL_DEBUG_SOURCE_CL_API_ARB = 0x8246, GL_DEBUG_SOURCE_WINDOW_SYSTEM_ARB = 0x8247, GL_DEBUG_SOURCE_SHADER_COMPILER_ARB = 0x8248, GL_DEBUG_SOURCE_THIRD_PARTY_ARB = 0x8249,
GL_DEBUG_SOURCE_APPLICATION_ARB = 0x824A, GL_DEBUG_SOURCE_OTHER_ARB = 0x824B, GL_DEBUG_TYPE_ERROR_ARB = 0x824C, GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR_ARB = 0x824D,
GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR_ARB = 0x824E, GL_DEBUG_TYPE_PORTABILITY_ARB = 0x824F, GL_DEBUG_TYPE_PERFORMANCE_ARB = 0x8250, GL_DEBUG_TYPE_OTHER_ARB = 0x8251,
GL_MAX_DEBUG_MESSAGE_LENGTH_ARB = 0x9143, GL_MAX_DEBUG_LOGGED_MESSAGES_ARB = 0x9144, GL_DEBUG_LOGGED_MESSAGES_ARB = 0x9145, GL_DEBUG_SEVERITY_HIGH_ARB = 0x9146,
GL_DEBUG_SEVERITY_MEDIUM_ARB = 0x9147, GL_DEBUG_SEVERITY_LOW_ARB = 0x9148, GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT_ARB = 0x00000004, GL_LOSE_CONTEXT_ON_RESET_ARB = 0x8252,
GL_GUILTY_CONTEXT_RESET_ARB = 0x8253, GL_INNOCENT_CONTEXT_RESET_ARB = 0x8254, GL_UNKNOWN_CONTEXT_RESET_ARB = 0x8255, GL_RESET_NOTIFICATION_STRATEGY_ARB = 0x8256,
GL_NO_RESET_NOTIFICATION_ARB = 0x8261, GL_UNPACK_COMPRESSED_BLOCK_WIDTH = 0x9127, GL_UNPACK_COMPRESSED_BLOCK_HEIGHT = 0x9128, GL_UNPACK_COMPRESSED_BLOCK_DEPTH = 0x9129,
GL_UNPACK_COMPRESSED_BLOCK_SIZE = 0x912A, GL_PACK_COMPRESSED_BLOCK_WIDTH = 0x912B, GL_PACK_COMPRESSED_BLOCK_HEIGHT = 0x912C, GL_PACK_COMPRESSED_BLOCK_DEPTH = 0x912D,
GL_PACK_COMPRESSED_BLOCK_SIZE = 0x912E, GL_NUM_SAMPLE_COUNTS = 0x9380, GL_MIN_MAP_BUFFER_ALIGNMENT = 0x90BC, GL_ATOMIC_COUNTER_BUFFER = 0x92C0,
GL_ATOMIC_COUNTER_BUFFER_BINDING = 0x92C1, GL_ATOMIC_COUNTER_BUFFER_START = 0x92C2, GL_ATOMIC_COUNTER_BUFFER_SIZE = 0x92C3, GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE = 0x92C4,
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS = 0x92C5, GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES = 0x92C6, GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER = 0x92C7, GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER = 0x92C8,
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x92C9, GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER = 0x92CA, GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER = 0x92CB, GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 0x92CC,
GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS = 0x92CD, GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS = 0x92CE, GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS = 0x92CF, GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 0x92D0,
GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 0x92D1, GL_MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2, GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS = 0x92D3, GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS = 0x92D4,
GL_MAX_GEOMETRY_ATOMIC_COUNTERS = 0x92D5, GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6, GL_MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7, GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x92D8,
GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 0x92DC, GL_ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x92D9, GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX = 0x92DA, GL_UNSIGNED_INT_ATOMIC_COUNTER = 0x92DB,
GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 0x00000001, GL_ELEMENT_ARRAY_BARRIER_BIT = 0x00000002, GL_UNIFORM_BARRIER_BIT = 0x00000004, GL_TEXTURE_FETCH_BARRIER_BIT = 0x00000008,
GL_SHADER_IMAGE_ACCESS_BARRIER_BIT = 0x00000020, GL_COMMAND_BARRIER_BIT = 0x00000040, GL_PIXEL_BUFFER_BARRIER_BIT = 0x00000080, GL_TEXTURE_UPDATE_BARRIER_BIT = 0x00000100,
GL_BUFFER_UPDATE_BARRIER_BIT = 0x00000200, GL_FRAMEBUFFER_BARRIER_BIT = 0x00000400, GL_TRANSFORM_FEEDBACK_BARRIER_BIT = 0x00000800, GL_ATOMIC_COUNTER_BARRIER_BIT = 0x00001000,
GL_ALL_BARRIER_BITS = 0xFFFFFFFF, GL_MAX_IMAGE_UNITS = 0x8F38, GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS = 0x8F39, GL_IMAGE_BINDING_NAME = 0x8F3A,
GL_IMAGE_BINDING_LEVEL = 0x8F3B, GL_IMAGE_BINDING_LAYERED = 0x8F3C, GL_IMAGE_BINDING_LAYER = 0x8F3D, GL_IMAGE_BINDING_ACCESS = 0x8F3E,
GL_IMAGE_1D = 0x904C, GL_IMAGE_2D = 0x904D, GL_IMAGE_3D = 0x904E, GL_IMAGE_2D_RECT = 0x904F,
GL_IMAGE_CUBE = 0x9050, GL_IMAGE_BUFFER = 0x9051, GL_IMAGE_1D_ARRAY = 0x9052, GL_IMAGE_2D_ARRAY = 0x9053,
GL_IMAGE_CUBE_MAP_ARRAY = 0x9054, GL_IMAGE_2D_MULTISAMPLE = 0x9055, GL_IMAGE_2D_MULTISAMPLE_ARRAY = 0x9056, GL_INT_IMAGE_1D = 0x9057,
GL_INT_IMAGE_2D = 0x9058, GL_INT_IMAGE_3D = 0x9059, GL_INT_IMAGE_2D_RECT = 0x905A, GL_INT_IMAGE_CUBE = 0x905B,
GL_INT_IMAGE_BUFFER = 0x905C, GL_INT_IMAGE_1D_ARRAY = 0x905D, GL_INT_IMAGE_2D_ARRAY = 0x905E, GL_INT_IMAGE_CUBE_MAP_ARRAY = 0x905F,
GL_INT_IMAGE_2D_MULTISAMPLE = 0x9060, GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY = 0x9061, GL_UNSIGNED_INT_IMAGE_1D = 0x9062, GL_UNSIGNED_INT_IMAGE_2D = 0x9063,
GL_UNSIGNED_INT_IMAGE_3D = 0x9064, GL_UNSIGNED_INT_IMAGE_2D_RECT = 0x9065, GL_UNSIGNED_INT_IMAGE_CUBE = 0x9066, GL_UNSIGNED_INT_IMAGE_BUFFER = 0x9067,
GL_UNSIGNED_INT_IMAGE_1D_ARRAY = 0x9068, GL_UNSIGNED_INT_IMAGE_2D_ARRAY = 0x9069, GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY = 0x906A, GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE = 0x906B,
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY = 0x906C, GL_MAX_IMAGE_SAMPLES = 0x906D, GL_IMAGE_BINDING_FORMAT = 0x906E, GL_IMAGE_FORMAT_COMPATIBILITY_TYPE = 0x90C7,
GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = 0x90C8, GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = 0x90C9, GL_MAX_VERTEX_IMAGE_UNIFORMS = 0x90CA, GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS = 0x90CB,
GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS = 0x90CC, GL_MAX_GEOMETRY_IMAGE_UNIFORMS = 0x90CD, GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 0x90CE, GL_MAX_COMBINED_IMAGE_UNIFORMS = 0x90CF,
GL_TEXTURE_IMMUTABLE_FORMAT = 0x912F, GL_COMPRESSED_RGBA_ASTC_4x4_KHR = 0x93B0, GL_COMPRESSED_RGBA_ASTC_5x4_KHR = 0x93B1, GL_COMPRESSED_RGBA_ASTC_5x5_KHR = 0x93B2,
GL_COMPRESSED_RGBA_ASTC_6x5_KHR = 0x93B3, GL_COMPRESSED_RGBA_ASTC_6x6_KHR = 0x93B4, GL_COMPRESSED_RGBA_ASTC_8x5_KHR = 0x93B5, GL_COMPRESSED_RGBA_ASTC_8x6_KHR = 0x93B6,
GL_COMPRESSED_RGBA_ASTC_8x8_KHR = 0x93B7, GL_COMPRESSED_RGBA_ASTC_10x5_KHR = 0x93B8, GL_COMPRESSED_RGBA_ASTC_10x6_KHR = 0x93B9, GL_COMPRESSED_RGBA_ASTC_10x8_KHR = 0x93BA,
GL_COMPRESSED_RGBA_ASTC_10x10_KHR = 0x93BB, GL_COMPRESSED_RGBA_ASTC_12x10_KHR = 0x93BC, GL_COMPRESSED_RGBA_ASTC_12x12_KHR = 0x93BD, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR = 0x93D0,
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR = 0x93D1, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR = 0x93D2, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR = 0x93D3, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR = 0x93D4,
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR = 0x93D5, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR = 0x93D6, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR = 0x93D7, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR = 0x93D8,
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR = 0x93D9, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR = 0x93DA, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR = 0x93DB, GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR = 0x93DC,
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR = 0x93DD, GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242, GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x8243, GL_DEBUG_CALLBACK_FUNCTION = 0x8244,
GL_DEBUG_CALLBACK_USER_PARAM = 0x8245, GL_DEBUG_SOURCE_API = 0x8246, GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x8247, GL_DEBUG_SOURCE_SHADER_COMPILER = 0x8248,
GL_DEBUG_SOURCE_THIRD_PARTY = 0x8249, GL_DEBUG_SOURCE_APPLICATION = 0x824A, GL_DEBUG_SOURCE_OTHER = 0x824B, GL_DEBUG_TYPE_ERROR = 0x824C,
GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x824D, GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x824E, GL_DEBUG_TYPE_PORTABILITY = 0x824F, GL_DEBUG_TYPE_PERFORMANCE = 0x8250,
GL_DEBUG_TYPE_OTHER = 0x8251, GL_DEBUG_TYPE_MARKER = 0x8268, GL_DEBUG_TYPE_PUSH_GROUP = 0x8269, GL_DEBUG_TYPE_POP_GROUP = 0x826A,
GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B, GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x826C, GL_DEBUG_GROUP_STACK_DEPTH = 0x826D, GL_BUFFER = 0x82E0,
GL_SHADER = 0x82E1, GL_PROGRAM = 0x82E2, GL_QUERY = 0x82E3, GL_PROGRAM_PIPELINE = 0x82E4,
GL_SAMPLER = 0x82E6, GL_DISPLAY_LIST = 0x82E7, GL_MAX_LABEL_LENGTH = 0x82E8, GL_MAX_DEBUG_MESSAGE_LENGTH = 0x9143,
GL_MAX_DEBUG_LOGGED_MESSAGES = 0x9144, GL_DEBUG_LOGGED_MESSAGES = 0x9145, GL_DEBUG_SEVERITY_HIGH = 0x9146, GL_DEBUG_SEVERITY_MEDIUM = 0x9147,
GL_DEBUG_SEVERITY_LOW = 0x9148, GL_DEBUG_OUTPUT = 0x92E0, GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002, GL_COMPUTE_SHADER = 0x91B9,
GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB, GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC, GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD, GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262,
GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263, GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264, GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265, GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266,
GL_MAX_COMPUTE_LOCAL_INVOCATIONS = 0x90EB, GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE, GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF, GL_COMPUTE_LOCAL_WORK_SIZE = 0x8267,
GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 0x90EC, GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 0x90ED, GL_DISPATCH_INDIRECT_BUFFER = 0x90EE, GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x90EF,
GL_COMPUTE_SHADER_BIT = 0x00000020, GL_COMPRESSED_RGB8_ETC2 = 0x9274, GL_COMPRESSED_SRGB8_ETC2 = 0x9275, GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276,
GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277, GL_COMPRESSED_RGBA8_ETC2_EAC = 0x9278, GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279, GL_COMPRESSED_R11_EAC = 0x9270,
GL_COMPRESSED_SIGNED_R11_EAC = 0x9271, GL_COMPRESSED_RG11_EAC = 0x9272, GL_COMPRESSED_SIGNED_RG11_EAC = 0x9273, GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69,
GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A, GL_MAX_ELEMENT_INDEX = 0x8D6B, GL_MAX_UNIFORM_LOCATIONS = 0x826E, GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x9310,
GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x9311, GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x9312, GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x9313, GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x9314,
GL_MAX_FRAMEBUFFER_WIDTH = 0x9315, GL_MAX_FRAMEBUFFER_HEIGHT = 0x9316, GL_MAX_FRAMEBUFFER_LAYERS = 0x9317, GL_MAX_FRAMEBUFFER_SAMPLES = 0x9318,
GL_INTERNALFORMAT_SUPPORTED = 0x826F, GL_INTERNALFORMAT_PREFERRED = 0x8270, GL_INTERNALFORMAT_RED_SIZE = 0x8271, GL_INTERNALFORMAT_GREEN_SIZE = 0x8272,
GL_INTERNALFORMAT_BLUE_SIZE = 0x8273, GL_INTERNALFORMAT_ALPHA_SIZE = 0x8274, GL_INTERNALFORMAT_DEPTH_SIZE = 0x8275, GL_INTERNALFORMAT_STENCIL_SIZE = 0x8276,
GL_INTERNALFORMAT_SHARED_SIZE = 0x8277, GL_INTERNALFORMAT_RED_TYPE = 0x8278, GL_INTERNALFORMAT_GREEN_TYPE = 0x8279, GL_INTERNALFORMAT_BLUE_TYPE = 0x827A,
GL_INTERNALFORMAT_ALPHA_TYPE = 0x827B, GL_INTERNALFORMAT_DEPTH_TYPE = 0x827C, GL_INTERNALFORMAT_STENCIL_TYPE = 0x827D, GL_MAX_WIDTH = 0x827E,
GL_MAX_HEIGHT = 0x827F, GL_MAX_DEPTH = 0x8280, GL_MAX_LAYERS = 0x8281, GL_MAX_COMBINED_DIMENSIONS = 0x8282,
GL_COLOR_COMPONENTS = 0x8283, GL_DEPTH_COMPONENTS = 0x8284, GL_STENCIL_COMPONENTS = 0x8285, GL_COLOR_RENDERABLE = 0x8286,
GL_DEPTH_RENDERABLE = 0x8287, GL_STENCIL_RENDERABLE = 0x8288, GL_FRAMEBUFFER_RENDERABLE = 0x8289, GL_FRAMEBUFFER_RENDERABLE_LAYERED = 0x828A,
GL_FRAMEBUFFER_BLEND = 0x828B, GL_READ_CL_PIXELS = 0x828C, GL_READ_CL_PIXELS_FORMAT = 0x828D, GL_READ_CL_PIXELS_TYPE = 0x828E,
GL_TEXTURE_IMAGE_FORMAT = 0x828F, GL_TEXTURE_IMAGE_TYPE = 0x8290, GL_GET_TEXTURE_IMAGE_FORMAT = 0x8291, GL_GET_TEXTURE_IMAGE_TYPE = 0x8292,
GL_MIPMAP = 0x8293, GL_MANUAL_GENERATE_MIPMAP = 0x8294, GL_AUTO_GENERATE_MIPMAP = 0x8295, GL_COLOR_ENCODING = 0x8296,
GL_SRGB_READ = 0x8297, GL_SRGB_WRITE = 0x8298, GL_SRGB_DECODE_ARB = 0x8299, GL_FILTER = 0x829A,
GL_VERTEX_TEXTURE = 0x829B, GL_TESS_CONTROL_TEXTURE = 0x829C, GL_TESS_EVALUATION_TEXTURE = 0x829D, GL_GEOMETRY_TEXTURE = 0x829E,
GL_FRAGMENT_TEXTURE = 0x829F, GL_COMPUTE_TEXTURE = 0x82A0, GL_TEXTURE_SHADOW = 0x82A1, GL_TEXTURE_GATHER = 0x82A2,
GL_TEXTURE_GATHER_SHADOW = 0x82A3, GL_SHADER_IMAGE_LOAD = 0x82A4, GL_SHADER_IMAGE_STORE = 0x82A5, GL_SHADER_IMAGE_ATOMIC = 0x82A6,
GL_IMAGE_TEXEL_SIZE = 0x82A7, GL_IMAGE_COMPATIBILITY_CLASS = 0x82A8, GL_IMAGE_CL_PIXEL_FORMAT = 0x82A9, GL_IMAGE_CL_PIXEL_TYPE = 0x82AA,
GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 0x82AC, GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 0x82AD, GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 0x82AE, GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 0x82AF,
GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 0x82B1, GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 0x82B2, GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 0x82B3, GL_CLEAR_BUFFER = 0x82B4,
GL_TEXTURE_VIEW = 0x82B5, GL_VIEW_COMPATIBILITY_CLASS = 0x82B6, GL_FULL_SUPPORT = 0x82B7, GL_CAVEAT_SUPPORT = 0x82B8,
GL_IMAGE_CLASS_4_X_32 = 0x82B9, GL_IMAGE_CLASS_2_X_32 = 0x82BA, GL_IMAGE_CLASS_1_X_32 = 0x82BB, GL_IMAGE_CLASS_4_X_16 = 0x82BC,
GL_IMAGE_CLASS_2_X_16 = 0x82BD, GL_IMAGE_CLASS_1_X_16 = 0x82BE, GL_IMAGE_CLASS_4_X_8 = 0x82BF, GL_IMAGE_CLASS_2_X_8 = 0x82C0,
GL_IMAGE_CLASS_1_X_8 = 0x82C1, GL_IMAGE_CLASS_11_11_10 = 0x82C2, GL_IMAGE_CLASS_10_10_10_2 = 0x82C3, GL_VIEW_CLASS_128_BITS = 0x82C4,
GL_VIEW_CLASS_96_BITS = 0x82C5, GL_VIEW_CLASS_64_BITS = 0x82C6, GL_VIEW_CLASS_48_BITS = 0x82C7, GL_VIEW_CLASS_32_BITS = 0x82C8,
GL_VIEW_CLASS_24_BITS = 0x82C9, GL_VIEW_CLASS_16_BITS = 0x82CA, GL_VIEW_CLASS_8_BITS = 0x82CB, GL_VIEW_CLASS_S3TC_DXT1_RGB = 0x82CC,
GL_VIEW_CLASS_S3TC_DXT1_RGBA = 0x82CD, GL_VIEW_CLASS_S3TC_DXT3_RGBA = 0x82CE, GL_VIEW_CLASS_S3TC_DXT5_RGBA = 0x82CF, GL_VIEW_CLASS_RGTC1_RED = 0x82D0,
GL_VIEW_CLASS_RGTC2_RG = 0x82D1, GL_VIEW_CLASS_BPTC_UNORM = 0x82D2, GL_VIEW_CLASS_BPTC_FLOAT = 0x82D3, GL_UNIFORM = 0x92E1,
GL_UNIFORM_BLOCK = 0x92E2, GL_PROGRAM_INPUT = 0x92E3, GL_PROGRAM_OUTPUT = 0x92E4, GL_BUFFER_VARIABLE = 0x92E5,
GL_SHADER_STORAGE_BLOCK = 0x92E6, GL_VERTEX_SUBROUTINE = 0x92E8, GL_TESS_CONTROL_SUBROUTINE = 0x92E9, GL_TESS_EVALUATION_SUBROUTINE = 0x92EA,
GL_GEOMETRY_SUBROUTINE = 0x92EB, GL_FRAGMENT_SUBROUTINE = 0x92EC, GL_COMPUTE_SUBROUTINE = 0x92ED, GL_VERTEX_SUBROUTINE_UNIFORM = 0x92EE,
GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x92EF, GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x92F0, GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x92F1, GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x92F2,
GL_COMPUTE_SUBROUTINE_UNIFORM = 0x92F3, GL_TRANSFORM_FEEDBACK_VARYING = 0x92F4, GL_ACTIVE_RESOURCES = 0x92F5, GL_MAX_NAME_LENGTH = 0x92F6,
GL_MAX_NUM_ACTIVE_VARIABLES = 0x92F7, GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 0x92F8, GL_NAME_LENGTH = 0x92F9, GL_TYPE = 0x92FA,
GL_ARRAY_SIZE = 0x92FB, GL_OFFSET = 0x92FC, GL_BLOCK_INDEX = 0x92FD, GL_ARRAY_STRIDE = 0x92FE,
GL_MATRIX_STRIDE = 0x92FF, GL_IS_ROW_MAJOR = 0x9300, GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x9301, GL_BUFFER_BINDING = 0x9302,
GL_BUFFER_DATA_SIZE = 0x9303, GL_NUM_ACTIVE_VARIABLES = 0x9304, GL_ACTIVE_VARIABLES = 0x9305, GL_REFERENCED_BY_VERTEX_SHADER = 0x9306,
GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x9307, GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x9308, GL_REFERENCED_BY_GEOMETRY_SHADER = 0x9309, GL_REFERENCED_BY_FRAGMENT_SHADER = 0x930A,
GL_REFERENCED_BY_COMPUTE_SHADER = 0x930B, GL_TOP_LEVEL_ARRAY_SIZE = 0x930C, GL_TOP_LEVEL_ARRAY_STRIDE = 0x930D, GL_LOCATION = 0x930E,
GL_LOCATION_INDEX = 0x930F, GL_IS_PER_PATCH = 0x92E7, GL_SHADER_STORAGE_BUFFER = 0x90D2, GL_SHADER_STORAGE_BUFFER_BINDING = 0x90D3,
GL_SHADER_STORAGE_BUFFER_START = 0x90D4, GL_SHADER_STORAGE_BUFFER_SIZE = 0x90D5, GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6, GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7,
GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x90D8, GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9, GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA, GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB,
GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC, GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD, GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE, GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x90DF,
GL_SHADER_STORAGE_BARRIER_BIT = 0x2000, GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS, GL_DEPTH_STENCIL_TEXTURE_MODE = 0x90EA, GL_TEXTURE_BUFFER_OFFSET = 0x919D,
GL_TEXTURE_BUFFER_SIZE = 0x919E, GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x919F, GL_TEXTURE_VIEW_MIN_LEVEL = 0x82DB, GL_TEXTURE_VIEW_NUM_LEVELS = 0x82DC,
GL_TEXTURE_VIEW_MIN_LAYER = 0x82DD, GL_TEXTURE_VIEW_NUM_LAYERS = 0x82DE, GL_TEXTURE_IMMUTABLE_LEVELS = 0x82DF, GL_VERTEX_ATTRIB_BINDING = 0x82D4,
GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5, GL_VERTEX_BINDING_DIVISOR = 0x82D6, GL_VERTEX_BINDING_OFFSET = 0x82D7, GL_VERTEX_BINDING_STRIDE = 0x82D8,
GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9, GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA, GL_TEXTURE_MAX_ANISOTROPY_EXT = 0x84FE, GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = 0x84FF,
GL_COMPRESSED_RGB_S3TC_DXT1_EXT = 0x83F0, GL_COMPRESSED_RGBA_S3TC_DXT1_EXT = 0x83F1, GL_COMPRESSED_RGBA_S3TC_DXT3_EXT = 0x83F2, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT = 0x83F3,
GL_SRGB_EXT = 0x8C40, GL_SRGB8_EXT = 0x8C41, GL_SRGB_ALPHA_EXT = 0x8C42, GL_SRGB8_ALPHA8_EXT = 0x8C43,
GL_SLUMINANCE_ALPHA_EXT = 0x8C44, GL_SLUMINANCE8_ALPHA8_EXT = 0x8C45, GL_SLUMINANCE_EXT = 0x8C46, GL_SLUMINANCE8_EXT = 0x8C47,
GL_COMPRESSED_SRGB_EXT = 0x8C48, GL_COMPRESSED_SRGB_ALPHA_EXT = 0x8C49, GL_COMPRESSED_SLUMINANCE_EXT = 0x8C4A, GL_COMPRESSED_SLUMINANCE_ALPHA_EXT = 0x8C4B,
GL_COMPRESSED_SRGB_S3TC_DXT1_EXT = 0x8C4C, GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT = 0x8C4D, GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT = 0x8C4E, GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT = 0x8C4F,
GL_MAX_VERTEX_ATTRIB_STRIDE = 0x82E5, GL_MAP_PERSISTENT_BIT = 0x0040, GL_MAP_COHERENT_BIT = 0x0080, GL_DYNAMIC_STORAGE_BIT = 0x0100,
GL_CLIENT_STORAGE_BIT = 0x0200, GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT = 0x00004000, GL_BUFFER_IMMUTABLE_STORAGE = 0x821F, GL_BUFFER_STORAGE_FLAGS = 0x8220,
GL_CLEAR_TEXTURE = 0x9365, GL_LOCATION_COMPONENT = 0x934A, GL_TRANSFORM_FEEDBACK_BUFFER_INDEX = 0x934B, GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE = 0x934C,
GL_QUERY_BUFFER = 0x9192, GL_QUERY_BUFFER_BARRIER_BIT = 0x00008000, GL_QUERY_BUFFER_BINDING = 0x9193, GL_QUERY_RESULT_NO_WAIT = 0x9194,
GL_MIRROR_CLAMP_TO_EDGE = 0x8743, GL_COMPARE_R_TO_TEXTURE = 0x884e, GL_POINT_SPRITE = 0x8861, GL_MAX_TEXTURE_COORDS = 0x8871,
GL_MAX_TEXTURE_UNITS = 0x84E2
}
Display Defines.
enum DrawBuffer {
buffer_none, buffer_front_left, buffer_front_right, buffer_back_left,
buffer_back_right, buffer_front, buffer_back, buffer_left,
buffer_right, buffer_front_and_back
}
Drawing buffers.
enum EulerOrder {
EulerOrder::xyz, EulerOrder::xzy, EulerOrder::yzx, EulerOrder::yxz,
EulerOrder::zxy, EulerOrder::zyx
}
Euler angle rotation order.
enum EventUIPhase { EventUIPhase::none, EventUIPhase::capturing, EventUIPhase::at_target, EventUIPhase::bubbling }
UI event dispatch phase.
enum FaceSide { face_clockwise, face_counter_clockwise }
Front face modes.
enum FileAccess { FileAccess::read, FileAccess::write, FileAccess::read_write }
enum FilePathType { FilePathType::file_system, FilePathType::slashes }
File path types.
enum FillMode { fill_point, fill_line, fill_polygon }
Polygon filling modes.
enum FocusChangeType { FocusChangeType::gained, FocusChangeType::lost }
Focus change type.
enum FocusPolicy { FocusPolicy::reject, FocusPolicy::accept }
Automatic focus policy.
enum FontStyle { FontStyle::normal, FontStyle::italic, FontStyle::oblique }
enum FontWeight : int {
FontWeight::thin = 100, FontWeight::extra_light = 200, FontWeight::light = 300, FontWeight::normal = 400,
FontWeight::medium = 500, FontWeight::semi_bold = 600, FontWeight::bold = 700, FontWeight::extra_bold = 800,
FontWeight::heavy = 900
}
enum FrameBufferBindTarget { framebuffer_draw, framebuffer_read }
Framebuffer bind target.
enum Handedness { handed_left, handed_right }
enum InputCode {
mouse_left = 0, mouse_right = 1, mouse_middle = 2, mouse_wheel_up = 3,
mouse_wheel_down = 4, mouse_xbutton1 = 5, mouse_xbutton2 = 6, mouse_count = 7,
joystick_x = 0, joystick_y, joystick_z, joystick_rx,
joystick_ry, joystick_rz, joystick_slider, joystick_dial,
joystick_wheel, joystick_vx, joystick_vy, joystick_vz,
joystick_vrx, joystick_vry, joystick_vrz, joystick_vslider0,
joystick_vslider1, joystick_ax, joystick_ay, joystick_az,
joystick_arx, joystick_ary, joystick_arz, joystick_aslider0,
joystick_aslider1, joystick_fx, joystick_fy, joystick_fz,
joystick_frx, joystick_fry, joystick_frz, joystick_fslider0,
joystick_fslider1, joystick_button = 0, joystick_hat = 0, keycode_backspace =XK_BackSpace,
keycode_tab =XK_Tab, keycode_clear =XK_Clear, keycode_return =XK_Return, keycode_shift =XK_Shift_L,
keycode_control =XK_Control_L, keycode_menu =XK_Menu, keycode_pause =XK_Pause, keycode_kanji =XK_Kanji,
keycode_escape =XK_Escape, keycode_convert =XK_Henkan_Mode, keycode_nonconvert =XK_Muhenkan, keycode_space =XK_space,
keycode_prior =XK_Prior, keycode_next =XK_Next, keycode_end =XK_End, keycode_home =XK_Home,
keycode_left =XK_Left, keycode_up =XK_Up, keycode_right =XK_Right, keycode_down =XK_Down,
keycode_select =XK_Select, keycode_print =XK_Print, keycode_execute =XK_Execute, keycode_insert =XK_Insert,
keycode_delete =XK_Delete, keycode_help =XK_Help, keycode_0 =XK_0, keycode_1 =XK_1,
keycode_2 =XK_2, keycode_3 =XK_3, keycode_4 =XK_4, keycode_5 =XK_5,
keycode_6 =XK_6, keycode_7 =XK_7, keycode_8 =XK_8, keycode_9 =XK_9,
keycode_a =XK_a, keycode_b =XK_b, keycode_c =XK_c, keycode_d =XK_d,
keycode_e =XK_e, keycode_f =XK_f, keycode_g =XK_g, keycode_h =XK_h,
keycode_i =XK_i, keycode_j =XK_j, keycode_k =XK_k, keycode_l =XK_l,
keycode_m =XK_m, keycode_n =XK_n, keycode_o =XK_o, keycode_p =XK_p,
keycode_q =XK_q, keycode_r =XK_r, keycode_s =XK_s, keycode_t =XK_t,
keycode_u =XK_u, keycode_v =XK_v, keycode_w =XK_w, keycode_x =XK_x,
keycode_y =XK_y, keycode_z =XK_z, keycode_lwin =XK_Super_L, keycode_rwin =XK_Multi_key,
keycode_apps =XK_Menu, keycode_numpad0 =XK_KP_0, keycode_numpad1 =XK_KP_1, keycode_numpad2 =XK_KP_2,
keycode_numpad3 =XK_KP_3, keycode_numpad4 =XK_KP_4, keycode_numpad5 =XK_KP_5, keycode_numpad6 =XK_KP_6,
keycode_numpad7 =XK_KP_7, keycode_numpad8 =XK_KP_8, keycode_numpad9 =XK_KP_9, keycode_numpad_enter =XK_KP_Enter,
keycode_multiply =XK_KP_Multiply, keycode_add =XK_KP_Add, keycode_separator =XK_KP_Separator, keycode_subtract =XK_KP_Subtract,
keycode_decimal =XK_KP_Decimal, keycode_divide =XK_KP_Divide, keycode_f1 =XK_F1, keycode_f2 =XK_F2,
keycode_f3 =XK_F3, keycode_f4 =XK_F4, keycode_f5 =XK_F5, keycode_f6 =XK_F6,
keycode_f7 =XK_F7, keycode_f8 =XK_F8, keycode_f9 =XK_F9, keycode_f10 =XK_F10,
keycode_f11 =XK_F11, keycode_f12 =XK_F12, keycode_f13 =XK_F13, keycode_f14 =XK_F14,
keycode_f15 =XK_F15, keycode_f16 =XK_F16, keycode_f17 =XK_F17, keycode_f18 =XK_F18,
keycode_f19 =XK_F19, keycode_f20 =XK_F20, keycode_f21 =XK_F21, keycode_f22 =XK_F22,
keycode_f23 =XK_F23, keycode_f24 =XK_F24, keycode_numlock =XK_Num_Lock, keycode_scroll =XK_Scroll_Lock,
keycode_lshift =XK_Shift_L, keycode_rshift =XK_Shift_R, keycode_lcontrol =XK_Control_L, keycode_rcontrol =XK_Control_R,
keycode_lmenu =XK_Meta_L, keycode_rmenu =XK_Meta_R, keycode_enter = keycode_return, keycode_lapple = keycode_lwin,
keycode_rapple = keycode_rwin, keycode_unknown = -1
}
enum JsonType {
JsonType::undefined, JsonType::null, JsonType::object, JsonType::array,
JsonType::number, JsonType::boolean, JsonType::string
}
enum Key {
Key::none = 0x00, Key::backspace = 0x08, Key::tab = 0x09, Key::linefeed = 0x0a,
Key::clear = 0x0b, Key::scroll = 0x0c, Key::key_return = 0x0d, Key::select = 0x0e,
Key::execute = 0x1a, Key::escape = 0x1b, Key::pause = 0x1c, Key::print = 0x1d,
Key::space = 0x20, Key::prior = 0x21, Key::next = 0x22, Key::home = 0x23,
Key::end = 0x24, Key::left = 0x25, Key::up = 0x26, Key::right = 0x27,
Key::down = 0x28, Key::kanji = 0x29, Key::convert = 0x2a, Key::nonconvert = 0x2b,
Key::separator = 0x2c, Key::help = 0x3f, Key::key_0 = '0', Key::key_1 = '1',
Key::key_2 = '2', Key::key_3 = '3', Key::key_4 = '4', Key::key_5 = '5',
Key::key_6 = '6', Key::key_7 = '7', Key::key_8 = '8', Key::key_9 = '9',
Key::a = 'A', Key::b = 'B', Key::c = 'C', Key::d = 'D',
Key::e = 'E', Key::f = 'F', Key::g = 'G', Key::h = 'H',
Key::i = 'I', Key::j = 'J', Key::k = 'K', Key::l = 'L',
Key::m = 'M', Key::n = 'N', Key::o = 'O', Key::p = 'P',
Key::q = 'Q', Key::r = 'R', Key::s = 'S', Key::t = 'T',
Key::u = 'U', Key::v = 'V', Key::w = 'W', Key::x = 'X',
Key::y = 'Y', Key::z = 'Z', Key::f1 = 0x61, Key::f2 = 0x62,
Key::f3 = 0x63, Key::f4 = 0x64, Key::f5 = 0x65, Key::f6 = 0x66,
Key::f7 = 0x67, Key::f8 = 0x68, Key::f9 = 0x69, Key::f10 = 0x6a,
Key::f11 = 0x6b, Key::f12 = 0x6c, Key::f13 = 0x6d, Key::f14 = 0x6e,
Key::f15 = 0x6f, Key::f16 = 0x70, Key::f17 = 0x71, Key::f18 = 0x72,
Key::f19 = 0x73, Key::f20 = 0x74, Key::f21 = 0x75, Key::f22 = 0x76,
Key::f23 = 0x77, Key::f24 = 0x78, Key::insert = 0x7e, Key::key_delete = 0x7f,
Key::numpad_0 = 0x80, Key::numpad_1 = 0x81, Key::numpad_2 = 0x82, Key::numpad_3 = 0x83,
Key::numpad_4 = 0x84, Key::numpad_5 = 0x85, Key::numpad_6 = 0x86, Key::numpad_7 = 0x87,
Key::numpad_8 = 0x88, Key::numpad_9 = 0x89, Key::multiply = 0x8a, Key::add = 0x8b,
Key::seperator = 0x8c, Key::subtract = 0x8d, Key::decimal = 0x8e, Key::divide = 0x8f,
Key::lshift = 0xe0, Key::rshift = 0xe1, Key::lcontrol = 0xe2, Key::rcontrol = 0xe3,
Key::lalt = 0xe4, Key::loption = lalt, Key::ralt = 0xe5, Key::roption = ralt,
Key::lmenu = 0xe6, Key::apps = lmenu, Key::rmenu = 0xe7, Key::lsuper = 0xe8,
Key::lcmd = lsuper, Key::rsuper = 0xe9, Key::rcmd = rsuper, Key::scrolllock = 0xea,
Key::capslock = 0xeb, Key::numlock = 0xec
}
Enumeration of keyboard keys recognized on UICore.
enum KeyEventType { KeyEventType::none, KeyEventType::press, KeyEventType::release }
Keyboard key event type.
enum LineBreakMode { LineBreakMode::clipping, LineBreakMode::truncating_head, LineBreakMode::truncating_tail, LineBreakMode::truncating_middle }
enum LogicOp {
logic_clear, logic_and, logic_and_reverse, logic_copy,
logic_and_inverted, logic_noop, logic_xor, logic_or,
logic_nor, logic_equiv, logic_invert, logic_or_reverse,
logic_copy_inverted, logic_or_inverted, logic_nand, logic_set
}
Logic Op.
enum Origin {
origin_top_left, origin_top_center, origin_top_right, origin_center_left,
origin_center, origin_center_right, origin_bottom_left, origin_bottom_center,
origin_bottom_right
}
Alignment origins.
enum PathFillMode { PathFillMode::alternate, PathFillMode::winding }
enum PNGColorType {
png_color_type_gray, png_color_type_gray_alpha, png_color_type_palette, png_color_type_rgb,
png_color_type_rgb_alpha, png_color_mask_palette, png_color_mask_color, png_color_mask_alpha
}
enum PNGFilterMethod { png_filter_type_default, png_intrapixel_differencing }
enum PNGInterlaceType { png_interlace_none, png_interlace_adam7 }
enum PNGOffsetUnitType { png_offset_pixel, png_offset_micrometer }
enum PNGResolutionUnitType { png_resolution_unknown, png_resolution_meter }
enum PNGsRGBIntent { png_srgb_intent_saturation, png_srgb_intent_perceptual, png_srgb_intent_absolute, png_srgb_intent_relative }
enum PNGUnknownChunkLocation { png_before_plte, png_before_idat, png_after_idat }
enum PointerButton {
PointerButton::none, PointerButton::left, PointerButton::right, PointerButton::middle,
PointerButton::wheel_up, PointerButton::wheel_down, PointerButton::xbutton1, PointerButton::xbutton2,
PointerButton::xbutton3, PointerButton::xbutton4, PointerButton::xbutton5, PointerButton::xbutton6
}
Pointer button.
enum PointerEventType {
PointerEventType::none, PointerEventType::enter, PointerEventType::leave, PointerEventType::move,
PointerEventType::press, PointerEventType::release, PointerEventType::double_click, PointerEventType::promixity_change
}
Pointer event type.
enum PointSpriteOrigin { origin_upper_left, origin_lower_left }
Point Sprite Origin.
enum PolygonOrientation { cl_clockwise, cl_counter_clockwise }
Polygon orientations.
enum PrimitivesType {
type_points, type_line_strip, type_line_loop, type_lines,
type_triangle_strip, type_triangle_fan, type_triangles
}
Primitive types.
enum ShaderLanguage { shader_glsl, shader_hlsl, shader_fixed_function, num_shader_languages }
Shader language used.
enum ShaderType : int {
ShaderType::vertex, ShaderType::geometry, ShaderType::fragment, ShaderType::tess_evaluation,
ShaderType::tess_control, ShaderType::compute, ShaderType::num_types
}
Shader Type.
enum SpanAlign { SpanAlign::left, SpanAlign::right, SpanAlign::center, SpanAlign::justify }
Span Align.
enum StagingDirection : int { StagingDirection::to_gpu, StagingDirection::from_gpu }
Staging usage direction.
enum StandardCursor {
StandardCursor::arrow, StandardCursor::appstarting, StandardCursor::cross, StandardCursor::hand,
StandardCursor::ibeam, StandardCursor::no, StandardCursor::size_all, StandardCursor::size_nesw,
StandardCursor::size_ns, StandardCursor::size_nwse, StandardCursor::size_we, StandardCursor::uparrow,
StandardCursor::wait
}
Standard Cursor.
enum StandardProgram { program_color_only, program_single_texture, program_sprite, program_path }
Standard Program.
enum StencilOp {
stencil_keep, stencil_zero, stencil_replace, stencil_incr,
stencil_decr, stencil_invert, stencil_incr_wrap, stencil_decr_wrap
}
Stencil operations.
enum StyleDimension {
StyleDimension::px, StyleDimension::em, StyleDimension::pt, StyleDimension::mm,
StyleDimension::cm, StyleDimension::in, StyleDimension::pc, StyleDimension::ex,
StyleDimension::ch, StyleDimension::rem, StyleDimension::vw, StyleDimension::vh,
StyleDimension::vmin, StyleDimension::vmax, StyleDimension::deg, StyleDimension::grad,
StyleDimension::rad, StyleDimension::turn, StyleDimension::s, StyleDimension::ms,
StyleDimension::hz, StyleDimension::khz, StyleDimension::dpi, StyleDimension::dpcm,
StyleDimension::dppx
}
Unit of a style value.
enum StyleTokenType {
StyleTokenType::null, StyleTokenType::ident, StyleTokenType::atkeyword, StyleTokenType::string,
StyleTokenType::invalid, StyleTokenType::hash, StyleTokenType::number, StyleTokenType::percentage,
StyleTokenType::dimension, StyleTokenType::uri, StyleTokenType::unicode_range, StyleTokenType::cdo,
StyleTokenType::cdc, StyleTokenType::colon, StyleTokenType::semi_colon, StyleTokenType::curly_brace_begin,
StyleTokenType::curly_brace_end, StyleTokenType::bracket_begin, StyleTokenType::bracket_end, StyleTokenType::square_bracket_begin,
StyleTokenType::square_bracket_end, StyleTokenType::whitespace, StyleTokenType::comment, StyleTokenType::function,
StyleTokenType::includes, StyleTokenType::dashmatch, StyleTokenType::delim
}
Token types recognized by the style tokenzier.
enum StyleValueType {
StyleValueType::undefined, StyleValueType::keyword, StyleValueType::length, StyleValueType::percentage,
StyleValueType::number, StyleValueType::string, StyleValueType::url, StyleValueType::color,
StyleValueType::angle, StyleValueType::time, StyleValueType::frequency, StyleValueType::resolution
}
Style value type.
enum TextAlignment { TextAlignment::left, TextAlignment::right, TextAlignment::center, TextAlignment::justify }
enum TextureCompareMode { comparemode_none, comparemode_compare_r_to_texture }
Texture compare modes.
enum TextureCubeDirection {
cl_cube_positive_x, cl_cube_negative_x, cl_cube_positive_y, cl_cube_negative_y,
cl_cube_positive_z, cl_cube_negative_z
}
Texture cube directions.
enum TextureDimensions {
texture_1d, texture_1d_array, texture_2d, texture_2d_array,
texture_3d, texture_cube, texture_cube_array
}
Texture dimensions.
enum TextureFilter {
filter_nearest, filter_linear, filter_nearest_mipmap_nearest, filter_nearest_mipmap_linear,
filter_linear_mipmap_nearest, filter_linear_mipmap_linear
}
Texture filters.
enum TextureFormat {
tf_rgba8, tf_rgb8, tf_bgra8, tf_bgr8,
tf_stencil_index1, tf_stencil_index4, tf_stencil_index8, tf_stencil_index16,
tf_r8, tf_r8_snorm, tf_r16, tf_r16_snorm,
tf_rg8, tf_rg8_snorm, tf_rg16, tf_rg16_snorm,
tf_r3_g3_b2, tf_rgb4, tf_rgb5, tf_rgb8_snorm,
tf_rgb10, tf_rgb12, tf_rgb16, tf_rgb16_snorm,
tf_rgba2, tf_rgba4, tf_rgb5_a1, tf_rgba8_snorm,
tf_rgb10_a2, tf_rgba12, tf_rgba16, tf_rgba16_snorm,
tf_srgb8, tf_srgb8_alpha8, tf_r16f, tf_rg16f,
tf_rgb16f, tf_rgba16f, tf_r32f, tf_rg32f,
tf_rgb32f, tf_rgba32f, tf_r11f_g11f_b10f, tf_rgb9_e5,
tf_r8i, tf_r8ui, tf_r16i, tf_r16ui,
tf_r32i, tf_r32ui, tf_rg8i, tf_rg8ui,
tf_rg16i, tf_rg16ui, tf_rg32i, tf_rg32ui,
tf_rgb8i, tf_rgb8ui, tf_rgb16i, tf_rgb16ui,
tf_rgb32i, tf_rgb32ui, tf_rgba8i, tf_rgba8ui,
tf_rgba16i, tf_rgba16ui, tf_rgba32i, tf_rgba32ui,
tf_depth_component16, tf_depth_component24, tf_depth_component32, tf_depth_component32f,
tf_depth24_stencil8, tf_depth32f_stencil8, tf_compressed_red, tf_compressed_rg,
tf_compressed_rgb, tf_compressed_rgba, tf_compressed_srgb, tf_compressed_srgb_alpha,
tf_compressed_red_rgtc1, tf_compressed_signed_red_rgtc1, tf_compressed_rg_rgtc2, tf_compressed_signed_rg_rgtc2,
tf_compressed_rgb_s3tc_dxt1, tf_compressed_rgba_s3tc_dxt1, tf_compressed_rgba_s3tc_dxt3, tf_compressed_rgba_s3tc_dxt5,
tf_compressed_srgb_s3tc_dxt1, tf_compressed_srgb_alpha_s3tc_dxt1, tf_compressed_srgb_alpha_s3tc_dxt3, tf_compressed_srgb_alpha_s3tc_dxt5
}
Texture format.
enum TextureGroupAllocationPolicy { TextureGroupAllocationPolicy::create_new_texture, TextureGroupAllocationPolicy::search_previous_textures }
TextureGroup allocation policy.
enum TextureImageYAxis { y_axis_bottom_up, y_axis_top_down }
Y axis direction for viewports, clipping rects, textures and render targets.
enum TextureSubtype {
subtype_cube_map_positive_x, subtype_cube_map_negative_x, subtype_cube_map_positive_y, subtype_cube_map_negative_y,
subtype_cube_map_positive_z, subtype_cube_map_negative_z
}
Texture Subtype.
enum TextureWrapMode { wrap_clamp_to_edge, wrap_repeat, wrap_mirrored_repeat }
Texture coordinate wrapping modes.
enum VertexAttributeDataType {
type_unsigned_byte, type_unsigned_short, type_unsigned_int, type_byte,
type_short, type_int, type_float
}
Primitives array description.
enum WindowShowType {
WindowShowType::hide, WindowShowType::show, WindowShowType::show_no_activate, WindowShowType::normal,
WindowShowType::maximized, WindowShowType::minimized, WindowShowType::maximize, WindowShowType::minimize,
WindowShowType::minimize_no_activate, WindowShowType::restore, WindowShowType::show_default
}
enum XmlNodeType {
XmlNodeType::element, XmlNodeType::attribute, XmlNodeType::text, XmlNodeType::cdata,
XmlNodeType::comment, XmlNodeType::document, XmlNodeType::document_fragment
}
enum XmlTokenType {
XmlTokenType::null, XmlTokenType::element, XmlTokenType::text, XmlTokenType::cdata,
XmlTokenType::processing_instruction, XmlTokenType::comment, XmlTokenType::doctype
}
enum XmlTokenVariant { XmlTokenVariant::begin, XmlTokenVariant::end, XmlTokenVariant::single }
Functions
template<class R , class T , class... Args>
std::function< R(Args...)> bind_member (T *instance, R(T::*method)(Args...))
template<typename A , typename B , typename C >
C clamp (A val, B minval, C maxval)
Key decode_ic (InputCode)
float degrees (float radians)
Convert a quantity in radians to degrees.
double degrees (double radians)
template<typename T >
Vec2< T > degrees (const Vec2< T > &radians)
template<typename T >
Vec3< T > degrees (const Vec3< T > &radians)
template<typename T >
Vec4< T > degrees (const Vec4< T > &radians)
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&...args)
template<typename A , typename B >
A max (A a, B b)
template<typename Type >
Vec2< Type > max (Vec2< Type > a, Vec2< Type > b)
template<typename Type >
Vec3< Type > max (Vec3< Type > a, Vec3< Type > b)
template<typename Type >
Vec4< Type > max (Vec4< Type > a, Vec4< Type > b)
template<typename A , typename B >
A min (A a, B b)
template<typename Type >
Vec2< Type > min (Vec2< Type > a, Vec2< Type > b)
template<typename Type >
Vec3< Type > min (Vec3< Type > a, Vec3< Type > b)
template<typename Type >
Vec4< Type > min (Vec4< Type > a, Vec4< Type > b)
template<typename A , typename B , typename C >
A mix (A a, B b, C mix)
float normalize_180 (float degrees)
Converts angle to range [-180,180] degrees.
double normalize_180 (double degrees)
template<typename T >
Vec2< T > normalize_180 (const Vec2< T > &degrees)
template<typename T >
Vec3< T > normalize_180 (const Vec3< T > &degrees)
template<typename T >
Vec4< T > normalize_180 (const Vec4< T > &degrees)
float normalize_2pi (float radians)
Converts angle to range [0,2*PI] radians.
double normalize_2pi (double radians)
template<typename T >
Vec2< T > normalize_2pi (const Vec2< T > &radians)
template<typename T >
Vec3< T > normalize_2pi (const Vec3< T > &radians)
template<typename T >
Vec4< T > normalize_2pi (const Vec4< T > &radians)
float normalize_360 (float degrees)
Converts angle to range [0,360] degrees.
double normalize_360 (double degrees)
template<typename T >
Vec2< T > normalize_360 (const Vec2< T > &degrees)
template<typename T >
Vec3< T > normalize_360 (const Vec3< T > &degrees)
template<typename T >
Vec4< T > normalize_360 (const Vec4< T > &degrees)
float normalize_pi (float radians)
Converts angle to range [-PI,PI] radians.
double normalize_pi (double radians)
template<typename T >
Vec2< T > normalize_pi (const Vec2< T > &radians)
template<typename T >
Vec3< T > normalize_pi (const Vec3< T > &radians)
template<typename T >
Vec4< T > normalize_pi (const Vec4< T > &radians)
template<typename Type >
Vec3< Type > operator* (const Vec3< Type > &v1, const Vec3< Type > &v2)
operator.
template<typename Type >
Vec3< Type > operator* (Type s, const Vec3< Type > &v)
operator.
template<typename Type >
Vec3< Type > operator* (const Vec3< Type > &v, Type s)
operator.
template<typename Type >
Vec2< Type > operator* (const Vec2< Type > &v1, const Vec2< Type > &v2)
operator.
template<typename Type >
Vec2< Type > operator* (Type s, const Vec2< Type > &v)
operator.
template<typename Type >
Vec2< Type > operator* (const Vec2< Type > &v, Type s)
operator.
template<typename Type >
Vec3< Type > operator* (const Vec3< Type > &v, const Mat3< Type > &matrix)
template<typename Type >
Vec2< Type > operator* (const Vec2< Type > &v, const Mat2< Type > &matrix)
template<typename Type >
Vec3< Type > operator* (const Mat3< Type > &matrix, const Vec3< Type > &v)
template<typename Type >
Vec2< Type > operator* (const Mat2< Type > &matrix, const Vec2< Type > &v)
template<typename Type >
Vec4< Type > operator* (const Vec4< Type > &v1, const Vec4< Type > &v2)
operator.
template<typename Type >
Vec4< Type > operator* (Type s, const Vec4< Type > &v)
operator.
template<typename Type >
Vec4< Type > operator* (const Vec4< Type > &v, Type s)
operator.
template<typename Type >
Vec4< Type > operator* (const Vec4< Type > &v, const Mat4< Type > &matrix)
template<typename Type >
Vec4< Type > operator* (const Mat4< Type > &matrix, const Vec4< Type > &v)
template<typename Type >
Vec3< Type > operator+ (const Vec3< Type > &v1, const Vec3< Type > &v2)
operator.
template<typename Type >
Vec3< Type > operator+ (Type s, const Vec3< Type > &v)
operator.
template<typename Type >
Vec3< Type > operator+ (const Vec3< Type > &v, Type s)
operator.
template<typename Type >
Vec2< Type > operator+ (const Vec2< Type > &v1, const Vec2< Type > &v2)
operator.
template<typename Type >
Vec2< Type > operator+ (Type s, const Vec2< Type > &v)
operator.
template<typename Type >
Vec2< Type > operator+ (const Vec2< Type > &v, Type s)
operator.
template<typename Type >
Vec4< Type > operator+ (const Vec4< Type > &v1, const Vec4< Type > &v2)
operator.
template<typename Type >
Vec4< Type > operator+ (Type s, const Vec4< Type > &v)
operator.
template<typename Type >
Vec4< Type > operator+ (const Vec4< Type > &v, Type s)
operator.
template<typename Type >
Vec3< Type > operator- (const Vec3< Type > &v1, const Vec3< Type > &v2)
operator.
template<typename Type >
Vec3< Type > operator- (Type s, const Vec3< Type > &v)
operator.
template<typename Type >
Vec3< Type > operator- (const Vec3< Type > &v, Type s)
operator.
template<typename Type >
Vec2< Type > operator- (const Vec2< Type > &v1, const Vec2< Type > &v2)
operator.
template<typename Type >
Vec2< Type > operator- (Type s, const Vec2< Type > &v)
operator.
template<typename Type >
Vec2< Type > operator- (const Vec2< Type > &v, Type s)
operator.
template<typename Type >
Vec4< Type > operator- (const Vec4< Type > &v1, const Vec4< Type > &v2)
operator.
template<typename Type >
Vec4< Type > operator- (Type s, const Vec4< Type > &v)
operator.
template<typename Type >
Vec4< Type > operator- (const Vec4< Type > &v, Type s)
operator.
template<typename Type >
Vec3< Type > operator/ (const Vec3< Type > &v1, const Vec3< Type > &v2)
/ operator.
template<typename Type >
Vec3< Type > operator/ (Type s, const Vec3< Type > &v)
/ operator.
template<typename Type >
Vec3< Type > operator/ (const Vec3< Type > &v, Type s)
/ operator.
template<typename Type >
Vec2< Type > operator/ (const Vec2< Type > &v1, const Vec2< Type > &v2)
/ operator.
template<typename Type >
Vec2< Type > operator/ (Type s, const Vec2< Type > &v)
/ operator.
template<typename Type >
Vec2< Type > operator/ (const Vec2< Type > &v, Type s)
/ operator.
template<typename Type >
Vec4< Type > operator/ (const Vec4< Type > &v1, const Vec4< Type > &v2)
/ operator.
template<typename Type >
Vec4< Type > operator/ (Type s, const Vec4< Type > &v)
/ operator.
template<typename Type >
Vec4< Type > operator/ (const Vec4< Type > &v, Type s)
/ operator.
template<typename T >
T pow2 (T value)
float radians (float degrees)
Convert a quantity in degrees to radians.
double radians (double degrees)
template<typename T >
Vec2< T > radians (const Vec2< T > &degrees)
template<typename T >
Vec3< T > radians (const Vec3< T > &degrees)
template<typename T >
Vec4< T > radians (const Vec4< T > &degrees)
Rectd RectdPS (double x, double y, double width, double height)
Rectf RectfPS (float x, float y, float width, float height)
Rect RectPS (int x, int y, int width, int height)
int sign (int x)
float sign (float x)
double sign (double x)
template<typename Type >
Vec2< Type > sign (const Vec2< Type > &x)
template<typename Type >
Vec3< Type > sign (const Vec3< Type > &x)
template<typename Type >
Vec4< Type > sign (const Vec4< Type > &x)
template<typename A , typename B , typename C >
C smoothstep (A edge0, B edge1, C x)
int step (int edge, int x)
long long step (long long edge, long long x)
float step (float edge, float x)
double step (double edge, double x)
template<typename Type >
Vec2< Type > step (const Vec2< Type > &edge, const Vec2< Type > &x)
template<typename Type >
Vec3< Type > step (const Vec3< Type > &edge, const Vec3< Type > &x)
template<typename Type >
Vec4< Type > step (const Vec4< Type > &edge, const Vec4< Type > &x)
std::string string_format (const std::string &format)
See uicore::StringFormat for details.
template<class Arg1 >
std::string string_format (const std::string &format, Arg1 arg1)
See uicore::StringFormat for details.
template<class Arg1 , class Arg2 >
std::string string_format (const std::string &format, Arg1 arg1, Arg2 arg2)
See uicore::StringFormat for details.
template<class Arg1 , class Arg2 , class Arg3 >
std::string string_format (const std::string &format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
See uicore::StringFormat for details.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 >
std::string string_format (const std::string &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
See uicore::StringFormat for details.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 >
std::string string_format (const std::string &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
See uicore::StringFormat for details.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 >
std::string string_format (const std::string &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
See uicore::StringFormat for details.
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 >
std::string string_format (const std::string &format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
See uicore::StringFormat for details.
Variables
const float PI = 3.14159274101257f
const double PI_D = 3.141592653589793115998
const float PI_F = 3.14159274101257f
Typedef Documentation
typedef std::shared_ptr<AES128_Decrypt> uicore::AES128_DecryptPtr
typedef std::shared_ptr<AES128_Encrypt> uicore::AES128_EncryptPtr
typedef std::shared_ptr<AES192_Decrypt> uicore::AES192_DecryptPtr
typedef std::shared_ptr<AES192_Encrypt> uicore::AES192_EncryptPtr
typedef std::shared_ptr<AES256_Decrypt> uicore::AES256_DecryptPtr
typedef std::shared_ptr<AES256_Encrypt> uicore::AES256_EncryptPtr
typedef std::shared_ptr< BlendState > uicore::BlendStatePtr
typedef std::shared_ptr< Canvas > uicore::CanvasPtr
typedef void* uicore::CLDEBUGPROC
typedef void* uicore::CLDEBUGPROCARB
typedef int64_t uicore::CLint64
typedef struct __CLsync* uicore::CLsync
typedef uint64_t uicore::CLuint64
typedef ColorHSLx<double, Colorf> uicore::ColorHSLd
typedef ColorHSLx<float, Colorf> uicore::ColorHSLf
typedef ColorHSLx<int, Color> uicore::ColorHSLi
typedef ColorHSVx<double, Colorf> uicore::ColorHSVd
typedef ColorHSVx<float, Colorf> uicore::ColorHSVf
typedef ColorHSVx<int, Color> uicore::ColorHSVi
typedef std::shared_ptr< Cursor > uicore::CursorPtr
typedef std::shared_ptr<DataBuffer> uicore::DataBufferPtr
typedef std::shared_ptr<DepthStencilState> uicore::DepthStencilStatePtr
typedef std::shared_ptr<DetectHang> uicore::DetectHangPtr
typedef std::shared_ptr< DisplayWindow > uicore::DisplayWindowPtr
typedef std::shared_ptr< ElementArrayBuffer > uicore::ElementArrayBufferPtr
typedef std::shared_ptr<File> uicore::FilePtr
typedef std::shared_ptr< FontFamily > uicore::FontFamilyPtr
typedef std::shared_ptr< Font > uicore::FontPtr
typedef std::shared_ptr< FrameBuffer > uicore::FrameBufferPtr
typedef unsigned int uicore::GLbitfield
typedef unsigned char uicore::GLboolean
typedef signed char uicore::GLbyte
typedef char uicore::GLchar
typedef double uicore::GLclampd
typedef float uicore::GLclampf
typedef double uicore::GLdouble
typedef unsigned int uicore::GLenum
typedef float uicore::GLfloat
typedef int uicore::GLint
typedef ptrdiff_t uicore::GLintptr
typedef short uicore::GLshort
typedef int uicore::GLsizei
typedef ptrdiff_t uicore::GLsizeiptr
typedef unsigned char uicore::GLubyte
typedef unsigned int uicore::GLuint
typedef unsigned short uicore::GLushort
typedef void uicore::GLvoid
typedef std::shared_ptr< GraphicContext > uicore::GraphicContextPtr
typedef std::shared_ptr<IconSet> uicore::IconSetPtr
typedef std::shared_ptr< Image > uicore::ImagePtr
typedef std::shared_ptr< InputDevice > uicore::InputDevicePtr
typedef std::shared_ptr< IODevice > uicore::IODevicePtr
typedef Mat2<double> uicore::Mat2d
typedef Mat2<float> uicore::Mat2f
typedef Mat2<int> uicore::Mat2i
typedef Mat3<double> uicore::Mat3d
typedef Mat3<float> uicore::Mat3f
typedef Mat3<int> uicore::Mat3i
typedef Mat4<double> uicore::Mat4d
typedef Mat4<float> uicore::Mat4f
typedef Mat4<int> uicore::Mat4i
typedef std::shared_ptr<MD5> uicore::MD5Ptr
typedef std::shared_ptr<MemoryDevice> uicore::MemoryDevicePtr
typedef std::shared_ptr<OcclusionQuery> uicore::OcclusionQueryPtr
typedef std::shared_ptr<Path> uicore::PathPtr
typedef std::shared_ptr<PerlinNoise> uicore::PerlinNoisePtr
typedef std::shared_ptr< PixelBuffer > uicore::PixelBufferPtr
typedef std::shared_ptr< PixelBufferSet > uicore::PixelBufferSetPtr
typedef std::shared_ptr< PixelConverter > uicore::PixelConverterPtr
typedef std::shared_ptr<PrimitivesArray> uicore::PrimitivesArrayPtr
typedef void(uicore::ProcAddress) ()
Extension procedure address typedef for OpenGL.
typedef std::shared_ptr< ProgramObject > uicore::ProgramObjectPtr
typedef Quaternionx<double> uicore::Quaterniond
typedef Quaternionx<float> uicore::Quaternionf
typedef std::shared_ptr<Random> uicore::RandomPtr
typedef std::shared_ptr<RasterizerState> uicore::RasterizerStatePtr
typedef std::shared_ptr<RegistryKey> uicore::RegistryKeyPtr
typedef std::shared_ptr< RenderBuffer > uicore::RenderBufferPtr
typedef std::shared_ptr<Secret> uicore::SecretPtr
typedef std::shared_ptr<SHA1> uicore::SHA1Ptr
typedef std::shared_ptr<SHA224> uicore::SHA224Ptr
typedef std::shared_ptr<SHA256> uicore::SHA256Ptr
typedef std::shared_ptr<SHA384> uicore::SHA384Ptr
typedef std::shared_ptr<SHA512_224> uicore::SHA512_224Ptr
typedef std::shared_ptr<SHA512_256> uicore::SHA512_256Ptr
typedef std::shared_ptr<SHA512> uicore::SHA512Ptr
typedef std::shared_ptr< ShaderObject > uicore::ShaderObjectPtr
typedef std::shared_ptr< StagingBuffer > uicore::StagingBufferPtr
typedef std::shared_ptr<StagingTexture> uicore::StagingTexturePtr
typedef std::shared_ptr< StorageBuffer > uicore::StorageBufferPtr
typedef std::shared_ptr<TCPConnection> uicore::TCPConnectionPtr
typedef std::shared_ptr<TCPListen> uicore::TCPListenPtr
typedef std::shared_ptr<TextBlock> uicore::TextBlockPtr
typedef std::shared_ptr<Texture1DArray> uicore::Texture1DArrayPtr
typedef std::shared_ptr<Texture1D> uicore::Texture1DPtr
typedef std::shared_ptr<Texture2DArray> uicore::Texture2DArrayPtr
typedef std::shared_ptr< Texture2D > uicore::Texture2DPtr
typedef std::shared_ptr<Texture3D> uicore::Texture3DPtr
typedef std::shared_ptr<TextureCube> uicore::TextureCubePtr
typedef std::shared_ptr<TextureGroup> uicore::TextureGroupPtr
typedef std::shared_ptr< Texture > uicore::TexturePtr
typedef std::shared_ptr<Timer> uicore::TimerPtr
typedef std::shared_ptr<TLSClient> uicore::TLSClientPtr
typedef std::shared_ptr<UDPSocket> uicore::UDPSocketPtr
typedef std::shared_ptr< UniformBuffer > uicore::UniformBufferPtr
typedef Vec2<char> uicore::Vec2b
typedef Vec2<double> uicore::Vec2d
typedef Vec2<float> uicore::Vec2f
typedef Vec2<int> uicore::Vec2i
typedef Vec2<short> uicore::Vec2s
typedef Vec2<unsigned char> uicore::Vec2ub
typedef Vec2<unsigned int> uicore::Vec2ui
typedef Vec2<unsigned short> uicore::Vec2us
typedef Vec3<char> uicore::Vec3b
typedef Vec3<double> uicore::Vec3d
typedef Vec3<float> uicore::Vec3f
typedef Vec3<int> uicore::Vec3i
typedef Vec3<short> uicore::Vec3s
typedef Vec3<unsigned char> uicore::Vec3ub
typedef Vec3<unsigned int> uicore::Vec3ui
typedef Vec3<unsigned short> uicore::Vec3us
typedef Vec4<char> uicore::Vec4b
typedef Vec4<double> uicore::Vec4d
typedef Vec4<float> uicore::Vec4f
typedef Vec4<int> uicore::Vec4i
typedef Vec4<short> uicore::Vec4s
typedef Vec4<unsigned char> uicore::Vec4ub
typedef Vec4<unsigned int> uicore::Vec4ui
typedef Vec4<unsigned short> uicore::Vec4us
typedef std::shared_ptr< VertexArrayBuffer > uicore::VertexArrayBufferPtr
typedef std::shared_ptr< XmlDocument > uicore::XmlDocumentPtr
typedef std::shared_ptr<XmlNode> uicore::XmlNodePtr
typedef std::string uicore::XmlString
typedef std::shared_ptr<XmlTokenizer> uicore::XmlTokenizerPtr
typedef std::shared_ptr<XmlWriter> uicore::XmlWriterPtr
Enumeration Type Documentation
enum uicore::ActivationChangeType strong
Window activation change.
Enumerator
activated
deactivated
Window was activated.
Window was deactivated
enum uicore::BlendEquation
Blending equations.
Enumerator
equation_add
equation_subtract
equation_reverse_subtract
equation_min
equation_max
enum uicore::BlendFunc
Blending functions.
Enumerator
blend_zero
source or destination (0, 0, 0, 0)
blend_one
source or destination (1, 1, 1, 1)
blend_dest_color
source (Rd, Gd, Bd, Ad)
blend_src_color
destination (Rs, Gs, Bs, As)
blend_one_minus_dest_color
source (1, 1, 1, 1) - (Rd, Gd, Bd, Ad)
blend_one_minus_src_color
destination (1, 1, 1, 1) - (Rs, Gs, Bs, As)
blend_src_alpha
source or destination (As, As, As, As)
blend_one_minus_src_alpha
source or destination (1, 1, 1, 1) - (As, As, As, As)
blend_dest_alpha
source or destination (Ad, Ad, Ad, Ad)
blend_one_minus_dest_alpha
source or destination (1, 1, 1, 1) - (Ad, Ad, Ad, Ad)
blend_src_alpha_saturate
source (f, f, f, 1) - f = min(As, 1 - Ad)
blend_constant_color
source or destination (Rc, Gc, Bc, Ac)
blend_one_minus_constant_color
source or destination (1, 1, 1, 1) - (Rc, Gc, Bc, Ac)
blend_constant_alpha
source or destination (Ac, Ac, Ac, Ac)
blend_one_minus_constant_alpha
source or destination (1, 1, 1, 1) - (Ac, Ac, Ac, Ac)
enum uicore::BrushInterpolateMode strong
Enumerator
nearest
linear
enum uicore::BrushType strong
Enumerator
solid
linear
radial
image
enum uicore::BrushWrapMode strong
Enumerator
clamp
wrap
mirror
enum uicore::BufferAccess
Array Buffer access enum.
Enumerator
access_read_only
access_write_only
access_read_write
access_write_discard
enum uicore::BufferUsage
Array Buffer usage enum.
Enumerator
usage_stream_draw
usage_stream_read
usage_stream_copy
usage_static_draw
usage_static_read
usage_static_copy
usage_dynamic_draw
usage_dynamic_read
usage_dynamic_copy
enum uicore::ByteOrderMark strong
Unicode byte order mark (BOM) types.
Enumerator
none
utf32_be
utf32_le
utf16_be
utf16_le
utf8
enum uicore::ClipZRange
Enumerator
clip_negative_positive_w
clip_zero_positive_w
enum uicore::CompareFunction
Compare functions.
Enumerator
compare_lequal
compare_gequal
compare_less
compare_greater
compare_equal
compare_notequal
compare_always
compare_never
enum uicore::ContentOverflow strong
Enumerator
hidden
scroll
automatic
enum uicore::CullMode
Polygon culling modes.
Enumerator
cull_front
cull_back
cull_front_and_back
enum uicore::DisplayDefines
Display Defines.
Enumerator
GL_DEPTH_BUFFER_BIT
GL_STENCIL_BUFFER_BIT
GL_COLOR_BUFFER_BIT
GL_FALSE
GL_TRUE
GL_POINTS
GL_LINES
GL_LINE_LOOP
GL_LINE_STRIP
GL_TRIANGLES
GL_TRIANGLE_STRIP
GL_TRIANGLE_FAN
GL_NEVER
GL_LESS
GL_EQUAL
GL_LEQUAL
GL_GREATER
GL_NOTEQUAL
GL_GEQUAL
GL_ALWAYS
GL_ZERO
GL_ONE
GL_SRC_COLOR
GL_ONE_MINUS_SRC_COLOR
GL_SRC_ALPHA
GL_ONE_MINUS_SRC_ALPHA
GL_DST_ALPHA
GL_ONE_MINUS_DST_ALPHA
GL_DST_COLOR
GL_ONE_MINUS_DST_COLOR
GL_SRC_ALPHA_SATURATE
GL_NONE
GL_FRONT_LEFT
GL_FRONT_RIGHT
GL_BACK_LEFT
GL_BACK_RIGHT
GL_FRONT
GL_BACK
GL_LEFT
GL_RIGHT
GL_FRONT_AND_BACK
GL_NO_ERROR
GL_INVALID_ENUM
GL_INVALID_VALUE
GL_INVALID_OPERATION
GL_OUT_OF_MEMORY
GL_CW
GL_CCW
GL_POINT_SIZE
GL_POINT_SIZE_RANGE
GL_POINT_SIZE_GRANULARITY
GL_LINE_SMOOTH
GL_LINE_WIDTH
GL_LINE_WIDTH_RANGE
GL_LINE_WIDTH_GRANULARITY
GL_POLYGON_SMOOTH
GL_CULL_FACE
GL_CULL_FACE_MODE
GL_FRONT_FACE
GL_DEPTH_RANGE
GL_DEPTH_TEST
GL_DEPTH_WRITEMASK
GL_DEPTH_CLEAR_VALUE
GL_DEPTH_FUNC
GL_STENCIL_TEST
GL_STENCIL_CLEAR_VALUE
GL_STENCIL_FUNC
GL_STENCIL_VALUE_MASK
GL_STENCIL_FAIL
GL_STENCIL_PASS_DEPTH_FAIL
GL_STENCIL_PASS_DEPTH_PASS
GL_STENCIL_REF
GL_STENCIL_WRITEMASK
GL_VIEWPORT
GL_DITHER
GL_BLEND_DST
GL_BLEND_SRC
GL_BLEND
GL_LOGIC_OP_MODE
GL_COLOR_LOGIC_OP
GL_DRAW_BUFFER
GL_READ_BUFFER
GL_SCISSOR_BOX
GL_SCISSOR_TEST
GL_COLOR_CLEAR_VALUE
GL_COLOR_WRITEMASK
GL_DOUBLEBUFFER
GL_STEREO
GL_LINE_SMOOTH_HINT
GL_POLYGON_SMOOTH_HINT
GL_UNPACK_SWAP_BYTES
GL_UNPACK_LSB_FIRST
GL_UNPACK_ROW_LENGTH
GL_UNPACK_SKIP_ROWS
GL_UNPACK_SKIP_PIXELS
GL_UNPACK_ALIGNMENT
GL_PACK_SWAP_BYTES
GL_PACK_LSB_FIRST
GL_PACK_ROW_LENGTH
GL_PACK_SKIP_ROWS
GL_PACK_SKIP_PIXELS
GL_PACK_ALIGNMENT
GL_MAX_TEXTURE_SIZE
GL_MAX_VIEWPORT_DIMS
GL_SUBCL_PIXEL_BITS
GL_TEXTURE_1D
GL_TEXTURE_2D
GL_POLYGON_OFFSET_UNITS
GL_POLYGON_OFFSET_POINT
GL_POLYGON_OFFSET_LINE
GL_POLYGON_OFFSET_FILL
GL_POLYGON_OFFSET_FACTOR
GL_TEXTURE_BINDING_1D
GL_TEXTURE_BINDING_2D
GL_TEXTURE_WIDTH
GL_TEXTURE_HEIGHT
GL_TEXTURE_INTERNAL_FORMAT
GL_TEXTURE_BORDER_COLOR
GL_TEXTURE_RED_SIZE
GL_TEXTURE_GREEN_SIZE
GL_TEXTURE_BLUE_SIZE
GL_TEXTURE_ALPHA_SIZE
GL_DONT_CARE
GL_FASTEST
GL_NICEST
GL_BYTE
GL_UNSIGNED_BYTE
GL_SHORT
GL_UNSIGNED_SHORT
GL_INT
GL_UNSIGNED_INT
GL_FLOAT
GL_DOUBLE
GL_STACK_OVERFLOW
GL_STACK_UNDERFLOW
GL_CLEAR
GL_AND
GL_AND_REVERSE
GL_COPY
GL_AND_INVERTED
GL_NOOP
GL_XOR
GL_OR
GL_NOR
GL_EQUIV
GL_INVERT
GL_OR_REVERSE
GL_COPY_INVERTED
GL_OR_INVERTED
GL_NAND
GL_SET
GL_TEXTURE
GL_COLOR
GL_DEPTH
GL_STENCIL
GL_STENCIL_INDEX
GL_DEPTH_COMPONENT
GL_RED
GL_GREEN
GL_BLUE
GL_ALPHA
GL_RGB
GL_RGBA
GL_POINT
GL_LINE
GL_FILL
GL_KEEP
GL_REPLACE
GL_INCR
GL_DECR
GL_VENDOR
GL_RENDERER
GL_VERSION
GL_EXTENSIONS
GL_NEAREST
GL_LINEAR
GL_NEAREST_MIPMAP_NEAREST
GL_LINEAR_MIPMAP_NEAREST
GL_NEAREST_MIPMAP_LINEAR
GL_LINEAR_MIPMAP_LINEAR
GL_TEXTURE_MAG_FILTER
GL_TEXTURE_MIN_FILTER
GL_TEXTURE_WRAP_S
GL_TEXTURE_WRAP_T
GL_PROXY_TEXTURE_1D
GL_PROXY_TEXTURE_2D
GL_REPEAT
GL_R3_G3_B2
GL_RGB4
GL_RGB5
GL_RGB8
GL_RGB10
GL_RGB12
GL_RGB16
GL_RGBA2
GL_RGBA4
GL_RGB5_A1
GL_RGBA8
GL_RGB10_A2
GL_RGBA12
GL_RGBA16
GL_UNSIGNED_BYTE_3_3_2
GL_UNSIGNED_SHORT_4_4_4_4
GL_UNSIGNED_SHORT_5_5_5_1
GL_UNSIGNED_INT_8_8_8_8
GL_UNSIGNED_INT_10_10_10_2
GL_TEXTURE_BINDING_3D
GL_PACK_SKIP_IMAGES
GL_PACK_IMAGE_HEIGHT
GL_UNPACK_SKIP_IMAGES
GL_UNPACK_IMAGE_HEIGHT
GL_TEXTURE_3D
GL_PROXY_TEXTURE_3D
GL_TEXTURE_DEPTH
GL_TEXTURE_WRAP_R
GL_MAX_3D_TEXTURE_SIZE
GL_UNSIGNED_BYTE_2_3_3_REV
GL_UNSIGNED_SHORT_5_6_5
GL_UNSIGNED_SHORT_5_6_5_REV
GL_UNSIGNED_SHORT_4_4_4_4_REV
GL_UNSIGNED_SHORT_1_5_5_5_REV
GL_UNSIGNED_INT_8_8_8_8_REV
GL_UNSIGNED_INT_2_10_10_10_REV
GL_BGR
GL_BGRA
GL_MAX_ELEMENTS_VERTICES
GL_MAX_ELEMENTS_INDICES
GL_CLAMP_TO_EDGE
GL_TEXTURE_MIN_LOD
GL_TEXTURE_MAX_LOD
GL_TEXTURE_BASE_LEVEL
GL_TEXTURE_MAX_LEVEL
GL_SMOOTH_POINT_SIZE_RANGE
GL_SMOOTH_POINT_SIZE_GRANULARITY
GL_SMOOTH_LINE_WIDTH_RANGE
GL_SMOOTH_LINE_WIDTH_GRANULARITY
GL_ALIASED_LINE_WIDTH_RANGE
GL_CONSTANT_COLOR
GL_ONE_MINUS_CONSTANT_COLOR
GL_CONSTANT_ALPHA
GL_ONE_MINUS_CONSTANT_ALPHA
GL_BLEND_COLOR
GL_FUNC_ADD
GL_MIN
GL_MAX
GL_BLEND_EQUATION
GL_FUNC_SUBTRACT
GL_FUNC_REVERSE_SUBTRACT
GL_TEXTURE0
GL_TEXTURE1
GL_TEXTURE2
GL_TEXTURE3
GL_TEXTURE4
GL_TEXTURE5
GL_TEXTURE6
GL_TEXTURE7
GL_TEXTURE8
GL_TEXTURE9
GL_TEXTURE10
GL_TEXTURE11
GL_TEXTURE12
GL_TEXTURE13
GL_TEXTURE14
GL_TEXTURE15
GL_TEXTURE16
GL_TEXTURE17
GL_TEXTURE18
GL_TEXTURE19
GL_TEXTURE20
GL_TEXTURE21
GL_TEXTURE22
GL_TEXTURE23
GL_TEXTURE24
GL_TEXTURE25
GL_TEXTURE26
GL_TEXTURE27
GL_TEXTURE28
GL_TEXTURE29
GL_TEXTURE30
GL_TEXTURE31
GL_ACTIVE_TEXTURE
GL_MULTISAMPLE
GL_SAMPLE_ALPHA_TO_COVERAGE
GL_SAMPLE_ALPHA_TO_ONE
GL_SAMPLE_COVERAGE
GL_SAMPLE_BUFFERS
GL_SAMPLES
GL_SAMPLE_COVERAGE_VALUE
GL_SAMPLE_COVERAGE_INVERT
GL_TEXTURE_CUBE_MAP
GL_TEXTURE_BINDING_CUBE_MAP
GL_TEXTURE_CUBE_MAP_POSITIVE_X
GL_TEXTURE_CUBE_MAP_NEGATIVE_X
GL_TEXTURE_CUBE_MAP_POSITIVE_Y
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
GL_TEXTURE_CUBE_MAP_POSITIVE_Z
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
GL_PROXY_TEXTURE_CUBE_MAP
GL_MAX_CUBE_MAP_TEXTURE_SIZE
GL_COMPRESSED_RGB
GL_COMPRESSED_RGBA
GL_TEXTURE_COMPRESSION_HINT
GL_TEXTURE_COMPRESSED_IMAGE_SIZE
GL_TEXTURE_COMPRESSED
GL_NUM_COMPRESSED_TEXTURE_FORMATS
GL_COMPRESSED_TEXTURE_FORMATS
GL_CLAMP_TO_BORDER
GL_BLEND_DST_RGB
GL_BLEND_SRC_RGB
GL_BLEND_DST_ALPHA
GL_BLEND_SRC_ALPHA
GL_POINT_FADE_THRESHOLD_SIZE
GL_DEPTH_COMPONENT16
GL_DEPTH_COMPONENT24
GL_DEPTH_COMPONENT32
GL_MIRRORED_REPEAT
GL_MAX_TEXTURE_LOD_BIAS
GL_TEXTURE_LOD_BIAS
GL_INCR_WRAP
GL_DECR_WRAP
GL_TEXTURE_DEPTH_SIZE
GL_TEXTURE_COMPARE_MODE
GL_TEXTURE_COMPARE_FUNC
GL_BUFFER_SIZE
GL_BUFFER_USAGE
GL_QUERY_COUNTER_BITS
GL_CURRENT_QUERY
GL_QUERY_RESULT
GL_QUERY_RESULT_AVAILABLE
GL_ARRAY_BUFFER
GL_ELEMENT_ARRAY_BUFFER
GL_ARRAY_BUFFER_BINDING
GL_ELEMENT_ARRAY_BUFFER_BINDING
GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
GL_READ_ONLY
GL_WRITE_ONLY
GL_READ_WRITE
GL_BUFFER_ACCESS
GL_BUFFER_MAPPED
GL_BUFFER_MAP_POINTER
GL_STREAM_DRAW
GL_STREAM_READ
GL_STREAM_COPY
GL_STATIC_DRAW
GL_STATIC_READ
GL_STATIC_COPY
GL_DYNAMIC_DRAW
GL_DYNAMIC_READ
GL_DYNAMIC_COPY
GL_SAMPLES_PASSED
GL_BLEND_EQUATION_RGB
GL_VERTEX_ATTRIB_ARRAY_ENABLED
GL_VERTEX_ATTRIB_ARRAY_SIZE
GL_VERTEX_ATTRIB_ARRAY_STRIDE
GL_VERTEX_ATTRIB_ARRAY_TYPE
GL_CURRENT_VERTEX_ATTRIB
GL_VERTEX_PROGRAM_POINT_SIZE
GL_VERTEX_ATTRIB_ARRAY_POINTER
GL_STENCIL_BACK_FUNC
GL_STENCIL_BACK_FAIL
GL_STENCIL_BACK_PASS_DEPTH_FAIL
GL_STENCIL_BACK_PASS_DEPTH_PASS
GL_MAX_DRAW_BUFFERS
GL_DRAW_BUFFER0
GL_DRAW_BUFFER1
GL_DRAW_BUFFER2
GL_DRAW_BUFFER3
GL_DRAW_BUFFER4
GL_DRAW_BUFFER5
GL_DRAW_BUFFER6
GL_DRAW_BUFFER7
GL_DRAW_BUFFER8
GL_DRAW_BUFFER9
GL_DRAW_BUFFER10
GL_DRAW_BUFFER11
GL_DRAW_BUFFER12
GL_DRAW_BUFFER13
GL_DRAW_BUFFER14
GL_DRAW_BUFFER15
GL_BLEND_EQUATION_ALPHA
GL_MAX_VERTEX_ATTRIBS
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
GL_MAX_TEXTURE_IMAGE_UNITS
GL_FRAGMENT_SHADER
GL_VERTEX_SHADER
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS
GL_MAX_VERTEX_UNIFORM_COMPONENTS
GL_MAX_VARYING_FLOATS
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
GL_SHADER_TYPE
GL_FLOAT_VEC2
GL_FLOAT_VEC3
GL_FLOAT_VEC4
GL_INT_VEC2
GL_INT_VEC3
GL_INT_VEC4
GL_BOOL
GL_BOOL_VEC2
GL_BOOL_VEC3
GL_BOOL_VEC4
GL_FLOAT_MAT2
GL_FLOAT_MAT3
GL_FLOAT_MAT4
GL_SAMPLER_1D
GL_SAMPLER_2D
GL_SAMPLER_3D
GL_SAMPLER_CUBE
GL_SAMPLER_1D_SHADOW
GL_SAMPLER_2D_SHADOW
GL_DELETE_STATUS
GL_COMPILE_STATUS
GL_LINK_STATUS
GL_VALIDATE_STATUS
GL_INFO_LOG_LENGTH
GL_ATTACHED_SHADERS
GL_ACTIVE_UNIFORMS
GL_ACTIVE_UNIFORM_MAX_LENGTH
GL_SHADER_SOURCE_LENGTH
GL_ACTIVE_ATTRIBUTES
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
GL_FRAGMENT_SHADER_DERIVATIVE_HINT
GL_SHADING_LANGUAGE_VERSION
GL_CURRENT_PROGRAM
GL_POINT_SPRITE_COORD_ORIGIN
GL_LOWER_LEFT
GL_UPPER_LEFT
GL_STENCIL_BACK_REF
GL_STENCIL_BACK_VALUE_MASK
GL_STENCIL_BACK_WRITEMASK
GL_PIXEL_PACK_BUFFER
GL_PIXEL_UNPACK_BUFFER
GL_PIXEL_PACK_BUFFER_BINDING
GL_PIXEL_UNPACK_BUFFER_BINDING
GL_FLOAT_MAT2x3
GL_FLOAT_MAT2x4
GL_FLOAT_MAT3x2
GL_FLOAT_MAT3x4
GL_FLOAT_MAT4x2
GL_FLOAT_MAT4x3
GL_SRGB
GL_SRGB8
GL_SRGB_ALPHA
GL_SRGB8_ALPHA8
GL_COMPRESSED_SRGB
GL_COMPRESSED_SRGB_ALPHA
GL_COMPARE_REF_TO_TEXTURE
GL_CLIP_DISTANCE0
GL_CLIP_DISTANCE1
GL_CLIP_DISTANCE2
GL_CLIP_DISTANCE3
GL_CLIP_DISTANCE4
GL_CLIP_DISTANCE5
GL_CLIP_DISTANCE6
GL_CLIP_DISTANCE7
GL_MAX_CLIP_DISTANCES
GL_MAJOR_VERSION
GL_MINOR_VERSION
GL_NUM_EXTENSIONS
GL_CONTEXT_FLAGS
GL_COMPRESSED_RED
GL_COMPRESSED_RG
GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT
GL_RGBA32F
GL_RGB32F
GL_RGBA16F
GL_RGB16F
GL_VERTEX_ATTRIB_ARRAY_INTEGER
GL_MAX_ARRAY_TEXTURE_LAYERS
GL_MIN_PROGRAM_TEXEL_OFFSET
GL_MAX_PROGRAM_TEXEL_OFFSET
GL_CLAMP_READ_COLOR
GL_FIXED_ONLY
GL_MAX_VARYING_COMPONENTS
GL_TEXTURE_1D_ARRAY
GL_PROXY_TEXTURE_1D_ARRAY
GL_TEXTURE_2D_ARRAY
GL_PROXY_TEXTURE_2D_ARRAY
GL_TEXTURE_BINDING_1D_ARRAY
GL_TEXTURE_BINDING_2D_ARRAY
GL_R11F_G11F_B10F
GL_UNSIGNED_INT_10F_11F_11F_REV
GL_RGB9_E5
GL_UNSIGNED_INT_5_9_9_9_REV
GL_TEXTURE_SHARED_SIZE
GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH
GL_TRANSFORM_FEEDBACK_BUFFER_MODE
GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS
GL_TRANSFORM_FEEDBACK_VARYINGS
GL_TRANSFORM_FEEDBACK_BUFFER_START
GL_TRANSFORM_FEEDBACK_BUFFER_SIZE
GL_PRIMITIVES_GENERATED
GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN
GL_RASTERIZER_DISCARD
GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS
GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS
GL_INTERLEAVED_ATTRIBS
GL_SEPARATE_ATTRIBS
GL_TRANSFORM_FEEDBACK_BUFFER
GL_TRANSFORM_FEEDBACK_BUFFER_BINDING
GL_RGBA32UI
GL_RGB32UI
GL_RGBA16UI
GL_RGB16UI
GL_RGBA8UI
GL_RGB8UI
GL_RGBA32I
GL_RGB32I
GL_RGBA16I
GL_RGB16I
GL_RGBA8I
GL_RGB8I
GL_RED_INTEGER
GL_GREEN_INTEGER
GL_BLUE_INTEGER
GL_RGB_INTEGER
GL_RGBA_INTEGER
GL_BGR_INTEGER
GL_BGRA_INTEGER
GL_SAMPLER_1D_ARRAY
GL_SAMPLER_2D_ARRAY
GL_SAMPLER_1D_ARRAY_SHADOW
GL_SAMPLER_2D_ARRAY_SHADOW
GL_SAMPLER_CUBE_SHADOW
GL_UNSIGNED_INT_VEC2
GL_UNSIGNED_INT_VEC3
GL_UNSIGNED_INT_VEC4
GL_INT_SAMPLER_1D
GL_INT_SAMPLER_2D
GL_INT_SAMPLER_3D
GL_INT_SAMPLER_CUBE
GL_INT_SAMPLER_1D_ARRAY
GL_INT_SAMPLER_2D_ARRAY
GL_UNSIGNED_INT_SAMPLER_1D
GL_UNSIGNED_INT_SAMPLER_2D
GL_UNSIGNED_INT_SAMPLER_3D
GL_UNSIGNED_INT_SAMPLER_CUBE
GL_UNSIGNED_INT_SAMPLER_1D_ARRAY
GL_UNSIGNED_INT_SAMPLER_2D_ARRAY
GL_QUERY_WAIT
GL_QUERY_NO_WAIT
GL_QUERY_BY_REGION_WAIT
GL_QUERY_BY_REGION_NO_WAIT
GL_BUFFER_ACCESS_FLAGS
GL_BUFFER_MAP_LENGTH
GL_BUFFER_MAP_OFFSET
GL_SAMPLER_2D_RECT
GL_SAMPLER_2D_RECT_SHADOW
GL_SAMPLER_BUFFER
GL_INT_SAMPLER_2D_RECT
GL_INT_SAMPLER_BUFFER
GL_UNSIGNED_INT_SAMPLER_2D_RECT
GL_UNSIGNED_INT_SAMPLER_BUFFER
GL_TEXTURE_BUFFER
GL_MAX_TEXTURE_BUFFER_SIZE
GL_TEXTURE_BINDING_BUFFER
GL_TEXTURE_BUFFER_DATA_STORE_BINDING
GL_TEXTURE_BUFFER_FORMAT
GL_TEXTURE_RECTANGLE
GL_TEXTURE_BINDING_RECTANGLE
GL_PROXY_TEXTURE_RECTANGLE
GL_MAX_RECTANGLE_TEXTURE_SIZE
GL_RED_SNORM
GL_RG_SNORM
GL_RGB_SNORM
GL_RGBA_SNORM
GL_R8_SNORM
GL_RG8_SNORM
GL_RGB8_SNORM
GL_RGBA8_SNORM
GL_R16_SNORM
GL_RG16_SNORM
GL_RGB16_SNORM
GL_RGBA16_SNORM
GL_SIGNED_NORMALIZED
GL_PRIMITIVE_RESTART
GL_PRIMITIVE_RESTART_INDEX
GL_CONTEXT_CORE_PROFILE_BIT
GL_CONTEXT_COMPATIBILITY_PROFILE_BIT
GL_LINES_ADJACENCY
GL_LINE_STRIP_ADJACENCY
GL_TRIANGLES_ADJACENCY
GL_TRIANGLE_STRIP_ADJACENCY
GL_PROGRAM_POINT_SIZE
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS
GL_FRAMEBUFFER_ATTACHMENT_LAYERED
GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS
GL_GEOMETRY_SHADER
GL_GEOMETRY_VERTICES_OUT
GL_GEOMETRY_INPUT_TYPE
GL_GEOMETRY_OUTPUT_TYPE
GL_MAX_GEOMETRY_UNIFORM_COMPONENTS
GL_MAX_GEOMETRY_OUTPUT_VERTICES
GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS
GL_MAX_VERTEX_OUTPUT_COMPONENTS
GL_MAX_GEOMETRY_INPUT_COMPONENTS
GL_MAX_GEOMETRY_OUTPUT_COMPONENTS
GL_MAX_FRAGMENT_INPUT_COMPONENTS
GL_CONTEXT_PROFILE_MASK
GL_VERTEX_ATTRIB_ARRAY_DIVISOR
GL_SAMPLE_SHADING
GL_MIN_SAMPLE_SHADING_VALUE
GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET
GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET
GL_TEXTURE_CUBE_MAP_ARRAY
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY
GL_PROXY_TEXTURE_CUBE_MAP_ARRAY
GL_SAMPLER_CUBE_MAP_ARRAY
GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW
GL_INT_SAMPLER_CUBE_MAP_ARRAY
GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY
GL_NUM_SHADING_LANGUAGE_VERSIONS
GL_VERTEX_ATTRIB_ARRAY_LONG
GL_DEPTH_COMPONENT32F
GL_DEPTH32F_STENCIL8
GL_FLOAT_32_UNSIGNED_INT_24_8_REV
GL_INVALID_FRAMEBUFFER_OPERATION
GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING
GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE
GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE
GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE
GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE
GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE
GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE
GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE
GL_FRAMEBUFFER_DEFAULT
GL_FRAMEBUFFER_UNDEFINED
GL_DEPTH_STENCIL_ATTACHMENT
GL_MAX_RENDERBUFFER_SIZE
GL_DEPTH_STENCIL
GL_UNSIGNED_INT_24_8
GL_DEPTH24_STENCIL8
GL_TEXTURE_STENCIL_SIZE
GL_TEXTURE_RED_TYPE
GL_TEXTURE_GREEN_TYPE
GL_TEXTURE_BLUE_TYPE
GL_TEXTURE_ALPHA_TYPE
GL_TEXTURE_DEPTH_TYPE
GL_UNSIGNED_NORMALIZED
GL_FRAMEBUFFER_BINDING
GL_DRAW_FRAMEBUFFER_BINDING
GL_RENDERBUFFER_BINDING
GL_READ_FRAMEBUFFER
GL_DRAW_FRAMEBUFFER
GL_READ_FRAMEBUFFER_BINDING
GL_RENDERBUFFER_SAMPLES
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER
GL_FRAMEBUFFER_COMPLETE
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER
GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER
GL_FRAMEBUFFER_UNSUPPORTED
GL_MAX_COLOR_ATTACHMENTS
GL_COLOR_ATTACHMENT0
GL_COLOR_ATTACHMENT1
GL_COLOR_ATTACHMENT2
GL_COLOR_ATTACHMENT3
GL_COLOR_ATTACHMENT4
GL_COLOR_ATTACHMENT5
GL_COLOR_ATTACHMENT6
GL_COLOR_ATTACHMENT7
GL_COLOR_ATTACHMENT8
GL_COLOR_ATTACHMENT9
GL_COLOR_ATTACHMENT10
GL_COLOR_ATTACHMENT11
GL_COLOR_ATTACHMENT12
GL_COLOR_ATTACHMENT13
GL_COLOR_ATTACHMENT14
GL_COLOR_ATTACHMENT15
GL_DEPTH_ATTACHMENT
GL_STENCIL_ATTACHMENT
GL_FRAMEBUFFER
GL_RENDERBUFFER
GL_RENDERBUFFER_WIDTH
GL_RENDERBUFFER_HEIGHT
GL_RENDERBUFFER_INTERNAL_FORMAT
GL_STENCIL_INDEX1
GL_STENCIL_INDEX4
GL_STENCIL_INDEX8
GL_STENCIL_INDEX16
GL_RENDERBUFFER_RED_SIZE
GL_RENDERBUFFER_GREEN_SIZE
GL_RENDERBUFFER_BLUE_SIZE
GL_RENDERBUFFER_ALPHA_SIZE
GL_RENDERBUFFER_DEPTH_SIZE
GL_RENDERBUFFER_STENCIL_SIZE
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE
GL_MAX_SAMPLES
GL_FRAMEBUFFER_SRGB
GL_HALF_FLOAT
GL_MAP_READ_BIT
GL_MAP_WRITE_BIT
GL_MAP_INVALIDATE_RANGE_BIT
GL_MAP_INVALIDATE_BUFFER_BIT
GL_MAP_FLUSH_EXPLICIT_BIT
GL_MAP_UNSYNCHRONIZED_BIT
GL_COMPRESSED_RED_RGTC1
GL_COMPRESSED_SIGNED_RED_RGTC1
GL_COMPRESSED_RG_RGTC2
GL_COMPRESSED_SIGNED_RG_RGTC2
GL_RG
GL_RG_INTEGER
GL_R8
GL_R16
GL_RG8
GL_RG16
GL_R16F
GL_R32F
GL_RG16F
GL_RG32F
GL_R8I
GL_R8UI
GL_R16I
GL_R16UI
GL_R32I
GL_R32UI
GL_RG8I
GL_RG8UI
GL_RG16I
GL_RG16UI
GL_RG32I
GL_RG32UI
GL_VERTEX_ARRAY_BINDING
GL_UNIFORM_BUFFER
GL_UNIFORM_BUFFER_BINDING
GL_UNIFORM_BUFFER_START
GL_UNIFORM_BUFFER_SIZE
GL_MAX_VERTEX_UNIFORM_BLOCKS
GL_MAX_GEOMETRY_UNIFORM_BLOCKS
GL_MAX_FRAGMENT_UNIFORM_BLOCKS
GL_MAX_COMBINED_UNIFORM_BLOCKS
GL_MAX_UNIFORM_BUFFER_BINDINGS
GL_MAX_UNIFORM_BLOCK_SIZE
GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS
GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS
GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS
GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT
GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH
GL_ACTIVE_UNIFORM_BLOCKS
GL_UNIFORM_TYPE
GL_UNIFORM_SIZE
GL_UNIFORM_NAME_LENGTH
GL_UNIFORM_BLOCK_INDEX
GL_UNIFORM_OFFSET
GL_UNIFORM_ARRAY_STRIDE
GL_UNIFORM_MATRIX_STRIDE
GL_UNIFORM_IS_ROW_MAJOR
GL_UNIFORM_BLOCK_BINDING
GL_UNIFORM_BLOCK_DATA_SIZE
GL_UNIFORM_BLOCK_NAME_LENGTH
GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS
GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES
GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER
GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER
GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER
GL_INVALID_INDEX
GL_COPY_READ_BUFFER_BINDING
GL_COPY_READ_BUFFER
GL_COPY_WRITE_BUFFER_BINDING
GL_COPY_WRITE_BUFFER
GL_DEPTH_CLAMP
GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION
GL_FIRST_VERTEX_CONVENTION
GL_LAST_VERTEX_CONVENTION
GL_PROVOKING_VERTEX
GL_TEXTURE_CUBE_MAP_SEAMLESS
GL_MAX_SERVER_WAIT_TIMEOUT
GL_OBJECT_TYPE
GL_SYNC_CONDITION
GL_SYNC_STATUS
GL_SYNC_FLAGS
GL_SYNC_FENCE
GL_SYNC_GPU_COMMANDS_COMPLETE
GL_UNSIGNALED
GL_SIGNALED
GL_ALREADY_SIGNALED
GL_TIMEOUT_EXCL_PIRED
GL_CONDITION_SATISFIED
GL_WAIT_FAILED
GL_SYNC_FLUSH_COMMANDS_BIT
GL_TIMEOUT_IGNORED
GL_SAMPLE_POSITION
GL_SAMPLE_MASK
GL_SAMPLE_MASK_VALUE
GL_MAX_SAMPLE_MASK_WORDS
GL_TEXTURE_2D_MULTISAMPLE
GL_PROXY_TEXTURE_2D_MULTISAMPLE
GL_TEXTURE_2D_MULTISAMPLE_ARRAY
GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY
GL_TEXTURE_BINDING_2D_MULTISAMPLE
GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY
GL_TEXTURE_SAMPLES
GL_TEXTURE_FIXED_SAMPLE_LOCATIONS
GL_SAMPLER_2D_MULTISAMPLE
GL_INT_SAMPLER_2D_MULTISAMPLE
GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE
GL_SAMPLER_2D_MULTISAMPLE_ARRAY
GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
GL_MAX_COLOR_TEXTURE_SAMPLES
GL_MAX_DEPTH_TEXTURE_SAMPLES
GL_MAX_INTEGER_SAMPLES
GL_SAMPLE_SHADING_ARB
GL_MIN_SAMPLE_SHADING_VALUE_ARB
GL_TEXTURE_CUBE_MAP_ARRAY_ARB
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY_ARB
GL_PROXY_TEXTURE_CUBE_MAP_ARRAY_ARB
GL_SAMPLER_CUBE_MAP_ARRAY_ARB
GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW_ARB
GL_INT_SAMPLER_CUBE_MAP_ARRAY_ARB
GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_ARB
GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB
GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB
GL_SHADER_INCLUDE_ARB
GL_NAMED_STRING_LENGTH_ARB
GL_NAMED_STRING_TYPE_ARB
GL_COMPRESSED_RGBA_BPTC_UNORM_ARB
GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB
GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB
GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_ARB
GL_SRC1_COLOR
GL_ONE_MINUS_SRC1_COLOR
GL_ONE_MINUS_SRC1_ALPHA
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS
GL_ANY_SAMPLES_PASSED
GL_SAMPLER_BINDING
GL_RGB10_A2UI
GL_TEXTURE_SWIZZLE_R
GL_TEXTURE_SWIZZLE_G
GL_TEXTURE_SWIZZLE_B
GL_TEXTURE_SWIZZLE_A
GL_TEXTURE_SWIZZLE_RGBA
GL_TIME_ELAPSED
GL_TIMESTAMP
GL_INT_2_10_10_10_REV
GL_DRAW_INDIRECT_BUFFER
GL_DRAW_INDIRECT_BUFFER_BINDING
GL_GEOMETRY_SHADER_INVOCATIONS
GL_MAX_GEOMETRY_SHADER_INVOCATIONS
GL_MIN_FRAGMENT_INTERPOLATION_OFFSET
GL_MAX_FRAGMENT_INTERPOLATION_OFFSET
GL_FRAGMENT_INTERPOLATION_OFFSET_BITS
GL_DOUBLE_VEC2
GL_DOUBLE_VEC3
GL_DOUBLE_VEC4
GL_DOUBLE_MAT2
GL_DOUBLE_MAT3
GL_DOUBLE_MAT4
GL_DOUBLE_MAT2x3
GL_DOUBLE_MAT2x4
GL_DOUBLE_MAT3x2
GL_DOUBLE_MAT3x4
GL_DOUBLE_MAT4x2
GL_DOUBLE_MAT4x3
GL_ACTIVE_SUBROUTINES
GL_ACTIVE_SUBROUTINE_UNIFORMS
GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS
GL_ACTIVE_SUBROUTINE_MAX_LENGTH
GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH
GL_MAX_SUBROUTINES
GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS
GL_NUM_COMPATIBLE_SUBROUTINES
GL_COMPATIBLE_SUBROUTINES
GL_PATCHES
GL_PATCH_VERTICES
GL_PATCH_DEFAULT_INNER_LEVEL
GL_PATCH_DEFAULT_OUTER_LEVEL
GL_TESS_CONTROL_OUTPUT_VERTICES
GL_TESS_GEN_MODE
GL_TESS_GEN_SPACING
GL_TESS_GEN_VERTEX_ORDER
GL_TESS_GEN_POINT_MODE
GL_ISOLINES
GL_FRACTIONAL_ODD
GL_FRACTIONAL_EVEN
GL_MAX_PATCH_VERTICES
GL_MAX_TESS_GEN_LEVEL
GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS
GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS
GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS
GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS
GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS
GL_MAX_TESS_PATCH_COMPONENTS
GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS
GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS
GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS
GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS
GL_MAX_TESS_CONTROL_INPUT_COMPONENTS
GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS
GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS
GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER
GL_TESS_EVALUATION_SHADER
GL_TESS_CONTROL_SHADER
GL_TRANSFORM_FEEDBACK
GL_TRANSFORM_FEEDBACK_PAUSED
GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED
GL_TRANSFORM_FEEDBACK_ACTIVE
GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE
GL_TRANSFORM_FEEDBACK_BINDING
GL_MAX_TRANSFORM_FEEDBACK_BUFFERS
GL_MAX_VERTEX_STREAMS
GL_FIXED
GL_IMPLEMENTATION_COLOR_READ_TYPE
GL_IMPLEMENTATION_COLOR_READ_FORMAT
GL_LOW_FLOAT
GL_MEDIUM_FLOAT
GL_HIGH_FLOAT
GL_LOW_INT
GL_MEDIUM_INT
GL_HIGH_INT
GL_SHADER_COMPILER
GL_NUM_SHADER_BINARY_FORMATS
GL_MAX_VERTEX_UNIFORM_VECTORS
GL_MAX_VARYING_VECTORS
GL_MAX_FRAGMENT_UNIFORM_VECTORS
GL_RGB565
GL_PROGRAM_BINARY_RETRIEVABLE_HINT
GL_PROGRAM_BINARY_LENGTH
GL_NUM_PROGRAM_BINARY_FORMATS
GL_PROGRAM_BINARY_FORMATS
GL_VERTEX_SHADER_BIT
GL_FRAGMENT_SHADER_BIT
GL_GEOMETRY_SHADER_BIT
GL_TESS_CONTROL_SHADER_BIT
GL_TESS_EVALUATION_SHADER_BIT
GL_ALL_SHADER_BITS
GL_PROGRAM_SEPARABLE
GL_ACTIVE_PROGRAM
GL_PROGRAM_PIPELINE_BINDING
GL_MAX_VIEWPORTS
GL_VIEWPORT_SUBCL_PIXEL_BITS
GL_VIEWPORT_BOUNDS_RANGE
GL_LAYER_PROVOKING_VERTEX
GL_VIEWPORT_INDEX_PROVOKING_VERTEX
GL_UNDEFINED_VERTEX
GL_SYNC_EVENT_ARB
GL_SYNC_EVENT_COMPLETE_ARB
GL_DEBUG_OUTPUT_SYNCHRONOUS_ARB
GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH_ARB
GL_DEBUG_CALLBACK_FUNCTION_ARB
GL_DEBUG_CALLBACK_USER_PARAM_ARB
GL_DEBUG_SOURCE_CL_API_ARB
GL_DEBUG_SOURCE_WINDOW_SYSTEM_ARB
GL_DEBUG_SOURCE_SHADER_COMPILER_ARB
GL_DEBUG_SOURCE_THIRD_PARTY_ARB
GL_DEBUG_SOURCE_APPLICATION_ARB
GL_DEBUG_SOURCE_OTHER_ARB
GL_DEBUG_TYPE_ERROR_ARB
GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR_ARB
GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR_ARB
GL_DEBUG_TYPE_PORTABILITY_ARB
GL_DEBUG_TYPE_PERFORMANCE_ARB
GL_DEBUG_TYPE_OTHER_ARB
GL_MAX_DEBUG_MESSAGE_LENGTH_ARB
GL_MAX_DEBUG_LOGGED_MESSAGES_ARB
GL_DEBUG_LOGGED_MESSAGES_ARB
GL_DEBUG_SEVERITY_HIGH_ARB
GL_DEBUG_SEVERITY_MEDIUM_ARB
GL_DEBUG_SEVERITY_LOW_ARB
GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT_ARB
GL_LOSE_CONTEXT_ON_RESET_ARB
GL_GUILTY_CONTEXT_RESET_ARB
GL_INNOCENT_CONTEXT_RESET_ARB
GL_UNKNOWN_CONTEXT_RESET_ARB
GL_RESET_NOTIFICATION_STRATEGY_ARB
GL_NO_RESET_NOTIFICATION_ARB
GL_UNPACK_COMPRESSED_BLOCK_WIDTH
GL_UNPACK_COMPRESSED_BLOCK_HEIGHT
GL_UNPACK_COMPRESSED_BLOCK_DEPTH
GL_UNPACK_COMPRESSED_BLOCK_SIZE
GL_PACK_COMPRESSED_BLOCK_WIDTH
GL_PACK_COMPRESSED_BLOCK_HEIGHT
GL_PACK_COMPRESSED_BLOCK_DEPTH
GL_PACK_COMPRESSED_BLOCK_SIZE
GL_NUM_SAMPLE_COUNTS
GL_MIN_MAP_BUFFER_ALIGNMENT
GL_ATOMIC_COUNTER_BUFFER
GL_ATOMIC_COUNTER_BUFFER_BINDING
GL_ATOMIC_COUNTER_BUFFER_START
GL_ATOMIC_COUNTER_BUFFER_SIZE
GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER
GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS
GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS
GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS
GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS
GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS
GL_MAX_VERTEX_ATOMIC_COUNTERS
GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS
GL_MAX_GEOMETRY_ATOMIC_COUNTERS
GL_MAX_FRAGMENT_ATOMIC_COUNTERS
GL_MAX_COMBINED_ATOMIC_COUNTERS
GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE
GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS
GL_ACTIVE_ATOMIC_COUNTER_BUFFERS
GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX
GL_UNSIGNED_INT_ATOMIC_COUNTER
GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT
GL_ELEMENT_ARRAY_BARRIER_BIT
GL_UNIFORM_BARRIER_BIT
GL_TEXTURE_FETCH_BARRIER_BIT
GL_SHADER_IMAGE_ACCESS_BARRIER_BIT
GL_COMMAND_BARRIER_BIT
GL_PIXEL_BUFFER_BARRIER_BIT
GL_TEXTURE_UPDATE_BARRIER_BIT
GL_BUFFER_UPDATE_BARRIER_BIT
GL_FRAMEBUFFER_BARRIER_BIT
GL_TRANSFORM_FEEDBACK_BARRIER_BIT
GL_ATOMIC_COUNTER_BARRIER_BIT
GL_ALL_BARRIER_BITS
GL_MAX_IMAGE_UNITS
GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS
GL_IMAGE_BINDING_NAME
GL_IMAGE_BINDING_LEVEL
GL_IMAGE_BINDING_LAYERED
GL_IMAGE_BINDING_LAYER
GL_IMAGE_BINDING_ACCESS
GL_IMAGE_1D
GL_IMAGE_2D
GL_IMAGE_3D
GL_IMAGE_2D_RECT
GL_IMAGE_CUBE
GL_IMAGE_BUFFER
GL_IMAGE_1D_ARRAY
GL_IMAGE_2D_ARRAY
GL_IMAGE_CUBE_MAP_ARRAY
GL_IMAGE_2D_MULTISAMPLE
GL_IMAGE_2D_MULTISAMPLE_ARRAY
GL_INT_IMAGE_1D
GL_INT_IMAGE_2D
GL_INT_IMAGE_3D
GL_INT_IMAGE_2D_RECT
GL_INT_IMAGE_CUBE
GL_INT_IMAGE_BUFFER
GL_INT_IMAGE_1D_ARRAY
GL_INT_IMAGE_2D_ARRAY
GL_INT_IMAGE_CUBE_MAP_ARRAY
GL_INT_IMAGE_2D_MULTISAMPLE
GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY
GL_UNSIGNED_INT_IMAGE_1D
GL_UNSIGNED_INT_IMAGE_2D
GL_UNSIGNED_INT_IMAGE_3D
GL_UNSIGNED_INT_IMAGE_2D_RECT
GL_UNSIGNED_INT_IMAGE_CUBE
GL_UNSIGNED_INT_IMAGE_BUFFER
GL_UNSIGNED_INT_IMAGE_1D_ARRAY
GL_UNSIGNED_INT_IMAGE_2D_ARRAY
GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY
GL_MAX_IMAGE_SAMPLES
GL_IMAGE_BINDING_FORMAT
GL_IMAGE_FORMAT_COMPATIBILITY_TYPE
GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE
GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS
GL_MAX_VERTEX_IMAGE_UNIFORMS
GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS
GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS
GL_MAX_GEOMETRY_IMAGE_UNIFORMS
GL_MAX_FRAGMENT_IMAGE_UNIFORMS
GL_MAX_COMBINED_IMAGE_UNIFORMS
GL_TEXTURE_IMMUTABLE_FORMAT
GL_COMPRESSED_RGBA_ASTC_4x4_KHR
GL_COMPRESSED_RGBA_ASTC_5x4_KHR
GL_COMPRESSED_RGBA_ASTC_5x5_KHR
GL_COMPRESSED_RGBA_ASTC_6x5_KHR
GL_COMPRESSED_RGBA_ASTC_6x6_KHR
GL_COMPRESSED_RGBA_ASTC_8x5_KHR
GL_COMPRESSED_RGBA_ASTC_8x6_KHR
GL_COMPRESSED_RGBA_ASTC_8x8_KHR
GL_COMPRESSED_RGBA_ASTC_10x5_KHR
GL_COMPRESSED_RGBA_ASTC_10x6_KHR
GL_COMPRESSED_RGBA_ASTC_10x8_KHR
GL_COMPRESSED_RGBA_ASTC_10x10_KHR
GL_COMPRESSED_RGBA_ASTC_12x10_KHR
GL_COMPRESSED_RGBA_ASTC_12x12_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR
GL_DEBUG_OUTPUT_SYNCHRONOUS
GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH
GL_DEBUG_CALLBACK_FUNCTION
GL_DEBUG_CALLBACK_USER_PARAM
GL_DEBUG_SOURCE_API
GL_DEBUG_SOURCE_WINDOW_SYSTEM
GL_DEBUG_SOURCE_SHADER_COMPILER
GL_DEBUG_SOURCE_THIRD_PARTY
GL_DEBUG_SOURCE_APPLICATION
GL_DEBUG_SOURCE_OTHER
GL_DEBUG_TYPE_ERROR
GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR
GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR
GL_DEBUG_TYPE_PORTABILITY
GL_DEBUG_TYPE_PERFORMANCE
GL_DEBUG_TYPE_OTHER
GL_DEBUG_TYPE_MARKER
GL_DEBUG_TYPE_PUSH_GROUP
GL_DEBUG_TYPE_POP_GROUP
GL_DEBUG_SEVERITY_NOTIFICATION
GL_MAX_DEBUG_GROUP_STACK_DEPTH
GL_DEBUG_GROUP_STACK_DEPTH
GL_BUFFER
GL_SHADER
GL_PROGRAM
GL_QUERY
GL_PROGRAM_PIPELINE
GL_SAMPLER
GL_DISPLAY_LIST
GL_MAX_LABEL_LENGTH
GL_MAX_DEBUG_MESSAGE_LENGTH
GL_MAX_DEBUG_LOGGED_MESSAGES
GL_DEBUG_LOGGED_MESSAGES
GL_DEBUG_SEVERITY_HIGH
GL_DEBUG_SEVERITY_MEDIUM
GL_DEBUG_SEVERITY_LOW
GL_DEBUG_OUTPUT
GL_CONTEXT_FLAG_DEBUG_BIT
GL_COMPUTE_SHADER
GL_MAX_COMPUTE_UNIFORM_BLOCKS
GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS
GL_MAX_COMPUTE_IMAGE_UNIFORMS
GL_MAX_COMPUTE_SHARED_MEMORY_SIZE
GL_MAX_COMPUTE_UNIFORM_COMPONENTS
GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS
GL_MAX_COMPUTE_ATOMIC_COUNTERS
GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS
GL_MAX_COMPUTE_LOCAL_INVOCATIONS
GL_MAX_COMPUTE_WORK_GROUP_COUNT
GL_MAX_COMPUTE_WORK_GROUP_SIZE
GL_COMPUTE_LOCAL_WORK_SIZE
GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER
GL_DISPATCH_INDIRECT_BUFFER
GL_DISPATCH_INDIRECT_BUFFER_BINDING
GL_COMPUTE_SHADER_BIT
GL_COMPRESSED_RGB8_ETC2
GL_COMPRESSED_SRGB8_ETC2
GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2
GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2
GL_COMPRESSED_RGBA8_ETC2_EAC
GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC
GL_COMPRESSED_R11_EAC
GL_COMPRESSED_SIGNED_R11_EAC
GL_COMPRESSED_RG11_EAC
GL_COMPRESSED_SIGNED_RG11_EAC
GL_PRIMITIVE_RESTART_FIXED_INDEX
GL_ANY_SAMPLES_PASSED_CONSERVATIVE
GL_MAX_ELEMENT_INDEX
GL_MAX_UNIFORM_LOCATIONS
GL_FRAMEBUFFER_DEFAULT_WIDTH
GL_FRAMEBUFFER_DEFAULT_HEIGHT
GL_FRAMEBUFFER_DEFAULT_LAYERS
GL_FRAMEBUFFER_DEFAULT_SAMPLES
GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS
GL_MAX_FRAMEBUFFER_WIDTH
GL_MAX_FRAMEBUFFER_HEIGHT
GL_MAX_FRAMEBUFFER_LAYERS
GL_MAX_FRAMEBUFFER_SAMPLES
GL_INTERNALFORMAT_SUPPORTED
GL_INTERNALFORMAT_PREFERRED
GL_INTERNALFORMAT_RED_SIZE
GL_INTERNALFORMAT_GREEN_SIZE
GL_INTERNALFORMAT_BLUE_SIZE
GL_INTERNALFORMAT_ALPHA_SIZE
GL_INTERNALFORMAT_DEPTH_SIZE
GL_INTERNALFORMAT_STENCIL_SIZE
GL_INTERNALFORMAT_SHARED_SIZE
GL_INTERNALFORMAT_RED_TYPE
GL_INTERNALFORMAT_GREEN_TYPE
GL_INTERNALFORMAT_BLUE_TYPE
GL_INTERNALFORMAT_ALPHA_TYPE
GL_INTERNALFORMAT_DEPTH_TYPE
GL_INTERNALFORMAT_STENCIL_TYPE
GL_MAX_WIDTH
GL_MAX_HEIGHT
GL_MAX_DEPTH
GL_MAX_LAYERS
GL_MAX_COMBINED_DIMENSIONS
GL_COLOR_COMPONENTS
GL_DEPTH_COMPONENTS
GL_STENCIL_COMPONENTS
GL_COLOR_RENDERABLE
GL_DEPTH_RENDERABLE
GL_STENCIL_RENDERABLE
GL_FRAMEBUFFER_RENDERABLE
GL_FRAMEBUFFER_RENDERABLE_LAYERED
GL_FRAMEBUFFER_BLEND
GL_READ_CL_PIXELS
GL_READ_CL_PIXELS_FORMAT
GL_READ_CL_PIXELS_TYPE
GL_TEXTURE_IMAGE_FORMAT
GL_TEXTURE_IMAGE_TYPE
GL_GET_TEXTURE_IMAGE_FORMAT
GL_GET_TEXTURE_IMAGE_TYPE
GL_MIPMAP
GL_MANUAL_GENERATE_MIPMAP
GL_AUTO_GENERATE_MIPMAP
GL_COLOR_ENCODING
GL_SRGB_READ
GL_SRGB_WRITE
GL_SRGB_DECODE_ARB
GL_FILTER
GL_VERTEX_TEXTURE
GL_TESS_CONTROL_TEXTURE
GL_TESS_EVALUATION_TEXTURE
GL_GEOMETRY_TEXTURE
GL_FRAGMENT_TEXTURE
GL_COMPUTE_TEXTURE
GL_TEXTURE_SHADOW
GL_TEXTURE_GATHER
GL_TEXTURE_GATHER_SHADOW
GL_SHADER_IMAGE_LOAD
GL_SHADER_IMAGE_STORE
GL_SHADER_IMAGE_ATOMIC
GL_IMAGE_TEXEL_SIZE
GL_IMAGE_COMPATIBILITY_CLASS
GL_IMAGE_CL_PIXEL_FORMAT
GL_IMAGE_CL_PIXEL_TYPE
GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST
GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST
GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE
GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE
GL_TEXTURE_COMPRESSED_BLOCK_WIDTH
GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT
GL_TEXTURE_COMPRESSED_BLOCK_SIZE
GL_CLEAR_BUFFER
GL_TEXTURE_VIEW
GL_VIEW_COMPATIBILITY_CLASS
GL_FULL_SUPPORT
GL_CAVEAT_SUPPORT
GL_IMAGE_CLASS_4_X_32
GL_IMAGE_CLASS_2_X_32
GL_IMAGE_CLASS_1_X_32
GL_IMAGE_CLASS_4_X_16
GL_IMAGE_CLASS_2_X_16
GL_IMAGE_CLASS_1_X_16
GL_IMAGE_CLASS_4_X_8
GL_IMAGE_CLASS_2_X_8
GL_IMAGE_CLASS_1_X_8
GL_IMAGE_CLASS_11_11_10
GL_IMAGE_CLASS_10_10_10_2
GL_VIEW_CLASS_128_BITS
GL_VIEW_CLASS_96_BITS
GL_VIEW_CLASS_64_BITS
GL_VIEW_CLASS_48_BITS
GL_VIEW_CLASS_32_BITS
GL_VIEW_CLASS_24_BITS
GL_VIEW_CLASS_16_BITS
GL_VIEW_CLASS_8_BITS
GL_VIEW_CLASS_S3TC_DXT1_RGB
GL_VIEW_CLASS_S3TC_DXT1_RGBA
GL_VIEW_CLASS_S3TC_DXT3_RGBA
GL_VIEW_CLASS_S3TC_DXT5_RGBA
GL_VIEW_CLASS_RGTC1_RED
GL_VIEW_CLASS_RGTC2_RG
GL_VIEW_CLASS_BPTC_UNORM
GL_VIEW_CLASS_BPTC_FLOAT
GL_UNIFORM
GL_UNIFORM_BLOCK
GL_PROGRAM_INPUT
GL_PROGRAM_OUTPUT
GL_BUFFER_VARIABLE
GL_SHADER_STORAGE_BLOCK
GL_VERTEX_SUBROUTINE
GL_TESS_CONTROL_SUBROUTINE
GL_TESS_EVALUATION_SUBROUTINE
GL_GEOMETRY_SUBROUTINE
GL_FRAGMENT_SUBROUTINE
GL_COMPUTE_SUBROUTINE
GL_VERTEX_SUBROUTINE_UNIFORM
GL_TESS_CONTROL_SUBROUTINE_UNIFORM
GL_TESS_EVALUATION_SUBROUTINE_UNIFORM
GL_GEOMETRY_SUBROUTINE_UNIFORM
GL_FRAGMENT_SUBROUTINE_UNIFORM
GL_COMPUTE_SUBROUTINE_UNIFORM
GL_TRANSFORM_FEEDBACK_VARYING
GL_ACTIVE_RESOURCES
GL_MAX_NAME_LENGTH
GL_MAX_NUM_ACTIVE_VARIABLES
GL_MAX_NUM_COMPATIBLE_SUBROUTINES
GL_NAME_LENGTH
GL_TYPE
GL_ARRAY_SIZE
GL_OFFSET
GL_BLOCK_INDEX
GL_ARRAY_STRIDE
GL_MATRIX_STRIDE
GL_IS_ROW_MAJOR
GL_ATOMIC_COUNTER_BUFFER_INDEX
GL_BUFFER_BINDING
GL_BUFFER_DATA_SIZE
GL_NUM_ACTIVE_VARIABLES
GL_ACTIVE_VARIABLES
GL_REFERENCED_BY_VERTEX_SHADER
GL_REFERENCED_BY_TESS_CONTROL_SHADER
GL_REFERENCED_BY_TESS_EVALUATION_SHADER
GL_REFERENCED_BY_GEOMETRY_SHADER
GL_REFERENCED_BY_FRAGMENT_SHADER
GL_REFERENCED_BY_COMPUTE_SHADER
GL_TOP_LEVEL_ARRAY_SIZE
GL_TOP_LEVEL_ARRAY_STRIDE
GL_LOCATION
GL_LOCATION_INDEX
GL_IS_PER_PATCH
GL_SHADER_STORAGE_BUFFER
GL_SHADER_STORAGE_BUFFER_BINDING
GL_SHADER_STORAGE_BUFFER_START
GL_SHADER_STORAGE_BUFFER_SIZE
GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS
GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS
GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS
GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS
GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS
GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS
GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS
GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS
GL_MAX_SHADER_STORAGE_BLOCK_SIZE
GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT
GL_SHADER_STORAGE_BARRIER_BIT
GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES
GL_DEPTH_STENCIL_TEXTURE_MODE
GL_TEXTURE_BUFFER_OFFSET
GL_TEXTURE_BUFFER_SIZE
GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT
GL_TEXTURE_VIEW_MIN_LEVEL
GL_TEXTURE_VIEW_NUM_LEVELS
GL_TEXTURE_VIEW_MIN_LAYER
GL_TEXTURE_VIEW_NUM_LAYERS
GL_TEXTURE_IMMUTABLE_LEVELS
GL_VERTEX_ATTRIB_BINDING
GL_VERTEX_ATTRIB_RELATIVE_OFFSET
GL_VERTEX_BINDING_DIVISOR
GL_VERTEX_BINDING_OFFSET
GL_VERTEX_BINDING_STRIDE
GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET
GL_MAX_VERTEX_ATTRIB_BINDINGS
GL_TEXTURE_MAX_ANISOTROPY_EXT
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT
GL_COMPRESSED_RGB_S3TC_DXT1_EXT
GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
GL_SRGB_EXT
GL_SRGB8_EXT
GL_SRGB_ALPHA_EXT
GL_SRGB8_ALPHA8_EXT
GL_SLUMINANCE_ALPHA_EXT
GL_SLUMINANCE8_ALPHA8_EXT
GL_SLUMINANCE_EXT
GL_SLUMINANCE8_EXT
GL_COMPRESSED_SRGB_EXT
GL_COMPRESSED_SRGB_ALPHA_EXT
GL_COMPRESSED_SLUMINANCE_EXT
GL_COMPRESSED_SLUMINANCE_ALPHA_EXT
GL_COMPRESSED_SRGB_S3TC_DXT1_EXT
GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT
GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT
GL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT
GL_MAX_VERTEX_ATTRIB_STRIDE
GL_MAP_PERSISTENT_BIT
GL_MAP_COHERENT_BIT
GL_DYNAMIC_STORAGE_BIT
GL_CLIENT_STORAGE_BIT
GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT
GL_BUFFER_IMMUTABLE_STORAGE
GL_BUFFER_STORAGE_FLAGS
GL_CLEAR_TEXTURE
GL_LOCATION_COMPONENT
GL_TRANSFORM_FEEDBACK_BUFFER_INDEX
GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE
GL_QUERY_BUFFER
GL_QUERY_BUFFER_BARRIER_BIT
GL_QUERY_BUFFER_BINDING
GL_QUERY_RESULT_NO_WAIT
GL_MIRROR_CLAMP_TO_EDGE
GL_COMPARE_R_TO_TEXTURE
GL_POINT_SPRITE
GL_MAX_TEXTURE_COORDS
GL_MAX_TEXTURE_UNITS
enum uicore::DrawBuffer
Drawing buffers.
Enumerator
buffer_none
buffer_front_left
buffer_front_right
buffer_back_left
buffer_back_right
buffer_front
buffer_back
buffer_left
buffer_right
buffer_front_and_back
enum uicore::EulerOrder strong
Euler angle rotation order.
Enumerator
xyz
xzy
yzx
yxz
zxy
zyx
enum uicore::EventUIPhase strong
UI event dispatch phase.
Enumerator
none
capturing
Event is not currently in any dispatch phase.
at_target
Capture phase (inverse bubble from root to the target view)
bubbling
Currently being dispatched to the target view.
Event bubbling up from target view to root
enum uicore::FaceSide
Front face modes.
Enumerator
face_clockwise
face_counter_clockwise
enum uicore::FileAccess strong
Enumerator
read
write
read_write
enum uicore::FilePathType strong
File path types.
Enumerator
file_system
Native file system path. (On windows, '/' are turned into '\'. On linux, '\' are turned into '/')
slashes
Path using slashes ('/').
enum uicore::FillMode
Polygon filling modes.
Enumerator
fill_point
fill_line
fill_polygon
enum uicore::FocusChangeType strong
Focus change type.
Enumerator
gained
lost
View received the focus.
View no longer has the focus
enum uicore::FocusPolicy strong
Automatic focus policy.
Enumerator
reject
accept
Only gain focus if set_focus is called directly.
Accept focus when the user tabs with the keyboard
enum uicore::FontStyle strong
Enumerator
normal
italic
oblique
enum uicore::FontWeight : int strong
Enumerator
thin
extra_light
light
normal
medium
semi_bold
bold
extra_bold
heavy
enum uicore::FrameBufferBindTarget
Framebuffer bind target.
Enumerator
framebuffer_draw
framebuffer_read
enum uicore::Handedness
Enumerator
handed_left
handed_right
enum uicore::InputCode
Enumerator
mouse_left
mouse_right
mouse_middle
mouse_wheel_up
mouse_wheel_down
mouse_xbutton1
mouse_xbutton2
mouse_count
joystick_x
joystick_y
joystick_z
joystick_rx
joystick_ry
joystick_rz
joystick_slider
joystick_dial
joystick_wheel
joystick_vx
joystick_vy
joystick_vz
joystick_vrx
joystick_vry
joystick_vrz
joystick_vslider0
joystick_vslider1
joystick_ax
joystick_ay
joystick_az
joystick_arx
joystick_ary
joystick_arz
joystick_aslider0
joystick_aslider1
joystick_fx
joystick_fy
joystick_fz
joystick_frx
joystick_fry
joystick_frz
joystick_fslider0
joystick_fslider1
joystick_button
joystick_hat
keycode_backspace
keycode_tab
keycode_clear
keycode_return
keycode_shift
keycode_control
keycode_menu
keycode_pause
keycode_kanji
keycode_escape
keycode_convert
keycode_nonconvert
keycode_space
keycode_prior
keycode_next
keycode_end
keycode_home
keycode_left
keycode_up
keycode_right
keycode_down
keycode_select
keycode_print
keycode_execute
keycode_insert
keycode_delete
keycode_help
keycode_0
keycode_1
keycode_2
keycode_3
keycode_4
keycode_5
keycode_6
keycode_7
keycode_8
keycode_9
keycode_a
keycode_b
keycode_c
keycode_d
keycode_e
keycode_f
keycode_g
keycode_h
keycode_i
keycode_j
keycode_k
keycode_l
keycode_m
keycode_n
keycode_o
keycode_p
keycode_q
keycode_r
keycode_s
keycode_t
keycode_u
keycode_v
keycode_w
keycode_x
keycode_y
keycode_z
keycode_lwin
keycode_rwin
keycode_apps
keycode_numpad0
keycode_numpad1
keycode_numpad2
keycode_numpad3
keycode_numpad4
keycode_numpad5
keycode_numpad6
keycode_numpad7
keycode_numpad8
keycode_numpad9
keycode_numpad_enter
keycode_multiply
keycode_add
keycode_separator
keycode_subtract
keycode_decimal
keycode_divide
keycode_f1
keycode_f2
keycode_f3
keycode_f4
keycode_f5
keycode_f6
keycode_f7
keycode_f8
keycode_f9
keycode_f10
keycode_f11
keycode_f12
keycode_f13
keycode_f14
keycode_f15
keycode_f16
keycode_f17
keycode_f18
keycode_f19
keycode_f20
keycode_f21
keycode_f22
keycode_f23
keycode_f24
keycode_numlock
keycode_scroll
keycode_lshift
keycode_rshift
keycode_lcontrol
keycode_rcontrol
keycode_lmenu
keycode_rmenu
keycode_enter
keycode_lapple
keycode_rapple
keycode_unknown
enum uicore::JsonType strong
Enumerator
undefined
null
object
array
number
boolean
string
enum uicore::Key strong
Enumeration of keyboard keys recognized on UICore.
Enumerator
none
backspace
tab
linefeed
clear
scroll
key_return
select
execute
escape
pause
print
space
prior
next
home
end
left
up
right
down
kanji
convert
nonconvert
separator
help
key_0
key_1
key_2
key_3
key_4
key_5
key_6
key_7
key_8
key_9
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
f1
f2
f3
f4
f5
f6
f7
f8
f9
f10
f11
f12
f13
f14
f15
f16
f17
f18
f19
f20
f21
f22
f23
f24
insert
key_delete
numpad_0
numpad_1
numpad_2
numpad_3
numpad_4
numpad_5
numpad_6
numpad_7
numpad_8
numpad_9
multiply
add
seperator
subtract
decimal
divide
lshift
rshift
lcontrol
rcontrol
lalt
loption
ralt
roption
lmenu
apps
rmenu
lsuper
lcmd
rsuper
rcmd
scrolllock
capslock
numlock
enum uicore::KeyEventType strong
Keyboard key event type.
Enumerator
none
press
release
enum uicore::LineBreakMode strong
Enumerator
clipping
truncating_head
truncating_tail
truncating_middle
enum uicore::LogicOp
Logic Op.
Enumerator
logic_clear
logic_and
logic_and_reverse
logic_copy
logic_and_inverted
logic_noop
logic_xor
logic_or
logic_nor
logic_equiv
logic_invert
logic_or_reverse
logic_copy_inverted
logic_or_inverted
logic_nand
logic_set
enum uicore::Origin
Alignment origins.
Enumerator
origin_top_left
origin_top_center
origin_top_right
origin_center_left
origin_center
origin_center_right
origin_bottom_left
origin_bottom_center
origin_bottom_right
enum uicore::PathFillMode strong
Enumerator
alternate
winding
enum uicore::PNGColorType
Enumerator
png_color_type_gray
png_color_type_gray_alpha
png_color_type_palette
png_color_type_rgb
png_color_type_rgb_alpha
png_color_mask_palette
png_color_mask_color
png_color_mask_alpha
enum uicore::PNGFilterMethod
Enumerator
png_filter_type_default
png_intrapixel_differencing
enum uicore::PNGInterlaceType
Enumerator
png_interlace_none
png_interlace_adam7
enum uicore::PNGOffsetUnitType
Enumerator
png_offset_pixel
png_offset_micrometer
enum uicore::PNGResolutionUnitType
Enumerator
png_resolution_unknown
png_resolution_meter
enum uicore::PNGsRGBIntent
Enumerator
png_srgb_intent_saturation
png_srgb_intent_perceptual
png_srgb_intent_absolute
png_srgb_intent_relative
enum uicore::PNGUnknownChunkLocation
Enumerator
png_before_plte
png_before_idat
png_after_idat
enum uicore::PointerButton strong
Pointer button.
Enumerator
none
left
No button specified.
right
Left button.
middle
Right button.
wheel_up
Middle/wheel button.
wheel_down
Wheel up tick.
xbutton1
Wheel down tick.
xbutton2
Extra button 1.
xbutton3
Extra button 2.
xbutton4
Extra button 3.
xbutton5
Extra button 4.
xbutton6
Extra button 5.
Extra button 6
enum uicore::PointerEventType strong
Pointer event type.
Enumerator
none
enter
No event type specified.
leave
Pointer entered area.
move
Pointer left area.
press
Pointer moved above area.
release
Pointer pressed.
double_click
Pointer released.
promixity_change
Pointer double click pressed.
Pen proximity changed
enum uicore::PointSpriteOrigin
Point Sprite Origin.
Enumerator
origin_upper_left
origin_lower_left
enum uicore::PolygonOrientation
Polygon orientations.
Enumerator
cl_clockwise
cl_counter_clockwise
enum uicore::PrimitivesType
Primitive types.
Enumerator
type_points
type_line_strip
type_line_loop
type_lines
type_triangle_strip
type_triangle_fan
type_triangles
enum uicore::ShaderLanguage
Shader language used.
Enumerator
shader_glsl
shader_hlsl
shader_fixed_function
num_shader_languages
enum uicore::ShaderType : int strong
Shader Type.
Enumerator
vertex
geometry
fragment
tess_evaluation
tess_control
compute
num_types
enum uicore::SpanAlign strong
Span Align.
Enumerator
left
right
center
justify
enum uicore::StagingDirection : int strong
Staging usage direction.
Enumerator
to_gpu
Use of the pixel buffer is to send data to the gpu.
from_gpu
Use of the pixel buffer is to retrieve data from the gpu.
enum uicore::StandardCursor strong
Standard Cursor.
Enumerator
arrow
appstarting
cross
hand
ibeam
no
size_all
size_nesw
size_ns
size_nwse
size_we
uparrow
wait
enum uicore::StandardProgram
Standard Program.
Enumerator
program_color_only
program_single_texture
program_sprite
program_path
enum uicore::StencilOp
Stencil operations.
Enumerator
stencil_keep
stencil_zero
stencil_replace
stencil_incr
stencil_decr
stencil_invert
stencil_incr_wrap
stencil_decr_wrap
enum uicore::StyleDimension strong
Unit of a style value.
Enumerator
px
em
device independent pixel (96 dpi)
pt
relative to font-size length property
mm
point, 1/72 inch
cm
millimeter
in
centimeter
pc
inch, 1in is equal to 2.54cm
ex
picas, 1pc is equal to 12pt
ch
x-height, 1ex is equal to 0.5em
rem
used advance measure of the "0" glyph found in the font used to render it
vw
computed value of 'font-size' on the root element
vh
1/100 viewport (initial containing box) width
vmin
1/100 viewport (initial containing box) height
vmax
the smaller of vw or vh
deg
the larger of vw or vh
grad
degrees (360 in a full circle)
rad
gradians/gons/grades (400 in a full circle)
turn
radians (2*PI in a full circle)
s
turns (1 in a full circle)
ms
seconds
hz
milliseconds
khz
hertz
dpi
kilohertz
dpcm
dots per inch
dppx
dots per cm
dots per px unit
enum uicore::StyleTokenType strong
Token types recognized by the style tokenzier.
Enumerator
null
ident
No more tokens.
atkeyword
Identifier.
string
@ keyword
invalid
String.
hash
Syntax error.
number
Hash
percentage
Number.
dimension
Percentage number.
uri
Number with dimension.
unicode_range
Url function.
cdo
Unicode range.
cdc
HTLM comment begin.
colon
HTML comment end –>
semi_colon
:
curly_brace_begin
;
curly_brace_end
{
bracket_begin
}
bracket_end
(
square_bracket_begin
)
square_bracket_end
[
whitespace
]
comment
Whitespace.
function
C style comment block.
includes
Function name.
dashmatch
~=
delim
|=
Any other character
enum uicore::StyleValueType strong
Style value type.
Enumerator
undefined
keyword
value undefined
length
value is a keyword
percentage
value is a length
number
value is a percentage number
string
value is a number
url
value is a text string
color
value is an url
angle
value is a color
time
value is an angle
frequency
value is a time
resolution
value is a frequency
value is a resolution
enum uicore::TextAlignment strong
Enumerator
left
right
center
justify
enum uicore::TextureCompareMode
Texture compare modes.
Enumerator
comparemode_none
comparemode_compare_r_to_texture
enum uicore::TextureCubeDirection
Texture cube directions.
Enumerator
cl_cube_positive_x
cl_cube_negative_x
cl_cube_positive_y
cl_cube_negative_y
cl_cube_positive_z
cl_cube_negative_z
enum uicore::TextureDimensions
Texture dimensions.
Enumerator
texture_1d
texture_1d_array
texture_2d
texture_2d_array
texture_3d
texture_cube
texture_cube_array
enum uicore::TextureFilter
Texture filters.
Enumerator
filter_nearest
filter_linear
filter_nearest_mipmap_nearest
filter_nearest_mipmap_linear
filter_linear_mipmap_nearest
filter_linear_mipmap_linear
enum uicore::TextureFormat
Texture format.
Enumerator
tf_rgba8
tf_rgb8
tf_bgra8
tf_bgr8
tf_stencil_index1
tf_stencil_index4
tf_stencil_index8
tf_stencil_index16
tf_r8
tf_r8_snorm
tf_r16
tf_r16_snorm
tf_rg8
tf_rg8_snorm
tf_rg16
tf_rg16_snorm
tf_r3_g3_b2
tf_rgb4
tf_rgb5
tf_rgb8_snorm
tf_rgb10
tf_rgb12
tf_rgb16
tf_rgb16_snorm
tf_rgba2
tf_rgba4
tf_rgb5_a1
tf_rgba8_snorm
tf_rgb10_a2
tf_rgba12
tf_rgba16
tf_rgba16_snorm
tf_srgb8
tf_srgb8_alpha8
tf_r16f
tf_rg16f
tf_rgb16f
tf_rgba16f
tf_r32f
tf_rg32f
tf_rgb32f
tf_rgba32f
tf_r11f_g11f_b10f
tf_rgb9_e5
tf_r8i
tf_r8ui
tf_r16i
tf_r16ui
tf_r32i
tf_r32ui
tf_rg8i
tf_rg8ui
tf_rg16i
tf_rg16ui
tf_rg32i
tf_rg32ui
tf_rgb8i
tf_rgb8ui
tf_rgb16i
tf_rgb16ui
tf_rgb32i
tf_rgb32ui
tf_rgba8i
tf_rgba8ui
tf_rgba16i
tf_rgba16ui
tf_rgba32i
tf_rgba32ui
tf_depth_component16
tf_depth_component24
tf_depth_component32
tf_depth_component32f
tf_depth24_stencil8
tf_depth32f_stencil8
tf_compressed_red
tf_compressed_rg
tf_compressed_rgb
tf_compressed_rgba
tf_compressed_srgb
tf_compressed_srgb_alpha
tf_compressed_red_rgtc1
tf_compressed_signed_red_rgtc1
tf_compressed_rg_rgtc2
tf_compressed_signed_rg_rgtc2
tf_compressed_rgb_s3tc_dxt1
tf_compressed_rgba_s3tc_dxt1
tf_compressed_rgba_s3tc_dxt3
tf_compressed_rgba_s3tc_dxt5
tf_compressed_srgb_s3tc_dxt1
tf_compressed_srgb_alpha_s3tc_dxt1
tf_compressed_srgb_alpha_s3tc_dxt3
tf_compressed_srgb_alpha_s3tc_dxt5
enum uicore::TextureGroupAllocationPolicy strong
TextureGroup allocation policy.
Enumerator
create_new_texture
search_previous_textures
enum uicore::TextureImageYAxis
Y axis direction for viewports, clipping rects, textures and render targets.
Enumerator
y_axis_bottom_up
OpenGL, origin is lower left with Y going upwards.
y_axis_top_down
Direct3D, origin is upper left with Y going downwards.
enum uicore::TextureSubtype
Texture Subtype.
Enumerator
subtype_cube_map_positive_x
subtype_cube_map_negative_x
subtype_cube_map_positive_y
subtype_cube_map_negative_y
subtype_cube_map_positive_z
subtype_cube_map_negative_z
enum uicore::TextureWrapMode
Texture coordinate wrapping modes.
Enumerator
wrap_clamp_to_edge
wrap_repeat
wrap_mirrored_repeat
enum uicore::VertexAttributeDataType
Primitives array description.
Enumerator
type_unsigned_byte
type_unsigned_short
type_unsigned_int
type_byte
type_short
type_int
type_float
enum uicore::WindowShowType strong
Enumerator
hide
show
show_no_activate
normal
maximized
minimized
maximize
minimize
minimize_no_activate
restore
show_default
enum uicore::XmlNodeType strong
Enumerator
element
attribute
text
cdata
comment
document
document_fragment
enum uicore::XmlTokenType strong
Enumerator
null
element
text
cdata
processing_instruction
comment
doctype
enum uicore::XmlTokenVariant strong
Enumerator
begin
end
single
Function Documentation
template<class R , class T , class... Args> std::function<R(Args...)> uicore::bind_member (T * instance, R(T::*)(Args...) method)
Referenced by uicore::Signal< FuncType >::connect().
template<typename A , typename B , typename C > C uicore::clamp (A val, B minval, C maxval) inline
References max(), and min().
Referenced by smoothstep().
Key uicore::decode_ic (InputCode)
float uicore::degrees (float radians) inline
Convert a quantity in radians to degrees.
References PI.
Referenced by degrees().
double uicore::degrees (double radians) inline
References PI_D.
template<typename T > Vec2<T> uicore::degrees (const Vec2< T > & radians)
References degrees(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename T > Vec3<T> uicore::degrees (const Vec3< T > & radians)
References degrees(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename T > Vec4<T> uicore::degrees (const Vec4< T > & radians)
References degrees(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
template<typename T , typename... Args> std::unique_ptr<T> uicore::make_unique (Args &&... args)
template<typename A , typename B > A uicore::max (A a, B b) inline
Referenced by uicore::Rectx< int >::bounding_rect(), clamp(), uicore::Rectx< int >::clip(), max(), and uicore::Rectx< int >::overlap().
template<typename Type > Vec2<Type> uicore::max (Vec2< Type > a, Vec2< Type > b) inline
References max(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename Type > Vec3<Type> uicore::max (Vec3< Type > a, Vec3< Type > b) inline
References max(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename Type > Vec4<Type> uicore::max (Vec4< Type > a, Vec4< Type > b) inline
References max(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
template<typename A , typename B > A uicore::min (A a, B b) inline
Referenced by uicore::Rectx< int >::bounding_rect(), clamp(), uicore::Rectx< int >::clip(), min(), and uicore::Rectx< int >::overlap().
template<typename Type > Vec2<Type> uicore::min (Vec2< Type > a, Vec2< Type > b) inline
References min(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename Type > Vec3<Type> uicore::min (Vec3< Type > a, Vec3< Type > b) inline
References min(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename Type > Vec4<Type> uicore::min (Vec4< Type > a, Vec4< Type > b) inline
References min(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
template<typename A , typename B , typename C > A uicore::mix (A a, B b, C mix) inline
float uicore::normalize_180 (float degrees)
Converts angle to range [-180,180] degrees.
Referenced by normalize_180().
double uicore::normalize_180 (double degrees)
template<typename T > Vec2<T> uicore::normalize_180 (const Vec2< T > & degrees)
References normalize_180(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename T > Vec3<T> uicore::normalize_180 (const Vec3< T > & degrees)
References normalize_180(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename T > Vec4<T> uicore::normalize_180 (const Vec4< T > & degrees)
References normalize_180(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
float uicore::normalize_2pi (float radians)
Converts angle to range [0,2*PI] radians.
Referenced by normalize_2pi().
double uicore::normalize_2pi (double radians)
template<typename T > Vec2<T> uicore::normalize_2pi (const Vec2< T > & radians)
References normalize_2pi(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename T > Vec3<T> uicore::normalize_2pi (const Vec3< T > & radians)
References normalize_2pi(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename T > Vec4<T> uicore::normalize_2pi (const Vec4< T > & radians)
References normalize_2pi(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
float uicore::normalize_360 (float degrees)
Converts angle to range [0,360] degrees.
Referenced by normalize_360().
double uicore::normalize_360 (double degrees)
template<typename T > Vec2<T> uicore::normalize_360 (const Vec2< T > & degrees)
References normalize_360(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename T > Vec3<T> uicore::normalize_360 (const Vec3< T > & degrees)
References normalize_360(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename T > Vec4<T> uicore::normalize_360 (const Vec4< T > & degrees)
References normalize_360(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
float uicore::normalize_pi (float radians)
Converts angle to range [-PI,PI] radians.
Referenced by normalize_pi().
double uicore::normalize_pi (double radians)
template<typename T > Vec2<T> uicore::normalize_pi (const Vec2< T > & radians)
References normalize_pi(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename T > Vec3<T> uicore::normalize_pi (const Vec3< T > & radians)
References normalize_pi(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename T > Vec4<T> uicore::normalize_pi (const Vec4< T > & radians)
References normalize_pi(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
template<typename Type > Vec3<Type> uicore::operator* (const Vec3< Type > & v1, const Vec3< Type > & v2)
operator.
template<typename Type > Vec3<Type> uicore::operator* (Type s, const Vec3< Type > & v)
operator.
template<typename Type > Vec3<Type> uicore::operator* (const Vec3< Type > & v, Type s)
operator.
template<typename Type > Vec2<Type> uicore::operator* (const Vec2< Type > & v1, const Vec2< Type > & v2)
operator.
template<typename Type > Vec2<Type> uicore::operator* (Type s, const Vec2< Type > & v)
operator.
template<typename Type > Vec2<Type> uicore::operator* (const Vec2< Type > & v, Type s)
operator.
template<typename Type > Vec3<Type> uicore::operator* (const Vec3< Type > & v, const Mat3< Type > & matrix)
Matrix is assumed to be in the Column-Major matrix format (opengl native)
Note: "vec = vector * matrix" is different to "vec = matrix * vector"
template<typename Type > Vec2<Type> uicore::operator* (const Vec2< Type > & v, const Mat2< Type > & matrix)
template<typename Type > Vec3<Type> uicore::operator* (const Mat3< Type > & matrix, const Vec3< Type > & v)
Matrix is assumed to be in the Column-Major matrix format (opengl native)
Note: "vec = vector * matrix" is different to "vec = matrix * vector"
template<typename Type > Vec2<Type> uicore::operator* (const Mat2< Type > & matrix, const Vec2< Type > & v)
template<typename Type > Vec4<Type> uicore::operator* (const Vec4< Type > & v1, const Vec4< Type > & v2)
operator.
template<typename Type > Vec4<Type> uicore::operator* (Type s, const Vec4< Type > & v)
operator.
template<typename Type > Vec4<Type> uicore::operator* (const Vec4< Type > & v, Type s)
operator.
template<typename Type > Vec4<Type> uicore::operator* (const Vec4< Type > & v, const Mat4< Type > & matrix)
template<typename Type > Vec4<Type> uicore::operator* (const Mat4< Type > & matrix, const Vec4< Type > & v)
template<typename Type > Vec3<Type> uicore::operator+ (const Vec3< Type > & v1, const Vec3< Type > & v2)
operator.
template<typename Type > Vec3<Type> uicore::operator+ (Type s, const Vec3< Type > & v)
operator.
template<typename Type > Vec3<Type> uicore::operator+ (const Vec3< Type > & v, Type s)
operator.
template<typename Type > Vec2<Type> uicore::operator+ (const Vec2< Type > & v1, const Vec2< Type > & v2)
operator.
template<typename Type > Vec2<Type> uicore::operator+ (Type s, const Vec2< Type > & v)
operator.
template<typename Type > Vec2<Type> uicore::operator+ (const Vec2< Type > & v, Type s)
operator.
template<typename Type > Vec4<Type> uicore::operator+ (const Vec4< Type > & v1, const Vec4< Type > & v2)
operator.
template<typename Type > Vec4<Type> uicore::operator+ (Type s, const Vec4< Type > & v)
operator.
template<typename Type > Vec4<Type> uicore::operator+ (const Vec4< Type > & v, Type s)
operator.
template<typename Type > Vec3<Type> uicore::operator- (const Vec3< Type > & v1, const Vec3< Type > & v2)
operator.
template<typename Type > Vec3<Type> uicore::operator- (Type s, const Vec3< Type > & v)
operator.
template<typename Type > Vec3<Type> uicore::operator- (const Vec3< Type > & v, Type s)
operator.
template<typename Type > Vec2<Type> uicore::operator- (const Vec2< Type > & v1, const Vec2< Type > & v2)
operator.
template<typename Type > Vec2<Type> uicore::operator- (Type s, const Vec2< Type > & v)
operator.
template<typename Type > Vec2<Type> uicore::operator- (const Vec2< Type > & v, Type s)
operator.
template<typename Type > Vec4<Type> uicore::operator- (const Vec4< Type > & v1, const Vec4< Type > & v2)
operator.
template<typename Type > Vec4<Type> uicore::operator- (Type s, const Vec4< Type > & v)
operator.
template<typename Type > Vec4<Type> uicore::operator- (const Vec4< Type > & v, Type s)
operator.
template<typename Type > Vec3<Type> uicore::operator/ (const Vec3< Type > & v1, const Vec3< Type > & v2)
/ operator.
template<typename Type > Vec3<Type> uicore::operator/ (Type s, const Vec3< Type > & v)
/ operator.
template<typename Type > Vec3<Type> uicore::operator/ (const Vec3< Type > & v, Type s)
/ operator.
template<typename Type > Vec2<Type> uicore::operator/ (const Vec2< Type > & v1, const Vec2< Type > & v2)
/ operator.
template<typename Type > Vec2<Type> uicore::operator/ (Type s, const Vec2< Type > & v)
/ operator.
template<typename Type > Vec2<Type> uicore::operator/ (const Vec2< Type > & v, Type s)
/ operator.
template<typename Type > Vec4<Type> uicore::operator/ (const Vec4< Type > & v1, const Vec4< Type > & v2)
/ operator.
template<typename Type > Vec4<Type> uicore::operator/ (Type s, const Vec4< Type > & v)
/ operator.
template<typename Type > Vec4<Type> uicore::operator/ (const Vec4< Type > & v, Type s)
/ operator.
template<typename T > T uicore::pow2 (T value) inline
float uicore::radians (float degrees) inline
Convert a quantity in degrees to radians.
References PI.
Referenced by radians().
double uicore::radians (double degrees) inline
References PI_D.
template<typename T > Vec2<T> uicore::radians (const Vec2< T > & degrees)
References radians(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename T > Vec3<T> uicore::radians (const Vec3< T > & degrees)
References radians(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename T > Vec4<T> uicore::radians (const Vec4< T > & degrees)
References radians(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
Rectd uicore::RectdPS (double x, double y, double width, double height) inline
Rectf uicore::RectfPS (float x, float y, float width, float height) inline
Rect uicore::RectPS (int x, int y, int width, int height) inline
int uicore::sign (int x) inline
Referenced by sign().
float uicore::sign (float x) inline
References f.
double uicore::sign (double x) inline
template<typename Type > Vec2<Type> uicore::sign (const Vec2< Type > & x) inline
References sign(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename Type > Vec3<Type> uicore::sign (const Vec3< Type > & x) inline
References sign(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename Type > Vec4<Type> uicore::sign (const Vec4< Type > & x) inline
References sign(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
template<typename A , typename B , typename C > C uicore::smoothstep (A edge0, B edge1, C x) inline
References clamp(), and t.
int uicore::step (int edge, int x) inline
Referenced by step().
long long uicore::step (long long edge, long long x) inline
float uicore::step (float edge, float x) inline
double uicore::step (double edge, double x) inline
template<typename Type > Vec2<Type> uicore::step (const Vec2< Type > & edge, const Vec2< Type > & x) inline
References step(), uicore::Vec2< Type >::x, and uicore::Vec2< Type >::y.
template<typename Type > Vec3<Type> uicore::step (const Vec3< Type > & edge, const Vec3< Type > & x) inline
References step(), uicore::Vec3< Type >::x, uicore::Vec3< Type >::y, and uicore::Vec3< Type >::z.
template<typename Type > Vec4<Type> uicore::step (const Vec4< Type > & edge, const Vec4< Type > & x) inline
References step(), uicore::Vec4< Type >::w, uicore::Vec4< Type >::x, uicore::Vec4< Type >::y, and uicore::Vec4< Type >::z.
std::string uicore::string_format (const std::string & format) inline
See uicore::StringFormat for details.
Referenced by uicore::Style::set(), and uicore::Style::to_rgba().
template<class Arg1 > std::string uicore::string_format (const std::string & format, Arg1 arg1)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
template<class Arg1 , class Arg2 > std::string uicore::string_format (const std::string & format, Arg1 arg1, Arg2 arg2)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 > std::string uicore::string_format (const std::string & format, Arg1 arg1, Arg2 arg2, Arg3 arg3)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 > std::string uicore::string_format (const std::string & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 > std::string uicore::string_format (const std::string & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 > std::string uicore::string_format (const std::string & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
template<class Arg1 , class Arg2 , class Arg3 , class Arg4 , class Arg5 , class Arg6 , class Arg7 > std::string uicore::string_format (const std::string & format, Arg1 arg1, Arg2 arg2, Arg3 arg3, Arg4 arg4, Arg5 arg5, Arg6 arg6, Arg7 arg7)
See uicore::StringFormat for details.
References f, uicore::StringFormat::result(), and uicore::StringFormat::set_arg().
Variable Documentation
const float uicore::PI = 3.14159274101257f
Referenced by degrees(), and radians().
const double uicore::PI_D = 3.141592653589793115998
Referenced by degrees(), and radians().
const float uicore::PI_F = 3.14159274101257f
© ClanLib.org